force-app/main/default/objects/NS_Partner__c/NS_Partner__c.object-meta.xml
<CustomObject>
    <description>Custom object to display Partner Related List in Opportunities Object.</description>
    <label>Partner</label>
    <nameField>
        <displayFormat>PTNR-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Partner__c/fields/NS_Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field gets populated from the selected Partner Account in the related opportunity.</description>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>Partners3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Partner__c/fields/NS_Partner_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type__c</fullName>
    <description>This field gets populated from the selected Partner Account Type field in the related opportunity</description>
    <label>Partner Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Partner__c/fields/NS_Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NS_Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This looks up to the related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>NS_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_1__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_2__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner Account 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_3__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account 3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner Account 3)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_4__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to relate other accounts part of the deal or opportunity</description>
    <label>Partner Account 4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities4</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_Type_1__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type_1__c</fullName>
    <description>describe the role or type of partner this account is in relation to the opportunity</description>
    <label>Partner Account Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_Type_2__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type_2__c</fullName>
    <description>describe the role or type of partner this account is in relation to the opportunity</description>
    <label>Partner Account Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_Type_3__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type_3__c</fullName>
    <description>describe the role or type of partner this account is in relation to the opportunity</description>
    <label>Partner Account Type 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Partner_Account_Type_4__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type_4__c</fullName>
    <description>describe the role or type of partner this account is in relation to the opportunity</description>
    <label>Partner Account Type 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NS_PartnerTriggerHelper.cls
public class NS_PartnerTriggerHelper {
    
    
    public static void insertRelatedRecord(List<NS_Partner__c> ListPartner){
        Set<id> OppId = new Set<id>();
        List<Opportunity> listToUpdate = new  List<Opportunity>();
        map<id,Opportunity> mapUpdate = new map<id,Opportunity>();
        for(NS_Partner__c recPartner :ListPartner){
            OppId.add(recPartner.NS_Related_Opportunity__c);
        }
        
        map<id, Opportunity> mapOpp = new map<id, Opportunity>([Select id,
                                                                NS_Partner_Account_1__c,
                                                                NS_Partner_Account_Type_1__c,
                                                                NS_Partner_Account_2__c,
                                                                NS_Partner_Account_Type_2__c,
                                                                NS_Partner_Account_3__c,
                                                                NS_Partner_Account_Type_3__c,
                                                                NS_Partner_Account_4__c,
                                                                NS_Partner_Account_Type_4__c
                                                                from Opportunity where id in :OppId]);
        for(NS_Partner__c recFinalPartner :ListPartner){
            Opportunity parentOpportunity = mapOpp.get(recFinalPartner.NS_Related_Opportunity__c);
            
            if(parentOpportunity.NS_Partner_Account_1__c==null){
                parentOpportunity.NS_Partner_Account_1__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_1__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }Else if(parentOpportunity.NS_Partner_Account_2__c==null){
                parentOpportunity.NS_Partner_Account_2__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_2__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_3__c==null){
                parentOpportunity.NS_Partner_Account_3__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_3__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_4__c==null){
                parentOpportunity.NS_Partner_Account_4__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_4__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }
            
        }
        
        if(listToUpdate.size()>0){
            mapUpdate.putAll(listToUpdate);
        }
        update mapUpdate.values();
        
    }
    
    public static void updateRelatedRecord(List<NS_Partner__c> ListPartner){
        Set<id> OppId = new Set<id>();
        map<id,Opportunity> mapUpdate = new map<id,Opportunity>();
        List<Opportunity> listToUpdate = new  List<Opportunity>();
        for(NS_Partner__c recPartner :ListPartner){
            OppId.add(recPartner.NS_Related_Opportunity__c);
        }
        map<id, Opportunity> mapOpp = new map<id, Opportunity>([Select id,
                                                                NS_Partner_Account_1__c,
                                                                NS_Partner_Account_Type_1__c,
                                                                NS_Partner_Account_2__c,
                                                                NS_Partner_Account_Type_2__c,
                                                                NS_Partner_Account_3__c,
                                                                NS_Partner_Account_Type_3__c,
                                                                NS_Partner_Account_4__c,
                                                                NS_Partner_Account_Type_4__c
                                                                from Opportunity where id in :OppId]);
        for(NS_Partner__c recFinalPartner :ListPartner){
            Opportunity parentOpportunity = mapOpp.get(recFinalPartner.NS_Related_Opportunity__c);
            NS_Partner__c oldPartnerRecord = (NS_Partner__c)trigger.oldmap.get(recFinalPartner.ID);
            
            if(parentOpportunity.NS_Partner_Account_1__c==oldPartnerRecord.NS_Partner_Account__c && parentOpportunity.NS_Partner_Account_Type_1__c==oldPartnerRecord.NS_Partner_Account_Type__c){
                parentOpportunity.NS_Partner_Account_1__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_1__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }Else if(parentOpportunity.NS_Partner_Account_2__c==oldPartnerRecord.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_2__c==oldPartnerRecord.NS_Partner_Account_Type__c){
                parentOpportunity.NS_Partner_Account_2__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_2__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_3__c==oldPartnerRecord.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_3__c==oldPartnerRecord.NS_Partner_Account_Type__c){
                parentOpportunity.NS_Partner_Account_3__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_3__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_4__c==oldPartnerRecord.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_4__c==oldPartnerRecord.NS_Partner_Account_Type__c){
                parentOpportunity.NS_Partner_Account_4__c=recFinalPartner.NS_Partner_Account__c;
                parentOpportunity.NS_Partner_Account_Type_4__c=recFinalPartner.NS_Partner_Account_Type__c;
                listToUpdate.add(parentOpportunity);
            }
            
        }
        if(listToUpdate.size()>0){
            mapUpdate.putAll(listToUpdate);
        }
        update mapUpdate.values();
        
        
    }
    
    public static void deleteRelatedRecord(List<NS_Partner__c> ListPartner){
        Set<id> OppId = new Set<id>();
        map<id,Opportunity> mapUpdate = new map<id,Opportunity>();
        List<Opportunity> listToUpdate = new  List<Opportunity>();
        for(NS_Partner__c recPartner :ListPartner){
            OppId.add(recPartner.NS_Related_Opportunity__c);
        }
        map<id, Opportunity> mapOpp = new map<id, Opportunity>([Select id,
                                                                NS_Partner_Account_1__c,
                                                                NS_Partner_Account_Type_1__c,
                                                                NS_Partner_Account_2__c,
                                                                NS_Partner_Account_Type_2__c,
                                                                NS_Partner_Account_3__c,
                                                                NS_Partner_Account_Type_3__c,
                                                                NS_Partner_Account_4__c,
                                                                NS_Partner_Account_Type_4__c
                                                                from Opportunity where id in :OppId]);
        
        
        List<NS_Partner__c> ListrRelatedPartner =  [Select id,NS_Related_Opportunity__c,NS_Partner_Account__c,NS_Partner_Account_Type__c from NS_Partner__c where NS_Related_Opportunity__c=:OppId];
       
        List<NS_Partner__c> notUsedPartner = new List<NS_Partner__c>();
        
        
        for(NS_Partner__c relPartRec :ListrRelatedPartner){
            Opportunity parentOpp = mapOpp.get(relPartRec.NS_Related_Opportunity__c);
            
            list<String> oppAccountDetail = new List<String>();
            
            if(parentOpp.NS_Partner_Account_1__c!= null && parentOpp.NS_Partner_Account_Type_1__c!= null){
                oppAccountDetail.add
                    ( parentOpp.NS_Partner_Account_1__c+
                     parentOpp.NS_Partner_Account_Type_1__c);
            }
            if(parentOpp.NS_Partner_Account_2__c!= null && parentOpp.NS_Partner_Account_Type_2__c!= null){
                oppAccountDetail.add
                    ( parentOpp.NS_Partner_Account_2__c+
                     parentOpp.NS_Partner_Account_Type_2__c);
            }
            if(parentOpp.NS_Partner_Account_3__c!= null && parentOpp.NS_Partner_Account_Type_3__c!= null){
                oppAccountDetail.add
                    ( parentOpp.NS_Partner_Account_3__c+
                     parentOpp.NS_Partner_Account_Type_3__c);
            }
            if(parentOpp.NS_Partner_Account_4__c!= null && parentOpp.NS_Partner_Account_Type_4__c!= null){
                oppAccountDetail.add
                    ( parentOpp.NS_Partner_Account_4__c+
                     parentOpp.NS_Partner_Account_Type_4__c);
            }
   

            if(!oppAccountDetail.contains(relPartRec.NS_Partner_Account__c+relPartRec.NS_Partner_Account_Type__c)){
                notUsedPartner.add(relPartRec);
            }
        }   
        
        
        for(NS_Partner__c recFinalPartner :ListPartner){
            Opportunity parentOpportunity = mapOpp.get(recFinalPartner.NS_Related_Opportunity__c);
            
            
            
            if(parentOpportunity.NS_Partner_Account_1__c==recFinalPartner.NS_Partner_Account__c && parentOpportunity.NS_Partner_Account_Type_1__c==recFinalPartner.NS_Partner_Account_Type__c){
                if(notUsedPartner.size()>0){
                    NS_Partner__c unusedPartner = notUsedPartner[0];
                    parentOpportunity.NS_Partner_Account_1__c=unusedPartner.NS_Partner_Account__c;
                    parentOpportunity.NS_Partner_Account_Type_1__c=unusedPartner.NS_Partner_Account_Type__c;
                    notUsedPartner.remove(0);
                }else{
                    parentOpportunity.NS_Partner_Account_1__c=null;
                    parentOpportunity.NS_Partner_Account_Type_1__c=null;
                }
                
                
                listToUpdate.add(parentOpportunity);
            }Else if(parentOpportunity.NS_Partner_Account_2__c==recFinalPartner.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_2__c==recFinalPartner.NS_Partner_Account_Type__c){
                if(notUsedPartner.size()>0){
                    NS_Partner__c unusedPartner = notUsedPartner[0];
                    parentOpportunity.NS_Partner_Account_2__c=unusedPartner.NS_Partner_Account__c;
                    parentOpportunity.NS_Partner_Account_Type_2__c=unusedPartner.NS_Partner_Account_Type__c;
                    notUsedPartner.remove(0);
                }else{
                    parentOpportunity.NS_Partner_Account_2__c=null;
                    parentOpportunity.NS_Partner_Account_Type_2__c=null;
                }
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_3__c==recFinalPartner.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_3__c==recFinalPartner.NS_Partner_Account_Type__c){
                if(notUsedPartner.size()>0){
                    NS_Partner__c unusedPartner = notUsedPartner[0];
                    parentOpportunity.NS_Partner_Account_3__c=unusedPartner.NS_Partner_Account__c;
                    parentOpportunity.NS_Partner_Account_Type_3__c=unusedPartner.NS_Partner_Account_Type__c;
                    notUsedPartner.remove(0);
                }else{
                    parentOpportunity.NS_Partner_Account_3__c=null;
                    parentOpportunity.NS_Partner_Account_Type_3__c=null;
                }
                listToUpdate.add(parentOpportunity);
            }else if (parentOpportunity.NS_Partner_Account_4__c==recFinalPartner.NS_Partner_Account__c&& parentOpportunity.NS_Partner_Account_Type_4__c==recFinalPartner.NS_Partner_Account_Type__c){
                if(notUsedPartner.size()>0){
                    NS_Partner__c unusedPartner = notUsedPartner[0];
                    parentOpportunity.NS_Partner_Account_4__c=unusedPartner.NS_Partner_Account__c;
                    parentOpportunity.NS_Partner_Account_Type_4__c=unusedPartner.NS_Partner_Account_Type__c;
                    notUsedPartner.remove(0);
                }else{
                    parentOpportunity.NS_Partner_Account_4__c=null;
                    parentOpportunity.NS_Partner_Account_Type_4__c=null;
                }
                listToUpdate.add(parentOpportunity);
            }
            
        }
        if(listToUpdate.size()>0){
            mapUpdate.putAll(listToUpdate);
        }
        update mapUpdate.values();
        
    }
}