force-app/main/default/objects/NS_Partner__c/NS_Partner__c.object-meta.xml
<CustomObject>
    <description>Custom object to display Partner Related List in Opportunities Object.</description>
    <label>Partner</label>
    <nameField>
        <displayFormat>PTNR-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Partner__c/fields/NS_Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field gets populated from the selected Partner Account in the related opportunity.</description>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunities</relationshipLabel>
    <relationshipName>Partners3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Partner__c/fields/NS_Partner_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>NS_Partner_Account_Type__c</fullName>
    <description>This field gets populated from the selected Partner Account Type field in the related opportunity</description>
    <label>Partner Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*3PL</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Drayage</fullName>
            </value>
            <value>
                <fullName>ID Allies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payer</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Shipper &amp; Receiver</fullName>
            </value>
            <value>
                <fullName>TBT</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Partner__c/fields/NS_Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NS_Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This looks up to the related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partners</relationshipLabel>
    <relationshipName>NS_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>NS_Contract_Start_Date__c</fullName>
    <description>The date contract goes into effect</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_City__c</fullName>
    <description>the destination city will come from Workbench when possible</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_State__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_State__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Estimated_Volume__c.field-meta.xml
<CustomField>
    <fullName>NS_Estimated_Volume__c</fullName>
    <description>Volume (workbench in calcualtes volume in Carloads)</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Estimated Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_City__c</fullName>
    <description>The origin city will come from Workbench when possible. This field is required to move the Opportunity to the Internal Review Stage</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Commodity_Group__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Commodity_Group__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Commodity Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Need_by_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Need_by_Date__c</fullName>
    <inlineHelpText>The date marketing needs the final NPO Review decision. This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Need by Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Route__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Route__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Spot_Contract__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Spot_Contract__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Spot/Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Start_Date__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Projected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NS_PartnerTriggerHelperTest.cls
@isTest
public class NS_PartnerTriggerHelperTest {
 
    @testSetup
    private static void setup(){
        
        opportunity Oppo = new opportunity();
        Oppo.AccountId=AccountTestFactory.getThreePLAccountRecord('TestAcc').id;
        Oppo.Name='Tast Ops';
        
        Oppo.NS_Origin_Station__c='Test';	
        Oppo.StageName = 'Qualification/Analysis';                
        Oppo.CloseDate = System.Today();
        Oppo.NS_Estimated_Volume__c=50;
        Oppo.NS_Destination_Station__c='Test123';
        Oppo.NSSales_Commodity_Group__c='Test123';
        Oppo.Projected_Start_Date__c=System.Today();
        Oppo.NS_Contract_Start_Date__c=System.Today();
        Oppo.NS_Destination_State__c='Test';
        Oppo.Frequency__c='Weekly';
        Oppo.NSSales_Spot_Contract__c='Spot';
        Oppo.NSSales_Need_by_Date__c=System.Today();
        Oppo.NS_Origin_City__c='Kolkata';
        Oppo.NSSales_Route__c='Test';
        Oppo.NS_Destination_City__c='Kolkata';
        Oppo.NS_Originating_Department__c='Coal';
        Oppo.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('General Opportunity').getRecordTypeId();
        
        
        insert Oppo;
        
        Account Acc2X =AccountTestFactory.getThreePLAccountRecord('TestAcc2X');
        
        
        NS_Partner__c Ptnr2 = new NS_Partner__c();
        Ptnr2.NS_Related_Opportunity__c= Oppo.Id;
        Ptnr2.NS_Partner_Account_Type__c ='Beneficial Owner';
        Ptnr2.NS_Partner_Account__c =Acc2X.Id;
        insert Ptnr2; 
    }
    
    
    
    private static testmethod void testUpdate(){
        opportunity newOps =[Select id from Opportunity limit 01];
        test.startTest();
        Account Acc2X =[select id from account limit 01];
        id AccID2X = Acc2X.id;
        
        NS_Partner__c Ptnr1 = new NS_Partner__c();
        Ptnr1.NS_Related_Opportunity__c= newOps.Id;
        Ptnr1.NS_Partner_Account_Type__c ='*3PL';
        Ptnr1.NS_Partner_Account__c =AccID2X;
        insert Ptnr1;     
        
        NS_Partner__c Ptnr2 = new NS_Partner__c();
        Ptnr2.NS_Related_Opportunity__c= newOps.Id;
        Ptnr2.NS_Partner_Account_Type__c ='Beneficial Owner';
        Ptnr2.NS_Partner_Account__c =AccID2X;
        insert Ptnr2; 
        
        
        NS_Partner__c Ptnr3 = new NS_Partner__c();
        Ptnr3.NS_Related_Opportunity__c= newOps.Id;
        Ptnr3.NS_Partner_Account_Type__c ='Drayage';
        Ptnr3.NS_Partner_Account__c =AccID2X;
        insert Ptnr3;  
        
        NS_Partner__c Ptnr4 = new NS_Partner__c();
        Ptnr4.NS_Related_Opportunity__c= newOps.Id;
        Ptnr4.NS_Partner_Account_Type__c ='ID Allies';
        Ptnr4.NS_Partner_Account__c =AccID2X;
        insert Ptnr4; 
        
        
        NS_Partner__c Ptnr5 = new NS_Partner__c();
        Ptnr5.NS_Related_Opportunity__c= newOps.Id;
        Ptnr5.NS_Partner_Account_Type__c ='Other';
        Ptnr5.NS_Partner_Account__c =AccID2X;
        insert Ptnr5;
        
        NS_Partner__c Ptnr6 = new NS_Partner__c();
        Ptnr6.NS_Related_Opportunity__c= newOps.Id;
        Ptnr6.NS_Partner_Account_Type__c ='	Payer';
        Ptnr6.NS_Partner_Account__c =AccID2X;
        insert Ptnr6;
        
        NS_Partner__c Ptnr7 = new NS_Partner__c();
        Ptnr7.NS_Related_Opportunity__c= newOps.Id;
        Ptnr7.NS_Partner_Account_Type__c ='Port';
        Ptnr7.NS_Partner_Account__c =AccID2X;
        insert Ptnr7;
        
        NS_Partner__c Ptnr8 = new NS_Partner__c();
        Ptnr8.NS_Related_Opportunity__c= newOps.Id;
        Ptnr8.NS_Partner_Account_Type__c ='Receiver';
        Ptnr8.NS_Partner_Account__c =AccID2X;
        insert Ptnr8;
        
        
        
        
        delete Ptnr4;
        delete Ptnr3;
        delete Ptnr2;
        delete Ptnr1;
        delete Ptnr5;

        test.stopTest();
        
    }
    
    private static testmethod void testUpdate02(){
        
        opportunity newOps =[Select id from Opportunity limit 01];
        test.startTest();
        Account Acc2X =[select id from account limit 01];
        id AccID2X = Acc2X.id;
        
        NS_Partner__c Ptnr1 = new NS_Partner__c();
        Ptnr1.NS_Related_Opportunity__c= newOps.Id;
        Ptnr1.NS_Partner_Account_Type__c ='*3PL';
        Ptnr1.NS_Partner_Account__c =AccID2X;
        insert Ptnr1;     
        
        NS_Partner__c Ptnr2 = new NS_Partner__c();
        Ptnr2.NS_Related_Opportunity__c= newOps.Id;
        Ptnr2.NS_Partner_Account_Type__c ='Beneficial Owner';
        Ptnr2.NS_Partner_Account__c =AccID2X;
        insert Ptnr2; 
        
        
        NS_Partner__c Ptnr3 = new NS_Partner__c();
        Ptnr3.NS_Related_Opportunity__c= newOps.Id;
        Ptnr3.NS_Partner_Account_Type__c ='Drayage';
        Ptnr3.NS_Partner_Account__c =AccID2X;
        insert Ptnr3;  
        
        NS_Partner__c Ptnr4 = new NS_Partner__c();
        Ptnr4.NS_Related_Opportunity__c= newOps.Id;
        Ptnr4.NS_Partner_Account_Type__c ='ID Allies';
        Ptnr4.NS_Partner_Account__c =AccID2X;
        insert Ptnr4; 
        
        Ptnr1.NS_Partner_Account_Type__c = 'RR';
        update Ptnr1;   
        
        Ptnr2.NS_Partner_Account_Type__c = 'Shipper';
        update Ptnr2;
        
        Ptnr3.NS_Partner_Account_Type__c = 'Shipper & Receiver';
        update Ptnr3;      
        
        Ptnr4.NS_Partner_Account_Type__c = 'TBT';
        update Ptnr4;
        
        
        
        test.stopTest();        
        
    }
    
}