force-app/main/default/objects/Case/fields/NS_CustomerNotifiedDateTime__c.field-meta.xml
<CustomField>
    <fullName>NS_CustomerNotifiedDateTime__c</fullName>
    <description>This field captures the Date/Time of a customer notified</description>
    <label>Date Customer Notified</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NSSales_AllCaseRollups__c/NSSales_AllCaseRollups__c.object-meta.xml
<CustomObject>
    <description>This object will display all cases that are under a given account based on the hierarchy. Cases from all child accounts should roll up to its ultimate parent.</description>
    <label>All Case Rollups</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Case Rollup</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Case Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_AllCaseRollups__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Account for the case</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>All Case Rollups</relationshipLabel>
    <relationshipName>All_Case_Rollups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_AllCaseRollups__c/fields/NSSales_Case__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Case__c</fullName>
    <description>Case Related to a particular record</description>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>All Case Rollups</relationshipLabel>
    <relationshipName>All_Case_Rollups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NSSales_AllCaseRollups__c/fields/NSSales_UltimateParentAccount__c.field-meta.xml
<CustomField>
    <fullName>NSSales_UltimateParentAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ultimate Parent Account of the case</description>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>All Case Rollups (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>All_Case_Rollups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_AllCaseRollupsTriggerHelperTest.cls
@isTest(SeeAllData=false)
public class NSSales_AllCaseRollupsTriggerHelperTest {
    @isTest
    public static void updateCaseRollupRecordTest(){
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        System.runAs(admin){
            system.test.StartTest();
          
            Account ultimateParentAcc1 = AccountTestFactory.getOnlineAccountRecord('Ultimate Parent Account 1'); 
            Database.insert(ultimateParentAcc1,false);
            system.assertNotEquals(null, ultimateParentAcc1.id); 
            
            //sus

            
            Account testChildAcc1 = AccountTestFactory.getOnlineAccountRecord('Test Child Account 1');
            testChildAcc1.ParentId=ultimateParentAcc1.id;
            Database.insert(testChildAcc1,false);
            system.assertNotEquals(null, testChildAcc1.id); 
            system.assertEquals(ultimateParentAcc1.id, testChildAcc1.ParentId);   
            
            Account testChildAcc2= AccountTestFactory.getOnlineAccountRecord('Test Child Account 2');
            testChildAcc2.ParentId=testChildAcc1.Id;
            Database.insert(testChildAcc2,false);   
            Case case1 = CaseTestFactory.createCaseRecord('Embargo','Local Service',testChildAcc2.Id);
            case1.NS_CustomerNotifiedDateTime__c=system.now();

            insert case1;
            //system.debug('try test'+case1);
            system.assertNotEquals(null, case1.id);           
            
            NSSales_AllCaseRollups__c rollUpRec = new NSSales_AllCaseRollups__c(); 
            rollUpRec.NSSales_Case__c=case1.id;
            rollUpRec.NSSales_Account__c= null;
            insert rollUpRec;
            rollUpRec.NSSales_Account__c= testChildAcc2.Id;
            update rollUpRec;

            
            rollUpRec=[SELECT NSSales_Case__c, NSSales_Account__c,NSSales_UltimateParentAccount__c 
                    FROM NSSales_AllCaseRollups__c where NSSales_Case__c= :case1.id LIMIT 1];
            system.assertEquals(ultimateParentAcc1.Id,rollUpRec.NSSales_UltimateParentAccount__c);             
        }
        system.test.stopTest();
    }
}