force-app/main/default/objects/Case/fields/NS_CaseStatusCheck__c.field-meta.xml
<CustomField>
    <fullName>NS_CaseStatusCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NS_CaseStatusCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/NS_RACFUserID__c.field-meta.xml
<CustomField>
    <fullName>NS_RACFUserID__c</fullName>
    <label>RACF/User ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NS_StatusReason__c.field-meta.xml
<CustomField>
    <fullName>NS_StatusReason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Action Needed – Mechanical</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed – Customer</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed - IM Operations</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed – Mechanical</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed - Transportation</fullName>
            </value>
            <value>
                <fullName>Awaiting Response - Internal</fullName>
            </value>
            <value>
                <fullName>Case Created in Error</fullName>
            </value>
            <value>
                <fullName>Disposal Pending</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Fleet Quality</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Inspection Pending</fullName>
            </value>
            <value>
                <fullName>Internal Request</fullName>
            </value>
            <value>
                <fullName>No Action Required</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Transload Pending</fullName>
            </value>
            <value>
                <fullName>Analysis Required</fullName>
            </value>
            <value>
                <fullName>Phone Outreach Required</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Case Resolution in Progress</fullName>
            </value>
            <value>
                <fullName>Phone Outreach Completed</fullName>
            </value>
            <value>
                <fullName>Email Outreach Completed</fullName>
            </value>
            <value>
                <fullName>No Outreach Required</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed - Port/Foreign Rail</fullName>
            </value>
            <value>
                <fullName>Awaiting Response - IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NS_Type__c.field-meta.xml
<CustomField>
    <fullName>NS_Type__c</fullName>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_InteractionReason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Freight Bill</fullName>
            </value>
            <value>
                <fullName>Premium Payment</fullName>
            </value>
            <value>
                <fullName>Order not Used</fullName>
            </value>
            <value>
                <fullName>Adverse Loading</fullName>
            </value>
            <value>
                <fullName>Misc. Billing</fullName>
            </value>
            <value>
                <fullName>Demurrage/Storage</fullName>
            </value>
            <value>
                <fullName>Detention</fullName>
            </value>
            <value>
                <fullName>Stop in Route</fullName>
            </value>
            <value>
                <fullName>Empty Disposition</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Empty Railcar</fullName>
            </value>
            <value>
                <fullName>Loaded Railcar</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Locomotive</fullName>
            </value>
            <value>
                <fullName>Passenger Cars</fullName>
            </value>
            <value>
                <fullName>MPR</fullName>
            </value>
            <value>
                <fullName>Pool Adjustment</fullName>
            </value>
            <value>
                <fullName>Program Work</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>TTX</fullName>
            </value>
            <value>
                <fullName>Car Supply</fullName>
            </value>
            <value>
                <fullName>Commitment</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Line of Road Work</fullName>
            </value>
            <value>
                <fullName>Train Reporting Issue</fullName>
            </value>
            <value>
                <fullName>Work Planning</fullName>
            </value>
            <value>
                <fullName>Yard Inventory Update</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>AccessNS/TRAX - System Defect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NS_CaseUpdateforSystemDefect.cls
/**@author  Accenture
* @Created Date 2020-01-10
* @version  1.0
* @description This class is used by Case trigger to update Case owner, status and status reason for Interaction type:'AccessNS/TRAX – System Defect'
***************************************************************************
MODIFIED DATE       MODIFIED BY         DESCRIPTION
***************************************************************************

----------------------------------------------------------------------------
*/ 


public class NS_CaseUpdateforSystemDefect	 {
    
    /*Class Name*/ 
    private static final String CLASS_NAME='NS_CaseUpdateforSystemDefect';
    /*Method Name*/ 
    private static final String METHOD_NAME='caseUpdateforSystemDefect';
    public static void caseUpdateforSystemDefect(List<Case> newCases){
        
        
        try{
            string st='AccessNS/TRAX - System Defect';
            id groupDetail = [SELECT ID FROM Group where Type='Queue' And Name ='E - Commerce IT' limit 1].id;
            
            for(Case cc2 : newCases){
               
                system.debug('Sudipta UAT test'+cc2.NS_Type__c+''+cc2.NS_CaseStatusCheck__c);
                if(cc2.NS_Type__c==st && cc2.NS_CaseStatusCheck__c==false && cc2.NS_RACFUserID__c!=NULL )
                {
                    
                    if(cc2.OwnerId!=groupDetail && groupDetail!= null)
                    {
                        cc2.OwnerId=groupDetail;
                    }
                    cc2.status='NS_AwaitingResponse';
                    cc2.NS_CaseStatusCheck__c=true;

                    cc2.NS_StatusReason__c='Awaiting Response – IT';
                    
                }
            }
        }
        catch(Exception exp) {
            //inserting a record in Exception object
            NS_StaticVariablesUtility.createExceptionRecord(exp, CLASS_NAME,METHOD_NAME); 
        } 
        
    }
}