force-app/main/default/objects/Case/fields/NS_CaseStatusCheck__c.field-meta.xml
<CustomField>
    <fullName>NS_CaseStatusCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NS_CaseStatusCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/NS_InteractionCategory__c.field-meta.xml
<CustomField>
    <fullName>NS_InteractionCategory__c</fullName>
    <description>Basically its the case record type</description>
    <label>Interaction Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounting/Waybilling</fullName>
            </value>
            <value>
                <fullName>Concerned Citizen</fullName>
            </value>
            <value>
                <fullName>Foreign Road</fullName>
            </value>
            <value>
                <fullName>Local Service</fullName>
            </value>
            <value>
                <fullName>Marketing/Sales</fullName>
            </value>
            <value>
                <fullName>Tracing</fullName>
            </value>
            <value>
                <fullName>Transit Exceptions</fullName>
            </value>
            <value>
                <fullName>Business Functions</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Accounting/Billing</fullName>
                <isActive>false</isActive>
                <label>Accounting/Billing</label>
            </value>
            <value>
                <fullName>Billing/Accounting</fullName>
                <isActive>false</isActive>
                <label>Billing/Accounting</label>
            </value>
            <value>
                <fullName>Delayed Shipment</fullName>
                <isActive>false</isActive>
                <label>Delayed Shipment</label>
            </value>
            <value>
                <fullName>Email-to-case</fullName>
                <isActive>false</isActive>
                <label>Email-to-case</label>
            </value>
            <value>
                <fullName>Internal NS</fullName>
                <isActive>false</isActive>
                <label>Internal NS</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
                <isActive>false</isActive>
                <label>Outbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NS_InteractionReason__c.field-meta.xml
<CustomField>
    <fullName>NS_InteractionReason__c</fullName>
    <description>Reason for calling the customer care</description>
    <label>Interaction Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_InteractionCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3PL Tracing</fullName>
            </value>
            <value>
                <fullName>Cash Hold</fullName>
            </value>
            <value>
                <fullName>Classification Issues</fullName>
            </value>
            <value>
                <fullName>Concerned Citizen</fullName>
            </value>
            <value>
                <fullName>CSAO Communication</fullName>
            </value>
            <value>
                <fullName>Damage Prevention Holds</fullName>
            </value>
            <value>
                <fullName>Demurrage/Misc Bill/Freight Bill</fullName>
            </value>
            <value>
                <fullName>Diversion/Reship</fullName>
            </value>
            <value>
                <fullName>DQ/RIT Assistance</fullName>
            </value>
            <value>
                <fullName>EDI Request</fullName>
            </value>
            <value>
                <fullName>Embargo/OT5</fullName>
            </value>
            <value>
                <fullName>Expedite Request</fullName>
            </value>
            <value>
                <fullName>FRA/TSA Requests</fullName>
            </value>
            <value>
                <fullName>Freight Claims</fullName>
            </value>
            <value>
                <fullName>High &amp; Wide Movements</fullName>
            </value>
            <value>
                <fullName>Holiday Polling</fullName>
            </value>
            <value>
                <fullName>Interchange Concerns</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Inventory Accuracy</fullName>
            </value>
            <value>
                <fullName>Load Moving as Empty</fullName>
            </value>
            <value>
                <fullName>Local Service ETA</fullName>
            </value>
            <value>
                <fullName>Local Service Request</fullName>
            </value>
            <value>
                <fullName>LSS</fullName>
            </value>
            <value>
                <fullName>Misroute</fullName>
            </value>
            <value>
                <fullName>Missed Switch</fullName>
            </value>
            <value>
                <fullName>Pull/Place Errors</fullName>
            </value>
            <value>
                <fullName>Rate Request</fullName>
            </value>
            <value>
                <fullName>Rejects</fullName>
            </value>
            <value>
                <fullName>Request for 418</fullName>
            </value>
            <value>
                <fullName>RIT Not Qualified</fullName>
            </value>
            <value>
                <fullName>Technical Support</fullName>
            </value>
            <value>
                <fullName>Business Functions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NS_RACFUserID__c.field-meta.xml
<CustomField>
    <fullName>NS_RACFUserID__c</fullName>
    <label>RACF/User ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NS_Type__c.field-meta.xml
<CustomField>
    <fullName>NS_Type__c</fullName>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_InteractionReason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Freight Bill</fullName>
            </value>
            <value>
                <fullName>Premium Payment</fullName>
            </value>
            <value>
                <fullName>Order not Used</fullName>
            </value>
            <value>
                <fullName>Adverse Loading</fullName>
            </value>
            <value>
                <fullName>Misc. Billing</fullName>
            </value>
            <value>
                <fullName>Demurrage/Storage</fullName>
            </value>
            <value>
                <fullName>Detention</fullName>
            </value>
            <value>
                <fullName>Stop in Route</fullName>
            </value>
            <value>
                <fullName>Empty Disposition</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance</fullName>
            </value>
            <value>
                <fullName>Empty Railcar</fullName>
            </value>
            <value>
                <fullName>Loaded Railcar</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Locomotive</fullName>
            </value>
            <value>
                <fullName>Passenger Cars</fullName>
            </value>
            <value>
                <fullName>MPR</fullName>
            </value>
            <value>
                <fullName>Pool Adjustment</fullName>
            </value>
            <value>
                <fullName>Program Work</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Scrap</fullName>
            </value>
            <value>
                <fullName>TTX</fullName>
            </value>
            <value>
                <fullName>Car Supply</fullName>
            </value>
            <value>
                <fullName>Commitment</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Line of Road Work</fullName>
            </value>
            <value>
                <fullName>Train Reporting Issue</fullName>
            </value>
            <value>
                <fullName>Work Planning</fullName>
            </value>
            <value>
                <fullName>Yard Inventory Update</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>AccessNS/TRAX - System Defect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NS_CaseUpdateforSystemDefectTest.cls
/**@author  Accenture
* @Created Date 2019-12-23
* @version  1.0
* @description This is test class for NS_CaseUpdateforSystemDefect.
***************************************************************************
MODIFIED DATE       MODIFIED BY         DESCRIPTION
***************************************************************************

----------------------------------------------------------------------------
*/ 

@isTest(SeeAllData=false)
public class NS_CaseUpdateforSystemDefectTest {
    
    
     public static testmethod void positiveCasetest()
    {
     Account masterAccount= AccountTestFactory.createAccountRecord('BacthTest500');

        
         Case cs1 = new Case();
         cs1 = CaseTestFactory.createCaseRecord('Cash Hold','Accounting/Waybilling',masterAccount.Id);
        
   
         insert cs1; 
        system.debug('Sudipta:Case Status Check200'+cs1.Status+''+cs1.NS_Type__c+''+cs1.NS_CaseStatusCheck__c);
        cs1.NS_InteractionCategory__c='Business Functions';
        cs1.NS_InteractionReason__c='Technical Support';
        cs1.NS_Type__c='AccessNS/TRAX - System Defect';
        cs1.NS_RACFUserID__c='NS123';
        //cs1.NS_CaseStatusCheck__c=false;
        NS_StaticVariablesUtility.bSkipCaseTrigger =false;
        update cs1;   
  
         string cs3=([select status from case where id=:cs1.id].status);
         //system.debug('Sudipta:Case Status Check'+cs1.Status+''+cs1.NS_Type__c+''+cs3);
         system.assertEquals(cs3,'NS_AwaitingResponse');
        //system.assertNotEquals(cs1.id,null);

    }
    

}