force-app/main/default/objects/Case/fields/NS_InteractionCategory__c.field-meta.xml
<CustomField>
    <fullName>NS_InteractionCategory__c</fullName>
    <description>Basically its the case record type</description>
    <label>Interaction Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounting/Waybilling</fullName>
            </value>
            <value>
                <fullName>Concerned Citizen</fullName>
            </value>
            <value>
                <fullName>Foreign Road</fullName>
            </value>
            <value>
                <fullName>Local Service</fullName>
            </value>
            <value>
                <fullName>Marketing/Sales</fullName>
            </value>
            <value>
                <fullName>Tracing</fullName>
            </value>
            <value>
                <fullName>Transit Exceptions</fullName>
            </value>
            <value>
                <fullName>Business Functions</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Accounting/Billing</fullName>
                <isActive>false</isActive>
                <label>Accounting/Billing</label>
            </value>
            <value>
                <fullName>Billing/Accounting</fullName>
                <isActive>false</isActive>
                <label>Billing/Accounting</label>
            </value>
            <value>
                <fullName>Delayed Shipment</fullName>
                <isActive>false</isActive>
                <label>Delayed Shipment</label>
            </value>
            <value>
                <fullName>Email-to-case</fullName>
                <isActive>false</isActive>
                <label>Email-to-case</label>
            </value>
            <value>
                <fullName>Internal NS</fullName>
                <isActive>false</isActive>
                <label>Internal NS</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
                <isActive>false</isActive>
                <label>Outbound</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NS_InteractionReason__c.field-meta.xml
<CustomField>
    <fullName>NS_InteractionReason__c</fullName>
    <description>Reason for calling the customer care</description>
    <label>Interaction Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_InteractionCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3PL Tracing</fullName>
            </value>
            <value>
                <fullName>Cash Hold</fullName>
            </value>
            <value>
                <fullName>Classification Issues</fullName>
            </value>
            <value>
                <fullName>Concerned Citizen</fullName>
            </value>
            <value>
                <fullName>CSAO Communication</fullName>
            </value>
            <value>
                <fullName>Damage Prevention Holds</fullName>
            </value>
            <value>
                <fullName>Demurrage/Misc Bill/Freight Bill</fullName>
            </value>
            <value>
                <fullName>Diversion/Reship</fullName>
            </value>
            <value>
                <fullName>DQ/RIT Assistance</fullName>
            </value>
            <value>
                <fullName>EDI Request</fullName>
            </value>
            <value>
                <fullName>Embargo/OT5</fullName>
            </value>
            <value>
                <fullName>Expedite Request</fullName>
            </value>
            <value>
                <fullName>FRA/TSA Requests</fullName>
            </value>
            <value>
                <fullName>Freight Claims</fullName>
            </value>
            <value>
                <fullName>High &amp; Wide Movements</fullName>
            </value>
            <value>
                <fullName>Holiday Polling</fullName>
            </value>
            <value>
                <fullName>Interchange Concerns</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Inventory Accuracy</fullName>
            </value>
            <value>
                <fullName>Load Moving as Empty</fullName>
            </value>
            <value>
                <fullName>Local Service ETA</fullName>
            </value>
            <value>
                <fullName>Local Service Request</fullName>
            </value>
            <value>
                <fullName>LSS</fullName>
            </value>
            <value>
                <fullName>Misroute</fullName>
            </value>
            <value>
                <fullName>Missed Switch</fullName>
            </value>
            <value>
                <fullName>Pull/Place Errors</fullName>
            </value>
            <value>
                <fullName>Rate Request</fullName>
            </value>
            <value>
                <fullName>Rejects</fullName>
            </value>
            <value>
                <fullName>Request for 418</fullName>
            </value>
            <value>
                <fullName>RIT Not Qualified</fullName>
            </value>
            <value>
                <fullName>Setback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_CustomerAccnt__c.field-meta.xml
<CustomField>
    <fullName>NS_CustomerAccnt__c</fullName>
    <description>Account Name of Account in which another Account is calling on behalf of OR in which Online Account creation has been initiated but the Account has not yet been on-boarded to Salesforce</description>
    <inlineHelpText>Account Name for which Contact should be associated to when the Account becomes available in Salesforce.</inlineHelpText>
    <label>Customer Account</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/Survey_Result__c.object-meta.xml
<CustomObject>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Survey Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Result__c/fields/NS_ParentCaseNumber__c.field-meta.xml
<CustomField>
    <fullName>NS_ParentCaseNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Survey Results</relationshipLabel>
    <relationshipName>Survey_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/NS_resolve__c.field-meta.xml
<CustomField>
    <fullName>NS_resolve__c</fullName>
    <label>NS made it easy for me to resolve issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strongly Disagree</fullName>
            </value>
            <value>
                <fullName>Somewhat Disagree</fullName>
            </value>
            <value>
                <fullName>Neither Agree nor Disagree</fullName>
            </value>
            <value>
                <fullName>Somewhat Agree</fullName>
            </value>
            <value>
                <fullName>Strongly Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Result__c/fields/NS_resolveIssue__c.field-meta.xml
<CustomField>
    <fullName>NS_resolveIssue__c</fullName>
    <label>Please tell us why so we can follow-up</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NS_VOC_SurveyResultTriggerHelperTest.cls
@isTest
public class NS_VOC_SurveyResultTriggerHelperTest 
{
    @isTest static void testCreateSurvey() 
    {
        Account a=AccountTestFactory.createAccountRecord('Test Account');
        System.debug(' Check'+a.id);
        
        Contact c=ContactTestFactory.createContactRecord(a.Id,'Random');
        System.debug('test  '+c.NS_CustomerAccnt__c);
        System.debug('test1  '+c.id);
        
        Case cas=CaseTestFactory.createCase('Setback', 'Foreign Road', a.Id, c.Id);
        insert cas;
        System.debug('Test_Case' +cas.NS_InteractionReason__c);
        System.debug('Test_Case' +cas.NS_InteractionCategory__c);
        System.debug('Test_Case' +cas.AccountId);
        System.debug('Test_Case' +cas.id);
        
        
        Survey_Result__c svr = new Survey_Result__c();
        svr.NS_resolve__c='Strongly Disagree';
        svr.NS_ParentCaseNumber__c=cas.id;
        svr.NS_resolveIssue__c='Yes';
        insert svr;
        
        System.assert(svr.id!=null);
    }    
}