force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/NSSales_Marketing_Manager_Assignment__c.object-meta.xml
<CustomObject>
    <description>This custom objects allows ConnectNS users to associate Marketing Manager Assignments to an Account. An Account can contain multiple marketing manager assignments.</description>
    <label>Marketing Manager Assignment</label>
    <nameField>
        <displayFormat>MA-{0}</displayFormat>
        <label>Marketing Manager Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Account Name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Marketing Manager user name of the related record</description>
    <label>Marketing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/Primary_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Account Classification</label>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Expiration_Notification_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>NS_Expiration_Notification_Timeframe__c</fullName>
    <label>Expiration Notification Timeframe</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Implementation_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Implementation_Date__c</fullName>
    <label>Implementation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/NSSales_TimeDelta__c.field-meta.xml
<CustomField>
    <fullName>NSSales_TimeDelta__c</fullName>
    <label>Time Delta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NSSales_UserTriggerHelperTest.cls
@isTest(seeAllData=false)
public class NSSales_UserTriggerHelperTest {
    static testMethod void updateDateTime() {
        
        
        
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(37,sysprof.Id);
        User user1= UserTestFactory.createUser(76, UserTestFactory.createProfile('NS Marketing Manager').Id);
        
        admin.TimeZoneSidKey='America/New_York';
        admin.NSSales_TimeDelta__c=5;
        update admin;
        
        List<User> alist1=[Select id,TimeZoneSidKey from User where id=: admin.Id];
        System.debug('alist1'+alist1.size());
        system.assertNotEquals(null, admin.id);
        Test.startTest(); 
        
        Account ex= AccountTestFactory.createAccountRecord('test account');
        Opportunity opTest = new Opportunity();
        opTest.AccountId=ex.id;
        opTest.NS_Originating_Department__c='Automotive';
        opTest.NSSales_Implementation_Date__c=system.today();
        opTest.StageName='Closed: Implementation Pending';
        
        //opTest.NS_Expiration_Notification_Timeframe__c = 1;
        
        BU__c userPAC= new BU__c(Account__c=opTest.AccountId);
      
        NSSales_Marketing_Manager_Assignment__c nmm = 
            new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c = ex.Id ,
                                                        Primary_Account_Classification__c = userPAC.Id,
                                                        NSSales_MarketingManager__c = user1.id);
        
        
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        email.plainTextBody = 'teset';
        //email.toAddresses = 'test@test.com';
        
        
        NSSales_UserTriggerHelper abc=new NSSales_UserTriggerHelper();
        NSSales_UserTriggerHelper.sendEmail('teset','test@test.com','Test Lead');
        
        Test.stopTest();
        
        
    } 
    @isTest
    private  static void updatetimedelta(){
        
        Map<id,user> oldmap = new Map<id,user>();
        Map<id,user> newmap = new Map<id,user>();            
        
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        
        admin.TimeZoneSidKey='Asia/Kolkata';
        update admin;
        oldmap.put(admin.id , admin);
        Test.startTest(); 
        admin.TimeZoneSidKey='America/New_York';
        update admin;
        newmap.put(admin.id, admin);
        
        NSSales_UserTriggerHelper.updateTimeDeltaOnUpdate(newmap,oldmap);
        Test.stopTest();
        
        system.assertEquals('America/New_York',admin.TimeZoneSidKey);
        
    }
    @isTest
    private  static void updatemanopp(){
        Map<id,user> oldmap = new Map<id,user>();
        Map<id,user> newmap = new Map<id,user>();            
        
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User username = UserTestFactory.createAutoLeadUser(15,sysprof.Id);
          Id RoleId = [SELECT Id FROM UserRole WHERE DeveloperName = 'Automotive_Leadership'].Id;       
        
        admin.IsActive=true;
        //admin.UserRoleId=admin.id;
        admin.ManagerId=username.id;
        admin.UserRoleId=RoleId;
        update admin;
        
        oldmap.put(admin.id , admin);
        Test.startTest(); 
        admin.IsActive=false;
      // admin.UserRoleId=admin.id;
      	admin.ManagerId=username.id;
        admin.UserRoleId=RoleId;
        update admin;
        newmap.put(admin.id, admin);
        
        NSSales_UserTriggerHelper.updateoppmanager(newmap,oldmap);
        Test.stopTest();          
        system.assertEquals(false,admin.IsActive);       

}
}