force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/NSSales_Marketing_Manager_Assignment__c.object-meta.xml
<CustomObject>
    <description>This custom objects allows ConnectNS users to associate Marketing Manager Assignments to an Account. An Account can contain multiple marketing manager assignments.</description>
    <label>Marketing Manager Assignment</label>
    <nameField>
        <displayFormat>MA-{0}</displayFormat>
        <label>Marketing Manager Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Account Name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NSSales_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing Research &amp; Forecasting</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Marketing Manager user name of the related record</description>
    <label>Marketing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Field Sales Manager</fullName>
            </value>
            <value>
                <fullName>Group Manager</fullName>
            </value>
            <value>
                <fullName>Industrial Development Manager</fullName>
            </value>
            <value>
                <fullName>Market Manager</fullName>
            </value>
            <value>
                <fullName>National Account Manager</fullName>
            </value>
            <value>
                <fullName>Pricing Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Automotive Account Manager</fullName>
                <isActive>false</isActive>
                <label>Automotive Account Manager</label>
            </value>
            <value>
                <fullName>Industrial Products Account Manager</fullName>
                <isActive>false</isActive>
                <label>Industrial Products Account Manager</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/Primary_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Account Classification</label>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_MrktMngrAsgnmntTriggerHelperTest.cls
/************************************
Description  : Test class for NSSales_MrktMngrAsgnmntTriggerHelper class
Developer    : Soomjeet Sahoo
Date         : 21 Oct'19
**************************************/
@isTest(SeeAllData=false)
public class NSSales_MrktMngrAsgnmntTriggerHelperTest {
    public static testmethod void positiveMrktMngrTriggerHelperTestMain()
    {
        
        String testVariable='Test';
        
        //Starting Test
        Test.startTest();
        
        /*Test Account Created*/
        Account testAccount = AccountTestFactory.createAccountRecord(testVariable);
        
        /*NS Sales Manager profiles*/
        Profile user1Profile=UserTestFactory.createProfile('NS Sales Manager');
        Profile user2Profile=UserTestFactory.createProfile('NS Sales Manager');
        
        /*TestUser Accounts*/
        User user1= UserTestFactory.createUser(65, user1Profile.Id);
        User user2= UserTestFactory.createUser(53, user2Profile.Id);
        BU__c accPac= new BU__c();
        accPac.RecordTypeId=Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Automotive').getRecordTypeId();
        insert accPac;  
        BU__c accPac2= new BU__c();
        accPac2.RecordTypeId=Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Industrial Development').getRecordTypeId();
        insert accPac2; 
         BU__c accPac3= new BU__c();
        accPac3.RecordTypeId=Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Industrial Development').getRecordTypeId();
        insert accPac3;  

        
        
        //Record created for Marketing Manager Assignment
        NSSales_Marketing_Manager_Assignment__c nsMarketingRec= new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c=testAccount.id, 
                                                                                                            NSSales_MarketingManager__c=user1.id,
                                                                                                            Primary_Account_Classification__c=accPac2.id,
                                                                                                            NSSales_Role__c='Field Sales Manager',
                                                                                                            NSSales_BusinessUnit__c='Automotive');
        NSSales_Marketing_Manager_Assignment__c nsMarketingRec2= new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c=testAccount.id, 
                                                                                                             NSSales_MarketingManager__c=user1.id,
                                                                                                             Primary_Account_Classification__c=accPac3.id,
                                                                                                             NSSales_Role__c='Field Sales Manager',
                                                                                                             NSSales_BusinessUnit__c='Automotive');
        
        
        //insert comment
        database.SaveResult insNSMarketingRec= Database.insert(nsMarketingRec, true);
        database.SaveResult insNSMarketingRec2= Database.insert(nsMarketingRec2, true);
        System.assert(insNSMarketingRec.isSuccess());
        
        //update comment
        nsMarketingRec.NSSales_Role__c='Market Manager';
        nsMarketingRec.NSSales_MarketingManager__c=user2.Id;
        database.SaveResult updNSMarketingRec= Database.update(nsMarketingRec, true);
        System.assert(updNSMarketingRec.isSuccess());
        
        
        //delete comment
        database.DeleteResult delNSMarketingRec= Database.delete(nsMarketingRec, true);
        System.assert(delNSMarketingRec.isSuccess());
        
        //Stopping Test
        Test.stopTest(); 
        
    }
}