force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/NSSales_Opportunity_Lanes__c.object-meta.xml
<CustomObject>
    <label>Opportunity Lanes</label>
    <nameField>
        <displayFormat>OL-{0000}</displayFormat>
        <label>Oppty Lanes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Lanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Final_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Final_Rate__c</fullName>
    <label>Final Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Final_Rate_Update__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Final_Rate_Update__c</fullName>
    <description>This field is updated through workflow when final rate field is changed.</description>
    <label>Final Rate Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_LaneId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_LaneId__c</fullName>
    <externalId>true</externalId>
    <label>LaneId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lanes</relationshipLabel>
    <relationshipName>Opportunity_Lanes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Account Classification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>You cannot select an Account Classification record that does not belong to this Account.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities (Account Classification)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It relates a parent opportunity to an opportunity.</description>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_OppLaneClosedWonBatchTest.cls
@isTest(seeAllData=false)
public class NSSales_OppLaneClosedWonBatchTest {
    
    public static testmethod void OppClosedWon()
    {
         Test.startTest();
         String testVariable='Test';
         Account testAccount = AccountTestFactory.createAccountRecord(testVariable);
        BU__C testPAC = new BU__c();
        testPAC.RecordTypeId = Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Automotive').getRecordTypeId();
        testPAC.Account__c = testAccount.id;
        insert testPAC;
        Opportunity op = NSSales_OpportunityFactory.createOpportunityForHelper();  
        Opportunity op1 = NSSales_OpportunityFactory.createOpportunityForHelper(); 
        op1.NSSales_Parent_Opportunity__c =op.id;
        op1.NSSales_Account_Classification__c = testPAC.Id;
        update op1;
        NSSales_Opportunity_Lanes__c opl = new NSSales_Opportunity_Lanes__c();
        opl.NSSales_LaneId__c = '1000000004';
        opl.NSSales_Opportunity__c = op1.id;
        Datetime dt = DateTime.parse('09/25/2019 11:46 AM');
        opl.CreatedDate =dt;
        insert opl;
        opl.NSSales_Final_Rate__c ='Test';
        update opl;
        opl.NSSales_Final_Rate_Update__c = System.today()-14;
        update opl;
         Database.executeBatch(new NSSales_OppLaneClosedWonBatch());
        System.assert(opl.Id!=null);
        Test.stopTest();
    }
}