force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/NSSales_Marketing_Manager_Assignment__c.object-meta.xml
<CustomObject>
    <description>This custom objects allows ConnectNS users to associate Marketing Manager Assignments to an Account. An Account can contain multiple marketing manager assignments.</description>
    <label>Marketing Manager Assignment</label>
    <nameField>
        <displayFormat>MA-{0}</displayFormat>
        <label>Marketing Manager Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Account Name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Marketing Manager user name of the related record</description>
    <label>Marketing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/Primary_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Account Classification</label>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Expiration_Notification_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>NS_Expiration_Notification_Timeframe__c</fullName>
    <label>Expiration Notification Timeframe</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Implementation_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Implementation_Date__c</fullName>
    <label>Implementation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Rate_Renewal_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Rate_Renewal_Expiration_Date__c</fullName>
    <label>Rate Renewal Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Source_System__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Source_System__c</fullName>
    <label>Source System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_NotifyMMTest.cls
@isTest(SeeAllData=false)
public class NSSales_NotifyMMTest {
    public static testmethod void NSSales_NotifyMMTestPositiveTest()
    {
       
        Test.startTest();
        Account testAccount= AccountTestFactory.createAccountRecord('TestAcc');
        Profile user1Profile=UserTestFactory.createProfile('NS Marketing Manager'); 
        Profile user2Profile=UserTestFactory.createProfile('NS Marketing Manager');
        Profile user3Profile=UserTestFactory.createProfile('NS Marketing Manager');
        User user1= UserTestFactory.createUser(132, user1Profile.Id);
        user1.Email='crazymokey@gmail.com';
        User user2= UserTestFactory.createUser(393, user2Profile.Id);
        user2.Email='blackfox@gmail.com';
        User user3= UserTestFactory.createUser(582, user3Profile.Id);
        user3.Email='blackfox1@gmail.com';
        Opportunity opTest = new Opportunity();
        opTest.Name ='testOpty';
        opTest.CloseDate=(system.today()+3);
        opTest.AccountId=testAccount.id;
        opTest.NS_Originating_Department__c='Automotive';
        opTest.NSSales_Implementation_Date__c=(system.today());
        opTest.StageName='Qualification/Analysis';
        opTest.NSSales_Rate_Renewal_Expiration_Date__c = (system.today()+1);
        opTest.NS_Expiration_Notification_Timeframe__c = 1;
        opTest.Type='Renewal';
        opTest.NSSales_Source_System__c='NonIntermodal';
        insert opTest;
        BU__c userPAC= new BU__c(Account__c=opTest.AccountId);
        insert userPAC;
        NSSales_Marketing_Manager_Assignment__c nmm = 
            new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c = testAccount.Id ,
                                                        Primary_Account_Classification__c = userPAC.Id,
                                                        NSSales_MarketingManager__c = user1.id);
        
       
         NSSales_Marketing_Manager_Assignment__c nmm2 = 
            new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c = testAccount.Id ,
                                                        Primary_Account_Classification__c = userPAC.Id,
                                                        NSSales_MarketingManager__c = user2.id);
        
        NSSales_Marketing_Manager_Assignment__c nmm3 = 
            new NSSales_Marketing_Manager_Assignment__c(NSSales_Account__c = testAccount.Id ,
                                                        Primary_Account_Classification__c = userPAC.Id,
                                                        NSSales_MarketingManager__c = user3.id);
        insert nmm; 
        insert nmm2;
        insert nmm3;
        
        system.assertNotEquals(null,nmm.id); 
        DataBase.executeBatch(new NSSales_NotifyMM());
        Test.stopTest();
    }
    
}