force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/NSSales_Opportunity_Lanes__c.object-meta.xml
<CustomObject>
    <label>Opportunity Lanes</label>
    <nameField>
        <displayFormat>OL-{0000}</displayFormat>
        <label>Oppty Lanes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Lanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_LaneId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_LaneId__c</fullName>
    <externalId>true</externalId>
    <label>LaneId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lanes</relationshipLabel>
    <relationshipName>Opportunity_Lanes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Round_1_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Round_1_Rate__c</fullName>
    <label>Initial Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Round_1_Rate_Update__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Round_1_Rate_Update__c</fullName>
    <description>This field is updated through workflow when round-1 rate field is changed.</description>
    <label>Initial Rate Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It relates a parent opportunity to an opportunity.</description>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_OppLaneClosedLostBatchTest.cls
@isTest(SeeAllData=false)
public class NSSales_OppLaneClosedLostBatchTest {
   
    public static testmethod void testMethod1() {
        
        test.StartTest();
        opportunity opty = NSSales_OpportunityFactory.createOpportunityForHelper();
        Account testAccount = AccountTestFactory.createAccountRecord('Test');
        BU__C testPAC = new BU__c();
        testPAC.RecordTypeId = Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Automotive').getRecordTypeId();
        testPAC.Account__c = testAccount.id;
        insert testPAC;
        Opportunity op = NSSales_OpportunityFactory.createOpportunityForHelper(); 
        opty.NSSales_Parent_Opportunity__c =op.id;
       	update opty;
        
        NSSales_Opportunity_Lanes__c OLS = new NSSales_Opportunity_Lanes__c();
        OLS.NSSales_LaneId__c='a12364a';
        OLS.NSSales_Round_1_Rate__c = 'sddv';
        OLS.NSSales_Opportunity__c = opty.id;
        Datetime dates = DateTime.parse('05/30/2019 05:00 AM');
        OLS.CreatedDate =dates;
        OLS.NSSales_Round_1_Rate_Update__c = System.today() - 120;
        insert OLS;
        
        database.executeBatch(new NSSales_OppLaneClosedLostBatch());
        
        test.StopTest();
        
    }

}