force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Account_Type_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Account_Type_BU__c</fullName>
    <description>Sales - Classify the type of Account the customer is based on the NS Business group or user.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Beneficial Cargo Owner</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Drayage Provider</fullName>
            </value>
            <value>
                <fullName>Broker/3PL</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Economic Development Ally</fullName>
            </value>
            <value>
                <fullName>Engineering Consultant</fullName>
            </value>
            <value>
                <fullName>Railroad</fullName>
            </value>
            <value>
                <fullName>Site Selector</fullName>
            </value>
            <value>
                <fullName>State or Local EDC</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Shipper/Receiver</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
                <isActive>false</isActive>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Direct Customer</fullName>
                <isActive>false</isActive>
                <label>Direct Customer</label>
            </value>
            <value>
                <fullName>Indirect Customer</fullName>
                <isActive>false</isActive>
                <label>Indirect Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Business_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Business_Group_BU__c</fullName>
    <description>Sales - Business Group Breakdown sheet provided by NS. Dependant fields based on selected Unit, group(major/minor) and line of business</description>
    <label>Business Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
                <isActive>false</isActive>
                <label>Coal</label>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
                <isActive>false</isActive>
                <label>Industrial Development</label>
            </value>
            <value>
                <fullName>Industrial Prodcucts</fullName>
                <isActive>false</isActive>
                <label>Industrial Prodcucts</label>
            </value>
            <value>
                <fullName>Intermodal</fullName>
                <isActive>false</isActive>
                <label>Intermodal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Line_of_Business_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Line_of_Business_BU__c</fullName>
    <description>displayed alphabetically</description>
    <label>Line of Business_BU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_Minor_Group_BU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anthracite</fullName>
            </value>
            <value>
                <fullName>Coke</fullName>
            </value>
            <value>
                <fullName>Domestic Met</fullName>
            </value>
            <value>
                <fullName>Export Met</fullName>
            </value>
            <value>
                <fullName>Export Steam</fullName>
            </value>
            <value>
                <fullName>Hub</fullName>
            </value>
            <value>
                <fullName>Hunt</fullName>
            </value>
            <value>
                <fullName>IMC</fullName>
            </value>
            <value>
                <fullName>LTL</fullName>
            </value>
            <value>
                <fullName>Petcoke</fullName>
            </value>
            <value>
                <fullName>Truckload</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>Utility North</fullName>
            </value>
            <value>
                <fullName>Utility South</fullName>
            </value>
            <value>
                <fullName>Iron Ore</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Triple Crown</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Other Non/Met</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Anthracite (870)</fullName>
                <isActive>false</isActive>
                <label>Anthracite (870)</label>
            </value>
            <value>
                <fullName>Coke (850)</fullName>
                <isActive>false</isActive>
                <label>Coke (850)</label>
            </value>
            <value>
                <fullName>Domestic Met (830)</fullName>
                <isActive>false</isActive>
                <label>Domestic Met (830)</label>
            </value>
            <value>
                <fullName>Export Met (810)</fullName>
                <isActive>false</isActive>
                <label>Export Met (810)</label>
            </value>
            <value>
                <fullName>Export Steam (820)</fullName>
                <isActive>false</isActive>
                <label>Export Steam (820)</label>
            </value>
            <value>
                <fullName>Hub (714)</fullName>
                <isActive>false</isActive>
                <label>Hub (714)</label>
            </value>
            <value>
                <fullName>Hunt (715)</fullName>
                <isActive>false</isActive>
                <label>Hunt (715)</label>
            </value>
            <value>
                <fullName>ID Export Steam           </fullName>
                <isActive>false</isActive>
                <label>ID Export Steam           </label>
            </value>
            <value>
                <fullName>IMC (701)</fullName>
                <isActive>false</isActive>
                <label>IMC (701)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Major_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Major_Group_BU__c</fullName>
    <description>Sales - field dependent on Sub bus group</description>
    <label>Major Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Metals &amp; Construction</fullName>
            </value>
            <value>
                <fullName>Agriculture, Forest and Consumer Products</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
                <isActive>false</isActive>
                <label>Construction</label>
            </value>
            <value>
                <fullName>Forest and Consumer Products</fullName>
                <isActive>false</isActive>
                <label>Forest and Consumer Products</label>
            </value>
            <value>
                <fullName>Metals</fullName>
                <isActive>false</isActive>
                <label>Metals</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Minor_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Minor_Group_BU__c</fullName>
    <description>Sales - field dependent on major group</description>
    <label>Minor Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NS_Major_Group_BU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Triple Crown</fullName>
            </value>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Utility Coal</fullName>
            </value>
            <value>
                <fullName>Export Coal</fullName>
            </value>
            <value>
                <fullName>Domestic Met Coal</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Other Non/Met</fullName>
            </value>
            <value>
                <fullName>Agrifuels</fullName>
            </value>
            <value>
                <fullName>Corn &amp; Other Grains</fullName>
            </value>
            <value>
                <fullName>Feed &amp; Feed Prds</fullName>
            </value>
            <value>
                <fullName>Fertilizers</fullName>
            </value>
            <value>
                <fullName>Flour</fullName>
            </value>
            <value>
                <fullName>Food Oils</fullName>
            </value>
            <value>
                <fullName>Food Products</fullName>
            </value>
            <value>
                <fullName>Soybeans</fullName>
            </value>
            <value>
                <fullName>Sweeteners</fullName>
            </value>
            <value>
                <fullName>Wheat</fullName>
            </value>
            <value>
                <fullName>Beverages/Cons Prds</fullName>
            </value>
            <value>
                <fullName>Canned Goods</fullName>
            </value>
            <value>
                <fullName>Graphic Paper</fullName>
            </value>
            <value>
                <fullName>Lumber &amp; Wood</fullName>
            </value>
            <value>
                <fullName>Pulp</fullName>
            </value>
            <value>
                <fullName>Pulpboard</fullName>
            </value>
            <value>
                <fullName>Wood Chips</fullName>
            </value>
            <value>
                <fullName>Crude Oil</fullName>
            </value>
            <value>
                <fullName>Inorganic Chemicals</fullName>
            </value>
            <value>
                <fullName>NGLs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>NS_Record_Type_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Sub_Business_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Sub_Business_Group_BU__c</fullName>
    <description>Sales - Dependent field based on Business Group Selected</description>
    <label>Sub Business Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NSSales_Business_Group__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Business_Group__c</fullName>
    <label>Business Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Industrial Prodcucts</fullName>
                <label>Industrial Products</label>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NSSales_Group_Name1__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Group_Name1__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_DeletePACWithNoAccountBatchClass.cls
global class NSSales_DeletePACWithNoAccountBatchClass implements Database.Batchable<sObject>,Database.Stateful {
    
    global final String query;
    public List<String> accBatch = new list<String>();
    global Database.QueryLocator start(Database.BatchableContext bcx)
    {
        String query = 'select Id,Name,NSSales_Business_Group__c,NSSales_Group_Name1__c,NS_Account_Type_BU__c,NS_Business_Group_BU__c,NS_Line_of_Business_BU__c,NS_Major_Group_BU__c,NS_Minor_Group_BU__c,NS_Record_Type_Name__c,NS_Sub_Business_Group_BU__c,OwnerId from BU__c where Account__c = null';
        return Database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bcx, List<BU__c> batch)
    {	
	
		for(BU__c a: batch)
        {
            string recordString = a.Id+','+a.Name+','+a.NSSales_Business_Group__c+','+a.NSSales_Group_Name1__c+','+a.NS_Account_Type_BU__c+','+a.NS_Business_Group_BU__c+','+a.NS_Line_of_Business_BU__c+','+a.NS_Major_Group_BU__c+','+a.NS_Minor_Group_BU__c+','+a.NS_Record_Type_Name__c+','+a.NS_Sub_Business_Group_BU__c+','+a.OwnerId;
            accBatch.add(recordString);
        }
        database.delete(batch); //Deletion-Rule_UnCommented
    }
    
    global void finish (Database.BatchableContext bcx)
    {
        AsyncApexJob batchJobStatus = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, 
            CreatedBy.Email
            FROM AsyncApexJob WHERE Id = :bcx.getJobId()];
        
        string header = 'Id,Name,NSSales_Business_Group__c,NSSales_Group_Name1__c,NS_Account_Type_BU__c,NS_Business_Group_BU__c,NS_Line_of_Business_BU__c,NS_Major_Group_BU__c,NS_Minor_Group_BU__c,NS_Record_Type_Name__c,NS_Sub_Business_Group_BU__c,OwnerId\n';
        string finalstr = header ;
        for(String a: accBatch)
        {
            string recordString = a+'\n';
            finalstr = finalstr +recordString;
        }
		Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalstr);
        string csvname= 'Deleted_PAC_on_'+(system.now()).format('yyyyMMddhhmmss')+'.csv';      
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        
        if(finalstr.length() != header.length()){
        
        String emailList = label.NSSales_DeletedPAC_CSVRecList;
        List<String> emailAdd = emailList.split(',');
        String[] SendToAddresses = emailAdd;
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(SendToAddresses);
        String OrgName = URL.getSalesforceBaseUrl().toExternalForm().substringBetween('--','.');
        if(OrgName!=null){
            mail.setSubject('['+OrgName+']***Account Classification Deletion Batch Ran on ' +system.now()+ ' and status is ' + batchJobStatus.Status+ '***');
            
        }else{
            mail.setSubject('***Account Classification Deletion Batch Ran on ' +system.now()+ ' and status is ' + batchJobStatus.Status+ '***');
            
        }
        id owa = [select id, Address, DisplayName from OrgWideEmailAddress where DisplayName='No Reply' limit 01].id;
        mail.setOrgWideEmailAddressId(owa);
        string HTMLTextBody='<html> <body style="background-color: #d5f4e6;"> <font face = "Verdana" size = "2"> Hi, <br><br>This is to inform you that these Primary Account Classifications Were Deleted'
                +'<br><br><br><br>'
                + 'Thanks,<br>'
                + 'Connect NS Salesforce Support Team!'
                + '</font></body></html>';
        mail.setHtmlBody(HTMLTextBody); 
        mail.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
    }
    
}