force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Account_Type_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Account_Type_BU__c</fullName>
    <description>Sales - Classify the type of Account the customer is based on the NS Business group or user.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Beneficial Cargo Owner</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Drayage Provider</fullName>
            </value>
            <value>
                <fullName>Broker/3PL</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Economic Development Ally</fullName>
            </value>
            <value>
                <fullName>Engineering Consultant</fullName>
            </value>
            <value>
                <fullName>Railroad</fullName>
            </value>
            <value>
                <fullName>Site Selector</fullName>
            </value>
            <value>
                <fullName>State or Local EDC</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Shipper/Receiver</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
                <isActive>false</isActive>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Direct Customer</fullName>
                <isActive>false</isActive>
                <label>Direct Customer</label>
            </value>
            <value>
                <fullName>Indirect Customer</fullName>
                <isActive>false</isActive>
                <label>Indirect Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Business_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Business_Group_BU__c</fullName>
    <description>Sales - Business Group Breakdown sheet provided by NS. Dependant fields based on selected Unit, group(major/minor) and line of business</description>
    <label>Business Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
                <isActive>false</isActive>
                <label>Coal</label>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
                <isActive>false</isActive>
                <label>Industrial Development</label>
            </value>
            <value>
                <fullName>Industrial Prodcucts</fullName>
                <isActive>false</isActive>
                <label>Industrial Prodcucts</label>
            </value>
            <value>
                <fullName>Intermodal</fullName>
                <isActive>false</isActive>
                <label>Intermodal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Sub_Business_Group_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Sub_Business_Group_BU__c</fullName>
    <description>Sales - Dependent field based on Business Group Selected</description>
    <label>Sub Business Group_BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BU__c/fields/NSSales_Group_Name1__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Group_Name1__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/Record_Type_Duplication_Check__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Duplication_Check__c</fullName>
    <label>Record Type Duplication Check</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_DeletePACWithNoAccBatchClassTest.cls
@isTest(SeeAllData=false)
public class NSSales_DeletePACWithNoAccBatchClassTest {
    
    public static testmethod void NSSales_DeletePACWithNoAccBatchClassPositiveTest()
    {
         Test.startTest();
        BU__c b1= new BU__c();
        b1.NSSales_Group_Name1__c = 'Test';
        b1.Record_Type_Duplication_Check__c='Test';
        b1.NS_Account_Type_BU__c='Customer';
        b1.NS_Business_Group_BU__c='Merchandise';
        b1.NS_Sub_Business_Group_BU__c='Industrial Products';
        b1.Account__c=null;

        insert b1;
  
        Database.executeBatch(new NSSales_DeletePACWithNoAccountBatchClass());
        
        Test.stopTest();
    }
}