force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/NSSales_Group_Name1__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Group_Name1__c</fullName>
    <label>Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_lookupfieldControllerTest.cls
@isTest(SeeAllData=false)
public class NSSales_lookupfieldControllerTest {
	public static testmethod void positiveTest()
    {
		String objName = 'BU__c';
        List<String> returnFieldList = new List<String>{'Name','NSSales_Group_Name1__c'};
        Account Acc1 = AccountTestFactory.createAccountRecord(NS_StaticVariablesUtility.Name);
        String accountId =Acc1.id;
        BU__c objAccClass = new BU__c();
        objAccClass.Account__c = Acc1.Id;
        objAccClass.NSSales_Group_Name1__c ='test001';
        insert objAccClass;
        List<String> QueryFieldsList = new List<String>{'Name','NSSales_Group_Name1__c'};
		NSSales_lookupfieldController.getObjectDetails(objName);
        System.assertEquals('BU__c',objName);
		NSSales_lookupfieldController.findObjectIcon(objName); 
         System.assertEquals('BU__c',objName);
        NSSales_lookupfieldController.GetRecentRecords(objName,returnFieldList,10);
       	System.assert(returnFieldList != null);
       	NSSales_lookupfieldController.SearchRecords(accountId, objName, returnFieldList, QueryFieldsList, 'Acct', 'CreatedDate', 'DESC', 0);
        List<sobject> test1 = NSSales_lookupfieldController.SearchRecords(accountId, objName, returnFieldList, QueryFieldsList, 'Acct', 'CreatedDate', 'DESC', 0);
        System.debug(test1);
        System.assert(test1.size() > 0);
        NSSales_lookupfieldController.GetRecord(objName, returnFieldList, accountId, objAccClass.Name);
        System.assert(test1.size() > 0);
    }
}