force-app/main/default/objects/Market_Intelligence__c/Market_Intelligence__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture Marketing Intelligence for Executive &amp; Marketing ConnectNS users.</description>
    <label>Market Intel</label>
    <nameField>
        <label>Market Intel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Intel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intelligence__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to the Account Object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Marketing_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/NS_Market_Intel_Account__c.object-meta.xml
<CustomObject>
    <description>This is a junction object allowing multiple Market Intel records to be associated to multiple accounts</description>
    <label>Market Intel Associated Account</label>
    <nameField>
        <displayFormat>MIA-{0000}</displayFormat>
        <label>Market Intel Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Intel (Account)</relationshipLabel>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NSSales_MarketIntelTriggerHelper.cls
/**@author  Accenture
* @Created Date Oct,2019
* @version  1.0
* @description This class conatins methods which are invoked by NSSales_MarketIntelTrigger
*/ 

public class NSSales_MarketIntelTriggerHelper {
    
    private static final String CLASS_NAME = 'NSSales_MarketIntelTriggerHelper';
    private static final String METHOD_NAME1 = 'createNewMIAssocAccRec_DelPrevMIAccAssocRec';
   
    public static void createNewMIAssocAccRec_DelPrevMIAccAssocRec(Map<Id,Market_Intelligence__c> newMIMap, Map<Id,Market_Intelligence__c> oldMIMap){
        Set<Id> accIdSet = new Set<Id>();
        List<NS_Market_Intel_Account__c>  newMIAssocAccList= new List<NS_Market_Intel_Account__c>();
        List<NS_Market_Intel_Account__c>  miAssocAccListToBeDeleted= new List<NS_Market_Intel_Account__c>();
        
        for(Market_Intelligence__c miRec : oldMIMap.values()){
            if(miRec.Account__c != null){
                accIdSet.add(miRec.Account__c);
            }
        }
        Map<String,NS_Market_Intel_Account__c> accMIDetaisMap = new Map<String,NS_Market_Intel_Account__c>();
        for(NS_Market_Intel_Account__c miAssocAccRec : [SELECT name,NSSales_Account__c,NSSales_Market_Intel__c from NS_Market_Intel_Account__c where NSSales_Account__c IN :accIdSet]){
            accMIDetaisMap.put(miAssocAccRec.NSSales_Account__c+'-'+miAssocAccRec.NSSales_Market_Intel__c, miAssocAccRec);
        }
        
        for(Market_Intelligence__c changedMIRec : newMIMap.values()){
            if(oldMIMap.get(changedMIRec.id).Account__c != changedMIRec.Account__c && changedMIRec.Account__c != null){
                
                NS_Market_Intel_Account__c newMIAssocAccRec = new NS_Market_Intel_Account__c();
                newMIAssocAccRec.NSSales_Account__c = changedMIRec.Account__c;
                newMIAssocAccRec.NSSales_Market_Intel__c = changedMIRec.id;
                newMIAssocAccList.add(newMIAssocAccRec);
                
                if(oldMIMap.get(changedMIRec.id).Account__c!= null)
                {
                    NS_Market_Intel_Account__c assocMIAccRec = accMIDetaisMap.get(oldMIMap.get(changedMIRec.id).Account__c +'-'+changedMIRec.id);
                    miAssocAccListToBeDeleted.add(assocMIAccRec);
                }
            }
        }

        try{
            if(!newMIAssocAccList.isEmpty()){
                Database.insert(newMIAssocAccList,false);
            }
            
            if(!miAssocAccListToBeDeleted.isEmpty()){
                Database.Delete(miAssocAccListToBeDeleted,false);
            }
            
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME1);
        } 
        
    }
}