force-app/main/default/objects/Market_Intelligence__c/Market_Intelligence__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture Marketing Intelligence for Executive &amp; Marketing ConnectNS users.</description>
    <label>Market Intel</label>
    <nameField>
        <label>Market Intel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Intel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intelligence__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to the Account Object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Marketing_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <inlineHelpText>Multi-pick; Use Detail to refine Geography.</inlineHelpText>
    <label>Geography</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US-East</fullName>
            </value>
            <value>
                <fullName>US-West</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Asia Pac Rim</fullName>
            </value>
            <value>
                <fullName>So America</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Worldwide</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Norfolk Southern Terriroty</fullName>
                <isActive>false</isActive>
                <label>Norfolk Southern Terriroty</label>
            </value>
            <value>
                <fullName>North America</fullName>
                <isActive>false</isActive>
                <label>North America</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <inlineHelpText>Multi-pick; Use Carrier to refine Mode.</inlineHelpText>
    <label>Mode</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>IM</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>Ocean</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Water Inland</fullName>
                <isActive>false</isActive>
                <label>Water Inland</label>
            </value>
            <value>
                <fullName>Water Ocean</fullName>
                <isActive>false</isActive>
                <label>Water Ocean</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>If more than one, select Other; put details in the body of Intel section.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>NS Marketing Event</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business At Risk / Lost</fullName>
            </value>
            <value>
                <fullName>Business or Plant Closure / Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Competitor Capacity</fullName>
            </value>
            <value>
                <fullName>Competitor Customer Service</fullName>
            </value>
            <value>
                <fullName>Competitor Service Change</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Economic</fullName>
            </value>
            <value>
                <fullName>Equipment Capacity/Quality</fullName>
                <label>Equipment Capacity / Quality</label>
            </value>
            <value>
                <fullName>Market Conditions</fullName>
            </value>
            <value>
                <fullName>Mergers / Acquisitions</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>New or Cancelled Service</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Project Announcement</fullName>
            </value>
            <value>
                <fullName>Site Search</fullName>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Site Selection</fullName>
                <isActive>false</isActive>
                <label>Site Selection</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NSSales_MarketIntelTriggerHelperTest.cls
/************************************
Description  : Test class for NSSales_MrktMngrAsgnmntTriggerHelper class
Developer    : Accenture
Date         : 25 Nov'19
**************************************/
@isTest(SeeAllData=false)
public class NSSales_MarketIntelTriggerHelperTest {
    
    public static testmethod void createNewMIAssocAccRecTest(){
        
        system.test.StartTest();
        
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id); 
        
        system.runAs(admin){
            
            Account testAccount1 = AccountTestFactory.getOnlineAccountRecord('Test Account');
            Database.insert(testAccount1,false);
            system.assertNotEquals(null, testAccount1.id); 
            
            Market_Intelligence__c testMIRec = new Market_Intelligence__c();
            testMIRec.Name = 'test Market Intel';
            testMIRec.Type__c = 'Economic';
            testMIRec.Source__c ='Account';
            testMIRec.Account__c =testAccount1.id;
            testMIRec.Mode__c = 'Ocean';
            testMIRec.Geography__c = 'US-West';
            Database.insert(testMIRec,false);
            system.assertNotEquals(null, testMIRec.id); 
            
            Account testAccount2 = AccountTestFactory.getOnlineAccountRecord('Test Account1');
            Database.insert(testAccount2,false);
            system.assertNotEquals(null, testAccount2.id); 
            testMIRec.Account__c = testAccount2.id;
            Database.update(testMIRec,false);
            system.test.StopTest();
            
        }
        
    }
    
}