force-app/main/default/objects/Internal_Campaign_Members__c/Internal_Campaign_Members__c.object-meta.xml
<CustomObject>
    <label>Internal Campaign Members</label>
    <nameField>
        <displayFormat>ICM-{0000}</displayFormat>
        <label>Internal Campaign Members ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Internal Campaign Members</relationshipLabel>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Internal_User__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Internal_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Phone__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/logsControllerTest.cls
/**************************************************************************
Description  : Test Class for NSSales_opportunitySiteTriggerHelper class
Developer    : Accenture Solutions
Date         : 21-09-2019
****************************************************************************/
@isTest

public class logsControllerTest {
    
    static testMethod void logsControllerTestMethode()
    {
        
         Campaign newcamp = new Campaign();
          newcamp.Name='Test Campaign';
          newcamp.IsActive=True;
          newcamp.Type='Email';
          
          Insert newcamp;
          
        
        Internal_Campaign_Members__c internalcammem= new  Internal_Campaign_Members__c();
          internalcammem.NSSales_Campaign__c=newcamp.id;
          internalcammem.NSSales_Internal_User__c=userinfo.getUserId();
          internalcammem.NSSales_Phone__c='7845126';
          internalcammem.NSSales_Role__c='Teams';
          
          insert internalcammem;
        
        logsController.getLogs(internalcammem.id);
        
         Contact newCon= new Contact();
          newCon.FirstName='Test';
          newCon.LastName='Nscrop45';
          newCon.Email='Janpl@nscrop.com';
          newCon.Phone='4568092';
          newCon.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('General Contact').getRecordTypeId();
          insert newCon;
          
          
          CampaignMember camrcd= new CampaignMember();
          camrcd.CampaignId=newcamp.id;
          camrcd.ContactId=newCon.id;
          camrcd.Status='Sent';
          //insert camrcd;
          Database.SaveResult result=Database.insert(camrcd);
         system.assertEquals(True, result.isSuccess());
        
       logsController.getCampaignMemberLogs(camrcd.id);  
      
    }

}