force-app/main/default/objects/Internal_Campaign_Members__c/Internal_Campaign_Members__c.object-meta.xml
<CustomObject>
    <label>Internal Campaign Members</label>
    <nameField>
        <displayFormat>ICM-{0000}</displayFormat>
        <label>Internal Campaign Members ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Internal Campaign Members</relationshipLabel>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Internal_User__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Internal_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_IntCampMembersTriggerHelperTest.cls
/*
Description  : This class is a Test Class for Internal Campaign Members Trigger Helper.
Developer    : Accenture Solutions
Date         : 08-27-2019
*/
@isTest
public class NSSales_IntCampMembersTriggerHelperTest {
    
    /*Gunjari 08/27 -- test class for sendNotificationToMembersOnCreate*/
    @isTest
    public static void sendNotificationToMembersTest(){
        system.test.StartTest();
        //Creating one new user
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User testUser = UserTestFactory.createUser(14,sysprof.Id);
        system.assertNotEquals(null,testUser.id); 

        //creating one new campaign
        Campaign newCampaign = new Campaign();
        newCampaign.name = 'Test Campaign';
        insert newCampaign;
        system.assertNotEquals(null,newCampaign.id);
        
        //creating one Internal Campaign Member records
        Internal_Campaign_Members__c internalCampMember = new Internal_Campaign_Members__c();
        internalCampMember.NSSales_Campaign__c = newCampaign.id;
        internalCampMember.NSSales_Internal_User__c = testUser.id;
        internalCampMember.NSSales_Role__c ='test role';
        insert internalCampMember;
        system.assertNotEquals(null,internalCampMember.id); 
        system.assertEquals(newCampaign.id,internalCampMember.NSSales_Campaign__c); 
        system.test.stopTest();      
    }
}