force-app/main/default/objects/Internal_Campaign_Members__c/Internal_Campaign_Members__c.object-meta.xml
<CustomObject>
    <label>Internal Campaign Members</label>
    <nameField>
        <displayFormat>ICM-{0000}</displayFormat>
        <label>Internal Campaign Members ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSale_Non_Connect_NS_User_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>NSSale_Non_Connect_NS_User_Email_Address__c</fullName>
    <label>Non-Connect NS User Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSale_Non_Connect_NS_User_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSale_Non_Connect_NS_User_Phone_Number__c</fullName>
    <label>Non-Connect NS User Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Internal Campaign Members</relationshipLabel>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Internal_User__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Internal_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Non_Connect_NS_User__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Non_Connect_NS_User__c</fullName>
    <label>Non-Connect NS User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Non_Connect_NS_User_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Non_Connect_NS_User_Role__c</fullName>
    <label>Non-Connect NS User Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Campaign_Members__c/fields/NSSales_Phone__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NSSales_insertIntCmpMemberLogTest.cls
/**************************************************************************
Description  : Test Class for NSSales_opportunitySiteTriggerHelper class
Developer    : Accenture Solutions
Date         : 21-09-2019
****************************************************************************/
@isTest
public class NSSales_insertIntCmpMemberLogTest {
      static testMethod void createInternalMemberTestMethod()
      {
           Campaign newcamp = new Campaign();
          newcamp.Name='Test Campaign';
          newcamp.IsActive=True;
          newcamp.Type='Email';
          
          Insert newcamp;
          
          
          
          Internal_Campaign_Members__c internalcammem= new  Internal_Campaign_Members__c();
          internalcammem.NSSales_Campaign__c=newcamp.id;
          internalcammem.NSSales_Internal_User__c=userinfo.getUserId();
          internalcammem.NSSales_Phone__c='7845126';
          internalcammem.NSSales_Role__c='Teams';
          
          insert internalcammem;
          
          
          internalcammem.NSSales_Role__c='NS CROP';
          internalcammem.NSSales_Phone__c='7788556';
          update internalcammem;
          
          Delete internalcammem;
          
          
          Internal_Campaign_Members__c internalcammem02= new  Internal_Campaign_Members__c();
          internalcammem02.NSSales_Campaign__c=newcamp.id;
          internalcammem02.NSSales_Non_Connect_NS_User__c='Sudipta Mukherjee';
          internalcammem02.NSSale_Non_Connect_NS_User_Phone_Number__c='7845126';
          internalcammem02.NSSales_Non_Connect_NS_User_Role__c='Teams';
          internalcammem02.NSSale_Non_Connect_NS_User_Email_Address__c='abc@nscrop.com';
                    
        
          Database.SaveResult result = Database.insert(internalcammem02, false);
         
           system.assertEquals(True, result.isSuccess());
          
          
          internalcammem02.NSSales_Non_Connect_NS_User_Role__c='NS CROP';
          internalcammem02.NSSale_Non_Connect_NS_User_Phone_Number__c='7784556';
          internalcammem02.NSSale_Non_Connect_NS_User_Email_Address__c='sudipta@nscrop.com';
          update internalcammem02;
          
          
          delete internalcammem02;

     
          
      }
    
    
    
}