force-app/main/default/objects/NSSales_Opportunity_Lanes__c/NSSales_Opportunity_Lanes__c.object-meta.xml
<CustomObject>
    <label>Opportunity Lanes</label>
    <nameField>
        <displayFormat>OL-{0000}</displayFormat>
        <label>Oppty Lanes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Lanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/Dest_Location__c.field-meta.xml
<CustomField>
    <fullName>Dest_Location__c</fullName>
    <description>Destination city, Destination state</description>
    <formula>NSSales_DestinCity__c &amp;&quot;,&quot; &amp;  NSSales_DestinState__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Destination city, Destination state</inlineHelpText>
    <label>Destination</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/fmlSTCC__c.field-meta.xml
<CustomField>
    <fullName>fmlSTCC__c</fullName>
    <formula>IF(ISBLANK(NSSales_STCC__c),
IF(ISBLANK(STCC_Group__c), NULL,STCC_Group__c), 
NSSales_STCC__c)</formula>
    <label>STCC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NS_Sales_Origin_Group_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Sales_Origin_Group_City__c</fullName>
    <label>Origin Group City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Alk_Fuel_Miles__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Alk_Fuel_Miles__c</fullName>
    <label>Alk Fuel Miles</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Basis__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Basis__c</fullName>
    <description>Rate Basis</description>
    <label>Rate Basis</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Carloads_Moved__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Carloads_Moved__c</fullName>
    <label>Carloads Moved</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_CarOwnership__c.field-meta.xml
<CustomField>
    <fullName>NSSales_CarOwnership__c</fullName>
    <label>CarOwnership</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_CarType__c.field-meta.xml
<CustomField>
    <fullName>NSSales_CarType__c</fullName>
    <label>Car Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Committed_Volume__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Committed_Volume__c</fullName>
    <description>Committed volume, typically available after rate is published</description>
    <inlineHelpText>Committed volume</inlineHelpText>
    <label>Committed Volume</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_CompetitionType__c.field-meta.xml
<CustomField>
    <fullName>NSSales_CompetitionType__c</fullName>
    <label>Competition Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Destination_Group_City__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Destination_Group_City__c</fullName>
    <label>Destination Group City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Destination_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Destination_Group_Number__c</fullName>
    <label>Destination Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Destination_Group_Street__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Destination_Group_Street__c</fullName>
    <label>Destination Group State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_DestinCity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_DestinCity__c</fullName>
    <label>Destin City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_DestinHandlingLine__c.field-meta.xml
<CustomField>
    <fullName>NSSales_DestinHandlingLine__c</fullName>
    <label>Destin Handling Line</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_DestinRoad__c.field-meta.xml
<CustomField>
    <fullName>NSSales_DestinRoad__c</fullName>
    <label>Destination Road</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_DestinState__c.field-meta.xml
<CustomField>
    <fullName>NSSales_DestinState__c</fullName>
    <label>Destination State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_DestinStation__c.field-meta.xml
<CustomField>
    <fullName>NSSales_DestinStation__c</fullName>
    <label>DestinStation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Carloads__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Carloads__c</fullName>
    <label>EP Carloads</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Days_Online__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Days_Online__c</fullName>
    <label>EP Days Online</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Equip_Cost__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Equip_Cost__c</fullName>
    <label>EP Equip Cost</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Loaded_Miles__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Loaded_Miles__c</fullName>
    <label>EP Loaded Miles</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Tons__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Tons__c</fullName>
    <label>EP_Tons</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Total_Cost__c</fullName>
    <label>EP Total Cost</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EP_Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EP_Total_Revenue__c</fullName>
    <label>EP Total Revenue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EstRate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EstRate__c</fullName>
    <label>Estimated Rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_EstVolume__c.field-meta.xml
<CustomField>
    <fullName>NSSales_EstVolume__c</fullName>
    <description>Estimated volume.</description>
    <inlineHelpText>Estimated volume.</inlineHelpText>
    <label>Estimated Volume</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Expiring_NS_Factor__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Expiring_NS_Factor__c</fullName>
    <label>Expiring NS Factor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Expiring_rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Expiring_rate__c</fullName>
    <description>Expiring Thru Rate</description>
    <label>Expiring Thru Rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Final_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Final_Rate__c</fullName>
    <label>Final Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Lane_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Lane_Status__c</fullName>
    <label>Lane Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_LaneId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_LaneId__c</fullName>
    <externalId>true</externalId>
    <label>LaneId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_New_NS_Factor__c.field-meta.xml
<CustomField>
    <fullName>NSSales_New_NS_Factor__c</fullName>
    <label>New NS Factor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_New_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_New_Rate__c</fullName>
    <label>New Thru Rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OfferId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OfferId__c</fullName>
    <label>OfferId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Origin_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Origin_Group_Number__c</fullName>
    <label>Origin Group Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Origin_Group_Street__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Origin_Group_Street__c</fullName>
    <label>Origin Group State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OriginCity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OriginCity__c</fullName>
    <label>Origin City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OriginHandlingLine__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OriginHandlingLine__c</fullName>
    <label>Origin Handling Line</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OriginRoad__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OriginRoad__c</fullName>
    <description>Origin road</description>
    <inlineHelpText>Origin road</inlineHelpText>
    <label>Origin Road</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OriginState__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OriginState__c</fullName>
    <label>OriginState</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_OriginStation__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OriginStation__c</fullName>
    <label>OriginStation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Rate__c</fullName>
    <label>Rate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_RateSource__c.field-meta.xml
<CustomField>
    <fullName>NSSales_RateSource__c</fullName>
    <label>RateSource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Receiver__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Receiver__c</fullName>
    <label>Receiver</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Recommended_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Recommended_Rate__c</fullName>
    <label>Recommended Rate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Round_1_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Round_1_Rate__c</fullName>
    <label>Initial Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Route__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Route__c</fullName>
    <label>Route</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Shipper__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Shipper__c</fullName>
    <label>Shipper</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_STCC__c.field-meta.xml
<CustomField>
    <fullName>NSSales_STCC__c</fullName>
    <label>STCC Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>NSSales_Opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/Orig_Location__c.field-meta.xml
<CustomField>
    <fullName>Orig_Location__c</fullName>
    <description>Origin City, Origin State</description>
    <formula>IF(ISBLANK(NSSales_OriginCity__c),
IF(ISBLANK(NS_Sales_Origin_Group_City__c), NULL,(NS_Sales_Origin_Group_City__c &amp; &quot;,&quot; &amp; NSSales_Origin_Group_Street__c)), (NSSales_OriginCity__c &amp; &quot;,&quot; &amp; NSSales_OriginState__c))</formula>
    <inlineHelpText>Origin City, Origin State</inlineHelpText>
    <label>Origin</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/STCC_Group__c.field-meta.xml
<CustomField>
    <fullName>STCC_Group__c</fullName>
    <label>STCC Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_OpportunityLane.cls
public class NSSales_OpportunityLane {
    
    @AuraEnabled
    public static List <NSSales_Opportunity_Lanes__c> fetchOpportunityLane(Id opptyId) {
       
     List<NSSales_Opportunity_Lanes__c> laneList = 
         [SELECT Id,Name,NSSales_LaneId__c,Opportunity_Name__c,fmlSTCC__c,NSSales_STCC__c,STCC_Group__c,NSSales_OriginRoad__c,NSSales_OriginCity__c,NSSales_OriginState__c,NSSales_DestinRoad__c,NSSales_DestinCity__c,NSSales_DestinState__c,
                NSSales_Route__c,NSSales_Rate__c,NSSales_Recommended_Rate__c,NSSales_Round_1_Rate__c,NSSales_Final_Rate__c,NSSales_Lane_Status__c,
                NSSales_Shipper__c,NSSales_Receiver__c,NSSales_EstVolume__c,NSSales_Committed_Volume__c,Orig_Location__c,Dest_Location__c,
				NSSales_RateSource__c,NSSales_Expiring_rate__c,NSSales_Expiring_NS_Factor__c,
				NSSales_OfferId__c,NSSales_New_Rate__c,NSSales_New_NS_Factor__c,
				NSSales_CompetitionType__c,NSSales_CarType__c,NSSales_CarOwnership__c,NSSales_Carloads_Moved__c,
				NSSales_Origin_Group_Number__c,NS_Sales_Origin_Group_City__c,NSSales_Origin_Group_Street__c,NSSales_OriginStation__c,NSSales_OriginHandlingLine__c,
				NSSales_Destination_Group_Number__c,NSSales_Destination_Group_City__c,NSSales_Destination_Group_Street__c,NSSales_DestinStation__c,NSSales_DestinHandlingLine__c,
				NSSales_Alk_Fuel_Miles__c,NSSales_Basis__c,
                NSSales_EP_Carloads__c,NSSales_EP_Days_Online__c,NSSales_EP_Equip_Cost__c,NSSales_EP_Loaded_Miles__c,NSSales_EP_Total_Cost__c,
                NSSales_EP_Total_Revenue__c,NSSales_EP_Tons__c,NSSales_EstRate__c,NSSales_EstVolumePeriod__c,NSSales_EstVolumeUnits__c,
                NSSales_Lading__c,NSSales_MinCars__c,NSSales_MinCarsPeriod__c,
                NSSales_MinWeight__c,NSSales_MinWeightUnits__c,NSSales_OffRamp__c,NSSales_OnRamp__c,
                NSSales_STCCMajorGroup__c,NSSales_STCCMinorGroup__c,
				NSSales_Th_Carloads__c,NSSales_TH_Tons__c,NSSales_TH_NS_Revenue__c,NSSales_TH_Total_Revenue__c from NSSales_Opportunity_Lanes__c where NSSales_Opportunity__c=: opptyId];
       
        system.debug('laneList'+laneList);
        return laneList;
    }

}