force-app/main/default/objects/NSSales_Opportunity_Lanes__c/NSSales_Opportunity_Lanes__c.object-meta.xml
<CustomObject>
    <label>Opportunity Lanes</label>
    <nameField>
        <displayFormat>OL-{0000}</displayFormat>
        <label>Oppty Lanes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Lanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Final_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Final_Rate__c</fullName>
    <label>Final Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lanes</relationshipLabel>
    <relationshipName>Opportunity_Lanes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Round_1_Rate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Round_1_Rate__c</fullName>
    <label>Initial Offer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Round_1_Rate_Update__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Round_1_Rate_Update__c</fullName>
    <description>This field is updated through workflow when round-1 rate field is changed.</description>
    <label>Initial Rate Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Expiration_Notification_Timeframe__c.field-meta.xml
<CustomField>
    <fullName>NS_Expiration_Notification_Timeframe__c</fullName>
    <label>Expiration Notification Timeframe</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Lost_Cancelled_Description__c.field-meta.xml
<CustomField>
    <fullName>NS_Lost_Cancelled_Description__c</fullName>
    <description>Additional description for lost or cancelled opportunity reasons.</description>
    <inlineHelpText>Enter additional description if necessary.</inlineHelpText>
    <label>Lost/Cancelled Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Lost_Cancelled_Reason__c.field-meta.xml
<CustomField>
    <fullName>NS_Lost_Cancelled_Reason__c</fullName>
    <description>Reason the opportunity was lost or cancelled</description>
    <inlineHelpText>Select reason for loss of Opportunity</inlineHelpText>
    <label>Lost/Cancelled Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Product</fullName>
            </value>
            <value>
                <fullName>Alternative Source</fullName>
            </value>
            <value>
                <fullName>Bid Award</fullName>
            </value>
            <value>
                <fullName>Billing Type</fullName>
            </value>
            <value>
                <fullName>Business or Plant Closure/Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Competitor Capacity (i.e. Truck Capacity)</fullName>
            </value>
            <value>
                <fullName>Competitor Customer Service</fullName>
            </value>
            <value>
                <fullName>Competitor Service Change (New or Cancelled Service)</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Extreme Weather Event</fullName>
            </value>
            <value>
                <fullName>Location Inaccessible</fullName>
            </value>
            <value>
                <fullName>Market Conditions</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>NPO</fullName>
            </value>
            <value>
                <fullName>NS Customer Service</fullName>
            </value>
            <value>
                <fullName>NS Equipment Capacity/Quality</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Plant Closure</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Terms and Conditions</fullName>
            </value>
            <value>
                <fullName>Weather - Seasonality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Lost_To__c.field-meta.xml
<CustomField>
    <fullName>NS_Lost_To__c</fullName>
    <description>Where the opportunity was lost to</description>
    <label>Lost To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>CSX</fullName>
            </value>
            <value>
                <fullName>Internal NS Channel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Railroad</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It relates a parent opportunity to an opportunity.</description>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Rate_Renewal_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Rate_Renewal_Expiration_Date__c</fullName>
    <label>Rate Renewal Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NSSales_OppLaneClosedLostBatch.cls
global class NSSales_OppLaneClosedLostBatch implements Database.Batchable<sObject>,Database.Stateful {
    
    List<String> csvList = new List<String>();
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String query = 'SELECT id, NSSales_Round_1_Rate__c, NSSales_Round_1_Rate_Update__c, NSSales_Final_Rate__c,NSSales_Opportunity__c,NSSales_Opportunity__r.StageName,NSSales_Opportunity__r.Name,NSSales_Opportunity__r.CreatedDate from NSSales_Opportunity_Lanes__c where NSSales_Opportunity__r.NSSales_Parent_Opportunity__c != null and NSSales_Round_1_Rate_Update__c =  N_DAYS_AGO:120 ';
        System.debug(Database.getQueryLocator(query));
        return Database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bc, List<NSSales_Opportunity_Lanes__c> batch)
    {  
        List<NSSales_Opportunity_Lanes__c> updateOpp = new List<NSSales_Opportunity_Lanes__c>();
        List<Opportunity> opp = new List<Opportunity>();
       
        for(NSSales_Opportunity_Lanes__c op : batch)
        {
            if(op.NSSales_Final_Rate__c == null)
            {
            	Opportunity temp = op.NSSales_Opportunity__r;
            	opp.add(temp);
            }    
        }
        for(Opportunity obj : opp)
        {
            obj.StageName='Closed Lost';
            obj.NS_Lost_To__c='Other';
            obj.NS_Lost_Cancelled_Reason__c='Other';
            obj.NS_Lost_Cancelled_Description__c='Closed Lost';
            obj.NSSales_Rate_Renewal_Expiration_Date__c =System.today() + 2;
            obj.NS_Expiration_Notification_Timeframe__c=1.0;
            csvList.add(obj.id+','+obj.Name+','+obj.StageName+','+obj.CreatedDate);
            
        }
        System.debug(opp);
        Database.update(opp);
        
    }
    
    global void finish (Database.BatchableContext bc)
    {
        System.debug('email');
        AsyncApexJob batchJobStatus = [
            SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, 
            CreatedBy.Email
            FROM AsyncApexJob WHERE Id = :bc.getJobId()];
        string header = 'Id,Name,StageName,CreatedDate\n';
        string finalstr = header ;
        for(String a: csvList)
        {
            string recordString = a+'\n';
            finalstr = finalstr +recordString;
        }
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalstr);
        string csvname= 'OppStageChangeToClosedLost'+(system.now()).format('yyyyMMddhhmmss')+'.csv';      
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        if(finalstr.length() != header.length()){
            String emailList = label.NSSales_oppStageChange;
            List<String> emailAdd = emailList.split(',');
            String[] SendToAddresses = emailAdd;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(SendToAddresses);
            String OrgName = URL.getSalesforceBaseUrl().toExternalForm().substringBetween('--','.');
            if(OrgName!=null){
                mail.setSubject('['+OrgName+']***Opportunity Stage Change to Closed Lost ' +system.now()+ ' and status is ' + batchJobStatus.Status+ '***');
                
            }else{
                mail.setSubject('***Opportunity Stage Change to Closed Lost ' +system.now()+ ' and status is ' + batchJobStatus.Status+ '***');
                
            }
            
            id owa = [select id, Address, DisplayName from OrgWideEmailAddress where DisplayName='No Reply' limit 01].id;
            string HTMLTextBody='<html> <body style="background-color: #d5f4e6;"> <font face = "Verdana" size = "2"> Hi, <br><br>This is to inform you that these Opportunities Stages has been Changed to Closed Lost'
                +'<br><br><br><br>'
                + 'Thanks,<br>'
                + 'Connect NS Salesforce Support Team!'
                + '</font></body></html>';
            mail.setHtmlBody(HTMLTextBody);
            mail.setOrgWideEmailAddressId(owa);
            mail.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

}