force-app/main/default/objects/NSSales_Opportunity_Lanes__c/NSSales_Opportunity_Lanes__c.object-meta.xml
<CustomObject>
    <label>Opportunity Lanes</label>
    <nameField>
        <displayFormat>OL-{0000}</displayFormat>
        <label>Oppty Lanes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Lanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_LaneId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_LaneId__c</fullName>
    <externalId>true</externalId>
    <label>LaneId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_Opportunity_Lanes__c/fields/NSSales_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lanes</relationshipLabel>
    <relationshipName>Opportunity_Lanes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It relates a parent opportunity to an opportunity.</description>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Nssales_OppLaneCancelledBatchTest.cls
@isTest(seeAllData=false)
public class Nssales_OppLaneCancelledBatchTest {
    public static testmethod void OppCanceled()
    {
         Test.startTest();
        Opportunity op = NSSales_OpportunityFactory.createOpportunityForHelper();  
        Opportunity op1 = NSSales_OpportunityFactory.createOpportunityForHelper(); 
        op1.NSSales_Parent_Opportunity__c =op.id;
        update op1;
        NSSales_Opportunity_Lanes__c opl = new NSSales_Opportunity_Lanes__c();
        opl.NSSales_LaneId__c = '1000000004';
        opl.NSSales_Opportunity__c = op1.id;
        Datetime dt = DateTime.parse('09/25/2019 11:46 AM');
        opl.CreatedDate =dt;
        insert opl;
         Database.executeBatch(new Nssales_OppLaneCancelledBatch());
        System.assert(opl.Id!=null);
        Test.stopTest();

    }
}