force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/NSSales_609_1_All_Switch_Coordinates__c.object-meta.xml
<CustomObject>
    <label>All Switch Coordinate</label>
    <nameField>
        <displayFormat>SWC-{00000}</displayFormat>
        <label>AllSwitchCo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Switch Coordinates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Latitude__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Latitude__c</fullName>
    <label>Latitude</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Longitude__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Longitude__c</fullName>
    <label>Longitude</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Switch_Identification_Numbers__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Switch_Identification_Numbers__c</fullName>
    <label>Switch Identification Numbers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/NSSales_609_1_Manager_Routing__c.object-meta.xml
<CustomObject>
    <label>609.1 Manager Routing</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>609.1 Manager Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1 Managers Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_City_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_County_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_County_Name__c</fullName>
    <label>County Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_ID_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ID_Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industrial Development Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X609_1_Managers_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_State_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/NSSales_609_1FSSalesManager__c.object-meta.xml
<CustomObject>
    <label>609.1 FS Manager Routing</label>
    <nameField>
        <displayFormat>FSMR-{0000}</displayFormat>
        <label>NSSales_609.1FSSalesManager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1FSSalesManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/NSSales_NPO_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing approvers for NPO Approval Process.</description>
    <label>NPO Approval</label>
    <nameField>
        <displayFormat>NPO-{00000}</displayFormat>
        <label>NPO Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPO Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Approval_Type__c</fullName>
    <description>Approval Type for the related opportunity</description>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPS Planning North</fullName>
            </value>
            <value>
                <fullName>OPS Planning Central</fullName>
            </value>
            <value>
                <fullName>OPS Planning South</fullName>
            </value>
            <value>
                <fullName>OPS Planning West</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Network Capacity</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Commercial Planning</fullName>
            </value>
            <value>
                <fullName>Interline Services</fullName>
            </value>
            <value>
                <fullName>Auto/Intermodal</fullName>
            </value>
            <value>
                <fullName>Industrial Products/Unit</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>OPS Planning NOC</fullName>
            </value>
            <value>
                <fullName>OPS Planning East</fullName>
                <isActive>false</isActive>
                <label>OPS Planning East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>NPO Approvals</relationshipLabel>
    <relationshipName>NPO_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Status__c</fullName>
    <description>It captures the approval status i.e, approved or rejected</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval_Comments__c/NSSales_NPO_Approval_Comments__c.object-meta.xml
<CustomObject>
    <label>NPO Approval Comment</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPO Approval Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_NPO_Approval_Comments__c/fields/NSSales_Comments__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval_Comments__c/fields/NSSales_ProcessInstanceID__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ProcessInstanceID__c</fullName>
    <label>ProcessInstanceID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval_Comments__c/fields/NSSales_ProcessInstanceStepID__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ProcessInstanceStepID__c</fullName>
    <label>ProcessInstanceStepID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval_Comments__c/fields/NSSales_ProcessInstanceWorkItemId__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ProcessInstanceWorkItemId__c</fullName>
    <label>ProcessInstanceWorkItemId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_SalesNPO_Approvers__c.field-meta.xml
<CustomField>
    <fullName>NS_SalesNPO_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales609_1_InitaitedDate__c.field-meta.xml
<CustomField>
    <fullName>NSSales609_1_InitaitedDate__c</fullName>
    <label>Initiated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_SwitchIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_SwitchIdentificationNumber__c</fullName>
    <description>Required to be entered when 609.1 Opportunity is submitted for approval.</description>
    <label>Switch Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_SwitchRemovalRequest__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_SwitchRemovalRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of Req#3332</description>
    <label>609.1 Switch Removal Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Network_Capacity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Network_Capacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Network Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Territory_Name__c</fullName>
    <label>Territory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Harrisburg East</fullName>
            </value>
            <value>
                <fullName>Harrisburg West</fullName>
            </value>
            <value>
                <fullName>Indianapolis</fullName>
            </value>
            <value>
                <fullName>Knoxville</fullName>
            </value>
            <value>
                <fullName>Norfolk</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Ohio</fullName>
            </value>
            <value>
                <fullName>Roanoke</fullName>
            </value>
            <value>
                <fullName>South Carolina</fullName>
            </value>
            <value>
                <fullName>St. Louis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NS_General_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NS_General_Opportunity</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>General Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/NSSales_609_1.recordType-meta.xml
<RecordType>
    <fullName>NSSales_609_1</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>609.1</label>
</RecordType>

force-app/main/default/classes/NSSales_NPOCommentControllerTest.cls
@isTest (SeeAllData=false)
public class NSSales_NPOCommentControllerTest {
    
   
    @isTest
    public static void npo_Opty_Comment_Test(){
        
        system.test.StartTest();
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User atest;    
        
        //Creating Sales manager test User  
        System.runAs( admin ){ 
            Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            atest = UserTestFactory.createUserSales(22,agent.Id);
            
            Account acc = new Account(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                                SobjectType ='Account' Limit 1].id,
                Name='AccountForOppotunity');
            insert acc;
            system.assertNotEquals(null,acc.id); 
            Opportunity opty = new Opportunity();
            opty.Name = 'Test';
            opty.AccountId = acc.Id;
            opty.NS_Originating_Department__c = 'Automotive';
            opty.StageName = 'Qualification/Analysis';                
            opty.CloseDate = System.Today();
            opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NS_General_Opportunity').getRecordTypeId();
            opty.NSSales_609_1_SwitchRemovalRequest__c = true;
            insert opty; 
            opty.NS_SalesNPO_Approvers__c=atest.id;
            opty.NSSales_Network_Capacity__c=true;
            update opty;    
            List<NSSales_NPO_Approval__c> npoApprovalRec= [select id,NSSales_Approval_Type__c,NSSales_Status__c from NSSales_NPO_Approval__c where NSSales_Related_Opportunity__c =: opty.Id];
            NSSales_NPOCommentController.getVisibility(npoApprovalRec[0].Id);//npoObjReq
            List<ProcessInstanceWorkitem> pI = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :npoApprovalRec[0].Id];
            NSSales_NPOCommentController.getVisibility(pI[0].Id);
            String npoObjReq = NSSales_NPOCommentController.findObjectNameFromRecordId(npoApprovalRec[0].Id);//passed with one exception
            System.debug('npoObjReq'+npoObjReq);
            String piObjId = NSSales_NPOCommentController.fetchObjectId(pI[0].Id);
            System.debug('piObjId'+piObjId);
            NSSales_NPO_Approval_Comments__c approvalComment=new NSSales_NPO_Approval_Comments__c();
            approvalComment.NSSales_Comments__c='approved';
            approvalComment.NSSales_ProcessInstanceWorkItemId__c = pI[0].Id;
            approvalComment.NSSales_ProcessInstanceID__c=(pI[0].ProcessInstanceId);
            insert approvalComment;
            List<NSSales_NPO_Approval_Comments__c> piDetails21 =NSSales_NPOCommentController.fetchCommentsProcessItemDetailsNpo(pI[0].Id);
            System.assertNotEquals(null, approvalComment.id);
            List<ProcessInstanceStep>  ProcessInstanceStepList = [SELECT id,ProcessInstanceId FROM ProcessInstanceStep where ProcessInstanceId = :pI[0].ProcessInstanceId];    
           NSSales_NPOCommentController.getVisibility(ProcessInstanceStepList[0].Id);//npoObjReq
            String  fetchObjectIdfromProcess =NSSales_NPOCommentController.fetchObjectIdfromProcessInstance(ProcessInstanceStepList[0].ID);
            NSSales_NPO_Approval_Comments__c approvalComment1=new NSSales_NPO_Approval_Comments__c();
            approvalComment1.NSSales_Comments__c='approved';
            approvalComment1.NSSales_ProcessInstanceStepID__c=(ProcessInstanceStepList[0].id);
            insert approvalComment1;
            List<NSSales_NPO_Approval_Comments__c> piDetails30= NSSales_NPOCommentController.fetchCommentProcessInstanceStepNpo(ProcessInstanceStepList[0].ID);
            System.assertNotEquals(null, approvalComment1.id);
            system.test.StopTest();
        }
    } 
    
    @isTest
    public static void opty_609_1_Comment_Test(){
        system.test.StartTest();
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User idManager;
        User fsManager; 
        
        //Creating Sales manager test User  
        System.runAs( admin ){ 
            Profile agent1 = UserTestFactory.createProfile(NS_StaticVariablesUtility.NSSalesIDProfile);
            idManager = UserTestFactory.createUserSales(22,agent1.Id);
            Profile agent2 = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            fsManager = UserTestFactory.createUserSales(24,agent2.Id);
            Account acc = new Account(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                                SobjectType ='Account' Limit 1].id,
                Name='AccountForOppotunity');
            insert acc;
            system.assertNotEquals(null,acc.id); 
            Opportunity opty = new Opportunity();
            opty.Name = 'Test';
            opty.AccountId = acc.Id;
            opty.NS_Originating_Department__c = 'Automotive';
            opty.StageName = 'Qualification/Analysis';                
            opty.CloseDate = System.Today();
            opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NS_General_Opportunity').getRecordTypeId();
            opty.NSSales_609_1_SwitchRemovalRequest__c = true;
            insert opty;
            opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NSSales_609_1').getRecordTypeId();
            update opty;
            opty.NSSales609_1_InitaitedDate__c=date.parse('06/07/2012');
            NSSales_609_1_All_Switch_Coordinates__c switchCordinateRec = create_Switch_CordinateRecord();
            opty.NSSales_609_1_SwitchIdentificationNumber__c = switchCordinateRec.NSSales_Switch_Identification_Numbers__c;
            update opty;
            create_609_1_MngrRoutingRecord(idManager);
            create_609_1_FSMngrRoutingRecord(fsManager);
            NSSales_609_1_ApprovalProcessController.changeOptyStageOn_609_1_LocationSelect(opty.Id,'DE','Kent','Ada','DEARBORN','B',null,'487.66');
            NSSales_609_1_ApprovalProcessController.initiate_609_1_ApprovalProcess(opty.Id);
            List<ProcessInstanceWorkitem> pI = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :opty.id];
            System.debug('pI'+pI);
              System.debug('pI[0].Id'+pI[0].Id);
            NSSales_NPOCommentController.getVisibility(pI[0].Id);
           NSSales_NPOCommentController.fetchCommentsProcessItemDetailsOpp(pI[0].ID);
            List<ProcessInstanceStep>  processInstanceStepList = [SELECT id,ProcessInstanceId FROM ProcessInstanceStep where ProcessInstanceId = :pI[0].ProcessInstanceId]; 
           NSSales_NPOCommentController.fetchCommentProcessInstanceStepOpp(processInstanceStepList[0].id);
            NSSales_NPOCommentController.getVisibility(processInstanceStepList[0].Id);
            System.debug('ProcessInstanceStepList'+processInstanceStepList);
        } 
    }
    
    
    
    public static NSSales_609_1_All_Switch_Coordinates__c create_Switch_CordinateRecord(){
        NSSales_609_1_All_Switch_Coordinates__c switchCordinateRec = new NSSales_609_1_All_Switch_Coordinates__c();
        switchCordinateRec.NSSales_Switch_Identification_Numbers__c ='100026320';
        switchCordinateRec.NSSales_Latitude__c ='37.27935701';
        switchCordinateRec.NSSales_Longitude__c ='-79.90954751';
        insert switchCordinateRec;
        return switchCordinateRec;
    }
    
    public static NSSales_609_1_Manager_Routing__c create_609_1_MngrRoutingRecord(User idManager){
        NSSales_609_1_Manager_Routing__c newIDManagerRoutingRec = new NSSales_609_1_Manager_Routing__c();
        newIDManagerRoutingRec.NSSales_State_Name__c = 'DE';
        newIDManagerRoutingRec.NSSales_County_Name__c = 'Kent';
        newIDManagerRoutingRec.NSSales_City_Name__c = 'Ada';
        newIDManagerRoutingRec.NSSales_Territory_Name__c = 'Norfolk';
        newIDManagerRoutingRec.NSSales_ID_Manager_Name__c = idManager.id;
        insert newIDManagerRoutingRec;
        return newIDManagerRoutingRec;
    }
    
    
    public static NSSales_609_1FSSalesManager__c create_609_1_FSMngrRoutingRecord(User fsManager){
        NSSales_609_1FSSalesManager__c fsmanager1 = new NSSales_609_1FSSalesManager__c();
        fsmanager1.NSSales_609_1_OperatingDivision__c = 'DEARBORN';
        fsmanager1.NSSales_609_1_Sales_Prefix__c = 'B';
        fsmanager1.NSSales_609_1_Suffix__c = '';
        fsmanager1.NSSales_609_1_LMP__c = 486.88;
        fsmanager1.NSSales_609_1_HMP__c = 518.30;
        fsmanager1.NSSales_609_1_Field_Sales_Manager__c = fsManager.id;
        insert fsmanager1;
        return fsmanager1;
    }
}