force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/NSSales_609_1_All_Switch_Coordinates__c.object-meta.xml
<CustomObject>
    <label>All Switch Coordinate</label>
    <nameField>
        <displayFormat>SWC-{00000}</displayFormat>
        <label>AllSwitchCo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Switch Coordinates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Latitude__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Latitude__c</fullName>
    <label>Latitude</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Longitude__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Longitude__c</fullName>
    <label>Longitude</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_All_Switch_Coordinates__c/fields/NSSales_Switch_Identification_Numbers__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Switch_Identification_Numbers__c</fullName>
    <label>Switch Identification Numbers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/NSSales_609_1_Manager_Routing__c.object-meta.xml
<CustomObject>
    <label>609.1 Manager Routing</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>609.1 Manager Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1 Managers Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_City_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_County_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_County_Name__c</fullName>
    <label>County Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_ID_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ID_Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industrial Development Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X609_1_Managers_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_State_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/NSSales_609_1FSSalesManager__c.object-meta.xml
<CustomObject>
    <label>609.1 FS Manager Routing</label>
    <nameField>
        <displayFormat>FSMR-{0000}</displayFormat>
        <label>NSSales_609.1FSSalesManager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1FSSalesManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/fields/NSSales_609_1_Sales_Prefix__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Sales_Prefix__c</fullName>
    <label>Prefix</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NSSales_609_1_OperatingDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BK</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>BV</fullName>
            </value>
            <value>
                <fullName>BX</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
            <value>
                <fullName>ALAB</fullName>
                <isActive>false</isActive>
                <label>ALAB</label>
            </value>
            <value>
                <fullName>DEAR</fullName>
                <isActive>false</isActive>
                <label>DEAR</label>
            </value>
            <value>
                <fullName>GEOR</fullName>
                <isActive>false</isActive>
                <label>GEOR</label>
            </value>
            <value>
                <fullName>HARR</fullName>
                <isActive>false</isActive>
                <label>HARR</label>
            </value>
            <value>
                <fullName>ILLN</fullName>
                <isActive>false</isActive>
                <label>ILLN</label>
            </value>
            <value>
                <fullName>PIED</fullName>
                <isActive>false</isActive>
                <label>PIED</label>
            </value>
            <value>
                <fullName>PITT</fullName>
                <isActive>false</isActive>
                <label>PITT</label>
            </value>
            <value>
                <fullName>POCA</fullName>
                <isActive>false</isActive>
                <label>POCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_SwitchRemovalRequest__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_SwitchRemovalRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of Req#3332</description>
    <label>609.1 Switch Removal Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Territory_Name__c</fullName>
    <label>Territory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Harrisburg East</fullName>
            </value>
            <value>
                <fullName>Harrisburg West</fullName>
            </value>
            <value>
                <fullName>Indianapolis</fullName>
            </value>
            <value>
                <fullName>Knoxville</fullName>
            </value>
            <value>
                <fullName>Norfolk</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Ohio</fullName>
            </value>
            <value>
                <fullName>Roanoke</fullName>
            </value>
            <value>
                <fullName>South Carolina</fullName>
            </value>
            <value>
                <fullName>St. Louis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NS_General_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NS_General_Opportunity</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>General Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/NSSales_609_1.recordType-meta.xml
<RecordType>
    <fullName>NSSales_609_1</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>609.1</label>
</RecordType>

force-app/main/default/classes/NSSales_609_1_ApprovalProcessTest.cls
@isTest (SeeAllData=false)
public class NSSales_609_1_ApprovalProcessTest {
    
    /*Method to create 609.1 Opportunity*/
    public static  Opportunity create_609_1_Opty(){
        Account acc = new Account(
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                            SobjectType ='Account' Limit 1].id,
            Name='AccountForOppotunity');
         system.assertEquals(null, acc.id);
       insert acc;
        Opportunity opty = new Opportunity();
        opty.Name = 'Test';
        opty.AccountId = acc.Id;
        opty.NS_Originating_Department__c = 'Automotive';
        opty.StageName = 'Qualification/Analysis';                
        opty.CloseDate = System.Today();
        opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NS_General_Opportunity').getRecordTypeId();
        opty.NSSales_609_1_SwitchRemovalRequest__c = true;
        insert opty; 
        return opty;
        
    }
    
    
    public static OpportunityShare optyShare(Id optyId, Id userId, string oppAccess){
        OpportunityShare optyShare = new OpportunityShare();
        optyShare.OpportunityId = optyId;
        optyShare.OpportunityAccessLevel =oppAccess; 
        optyShare.UserOrGroupId = userId;
        insert optyShare;
        return optyShare;
    }
    
    public static NSSales_609_1_All_Switch_Coordinates__c create_Switch_CordinateRecord(){
        NSSales_609_1_All_Switch_Coordinates__c switchCordinateRec = new NSSales_609_1_All_Switch_Coordinates__c();
        switchCordinateRec.NSSales_Switch_Identification_Numbers__c ='100026320';
        switchCordinateRec.NSSales_Latitude__c ='37.27935701';
        switchCordinateRec.NSSales_Longitude__c ='-79.90954751';
        insert switchCordinateRec;
        return switchCordinateRec;
    }
    
    public static NSSales_609_1_Manager_Routing__c create_609_1_MngrRoutingRecord(User idManager){
        NSSales_609_1_Manager_Routing__c newIDManagerRoutingRec = new NSSales_609_1_Manager_Routing__c();
        newIDManagerRoutingRec.NSSales_State_Name__c = 'DE';
        newIDManagerRoutingRec.NSSales_County_Name__c = 'Kent';
        newIDManagerRoutingRec.NSSales_City_Name__c = 'Ada';
        newIDManagerRoutingRec.NSSales_Territory_Name__c = 'Norfolk';
        newIDManagerRoutingRec.NSSales_ID_Manager_Name__c = idManager.id;
        insert newIDManagerRoutingRec;
        return newIDManagerRoutingRec;
    }
    
    
    public static NSSales_609_1FSSalesManager__c create_609_1_FSMngrRoutingRecord(User fsManager){
        NSSales_609_1FSSalesManager__c fsmanager1 = new NSSales_609_1FSSalesManager__c();
        fsmanager1.NSSales_609_1_OperatingDivision__c = 'DEARBORN';
        fsmanager1.NSSales_609_1_Sales_Prefix__c = 'B';
        fsmanager1.NSSales_609_1_Suffix__c = '';
        fsmanager1.NSSales_609_1_LMP__c = 486.88;
        fsmanager1.NSSales_609_1_HMP__c = 518.30;
        fsmanager1.NSSales_609_1_Field_Sales_Manager__c = fsManager.id;
        insert fsmanager1;
        return fsmanager1;
    }
    
    public static Map<String,User> getUserDetails(Opportunity opty){
        List<id> approversId = new List<id>();
        Map<String,User> userMap = new Map<String,User>();
        approversId.add(opty.NSSales_609_1_IDManagerApprovalOwner__c);
        approversId.add(opty.NSSales_609_1_FSManagerApprovalOwner__c);
        List<User> userRecList = [select id, name, email from User where id in :approversId];
        for(User userDetail : userRecList){
            if(opty.NSSales_609_1_IDManagerApprovalOwner__c == userDetail.id)
            {
               userMap.put('ID', userDetail); 
            }
            if(opty.NSSales_609_1_FSManagerApprovalOwner__c == userDetail.id)
            {
                userMap.put('FS', userDetail);  
            }
        }
        return userMap;
    }
      
    @istest
    public static Opportunity push_609_1_For_Approval(){
        
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User idManager;
        User fsManager;
        
        //Creating Sales manager test User  
        System.runAs( admin ){ 
            Profile agent1 = UserTestFactory.createProfile(NS_StaticVariablesUtility.NSSalesIDProfile);
            idManager = UserTestFactory.createUserSales(22,agent1.Id);
            Profile agent2 = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            fsManager = UserTestFactory.createUserSales(24,agent2.Id);
        }
        
        system.test.StartTest();
        //Opportunity Creation
        Opportunity Opty = create_609_1_Opty();
        optyShare(Opty.Id,fsManager.Id,NS_StaticVariablesUtility.editAccess);
        optyShare(Opty.Id,idManager.Id,NS_StaticVariablesUtility.editAccess);
        NSSales_609_1_All_Switch_Coordinates__c switchCordinateRec = create_Switch_CordinateRecord();
        opty.NSSales_609_1_SwitchIdentificationNumber__c = switchCordinateRec.NSSales_Switch_Identification_Numbers__c;
        opty.NSSales609_1_InitaitedDate__c =system.today();
        update opty;
        /* To cover fetchstate, fetchCounty and fetchCity */
        NSSales_609_1_Manager_Routing__c newIDManagerRoutingRec = create_609_1_MngrRoutingRecord(idManager);
        
        NSSales_609_1_ApprovalProcessController.fetchState();
        NSSales_609_1_ApprovalProcessController.fetchCounty('Kent');
        NSSales_609_1_ApprovalProcessController.fetchCity('Kent','Ada');
        /*finish here for fetchstate, fetchCounty and fetchCity*/
        
        /*To cover checkMilepostRange */ 
        
        NSSales_609_1FSSalesManager__c fsmanager1 = create_609_1_FSMngrRoutingRecord(fsManager);
        NSSales_609_1FSSalesManager__c fsmanager2 = new NSSales_609_1FSSalesManager__c();
        fsmanager2.NSSales_609_1_OperatingDivision__c = 'GEORGIA';
        fsmanager2.NSSales_609_1_Sales_Prefix__c = '';
        fsmanager2.NSSales_609_1_Suffix__c = 'H';
        fsmanager2.NSSales_609_1_LMP__c = 240.36;
        fsmanager2.NSSales_609_1_HMP__c = 423.86;
        insert fsmanager2;
        
        NSSales_609_1_ApprovalProcessController.checkMilepostRange('DEARBORN','B','','487.88');
        NSSales_609_1_ApprovalProcessController.checkMilepostRange('GEORGIA','','H','245.00');
        /* finish here for checkMilepostRange*/ 
        /*To cover changeOptyStageOn_609_1_LocationSelect */ 
        opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NSSales_609_1').getRecordTypeId();
        update opty;
        
        NSSales_609_1_ApprovalProcessController.selectFieldSalesManager('GEORGIA',null,'H','245.00');
        NSSales_609_1_ApprovalProcessController.changeOptyStageOn_609_1_LocationSelect(opty.Id,'DE','Kent','Ada','DEARBORN','B',null,'487.66');
        
        // update opty;/*finish here for changeOptyStageOn_609_1_LocationSelect*/
        /* To cover ApprovalProcess */
        NSSales_609_1_ApprovalProcessController.initiate_609_1_ApprovalProcess(opty.Id);
        List<ProcessInstanceWorkitem> p = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :opty.Id];
        system.assertNotEquals(null, p[0].id);
        
        NSSales_609_1_ApprovalProcessController.fetchProcessItemDetails(p[0].id);
        NSSales_609_1_ApprovalProcessController.fetchOpportunityId(p[0].id);
        NSSales_609_1_ApprovalProcessController.fetchObjectId(p[0].id);
        NSSales_609_1_ApprovalProcessController.fetchprocessInstanceId(p[0].id);
        NSSales_609_1_ApprovalProcessController.setProcessInstanceWorkitemId(opty.Id); 
        NSSales_609_1_ApprovalProcessController.setProcessInstanceWorkitemId(p[0].id);
        system.test.StopTest();
        return opty;
    }
    
    @istest
    public static void test_609_Approve(){
       
        Opportunity fetchOptyRec = [select ID,NSSales_609_1_IDManagerApprovalOwner__c,NSSales_609_1_FSManagerApprovalOwner__c
                                    from Opportunity
                                    where id = :push_609_1_For_Approval().id];
        User idUser =  getUserDetails(fetchOptyRec).get('ID');
        User fsUser =  getUserDetails(fetchOptyRec).get('FS');
          system.assertnotEquals(null, fetchOptyRec.id);
        System.runAs(idUser){
            NSSales_609_1_ApprovalProcessController.popluteApprovalDecisionOnApprove(fetchOptyRec.id); 
        }
        System.runAs(fsUser){
            NSSales_609_1_ApprovalProcessController.popluteApprovalDecisionOnApprove(fetchOptyRec.id);
        }
        NSSales_609_1_ApprovalProcessController.fetchStageName(fetchOptyRec.id);
                
    }
    
    @istest
    public static void test_609_As_Reject(){
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(15,sysprof.Id);
        Opportunity fetchOptyRec = [select ID,NSSales_609_1_FSManagerApprovalOwner__c, NSSales_609_1_IDManagerApprovalOwner__c
                                    from Opportunity
                                    where id = :push_609_1_For_Approval().id];
         system.assertnotEquals(null, fetchOptyRec.id);
        User idUser =  getUserDetails(fetchOptyRec).get('ID');
        User fsUser =  getUserDetails(fetchOptyRec).get('FS');
        System.runAs(fsUser){
            NSSales_609_1_ApprovalProcessController.updateOpportunityOnReject(fetchOptyRec.id,'3');
        }
        System.runAs(admin){
            NSSales_609_1_ApprovalProcessController.callRecallProcess(fetchOptyRec.Id, 'recalled', 'Removed');
        }
    }
    
    @istest
    public static void test_609_Recall(){

        
        Opportunity fetchOptyRec = [select ID,NSSales_609_1_FSManagerApprovalOwner__c, NSSales_609_1_IDManagerApprovalOwner__c
                                    from Opportunity
                                    where id = :push_609_1_For_Approval().id];
        User idUser =  getUserDetails(fetchOptyRec).get('ID');
        User fsUser =  getUserDetails(fetchOptyRec).get('FS');
        List<ProcessInstanceWorkitem> p = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :fetchOptyRec.Id];     
         system.assertNotEquals(null, p[0].id);
        System.runAs(fsUser){
            NSSales_609_1_ApprovalProcessController.updateOpportunityOnReject(fetchOptyRec.id,'2');
        }
        System.runAs(idUser){
            NSSales_609_1_ApprovalProcessController.checkApprover(fetchOptyRec.id);  
            NSSales_609_1_ApprovalProcessController.checkRecallAccess(fetchOptyRec.id);
            NSSales_609_1_ApprovalProcessController.callRecallProcess(fetchOptyRec.Id, 'recalled', 'Removed');
            NSSales_609_1_ApprovalProcessController.checkRecall(fetchOptyRec.Id);
            NSSales_609_1_ApprovalProcessController.updateOptyStage(fetchOptyRec.Id);
            NSSales_609_1_ApprovalProcessController.fetchApprovalStatus(p[0].ProcessInstanceId);
            NSSales_609_1_ApprovalProcessController.callApprovalProcess(p[0].id,'Rejecting request for Opportunity', 'Reject');
            
        }
    } 
}