force-app/main/default/objects/Market_Intel_Associated_Campaign__c/Market_Intel_Associated_Campaign__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Campaign</label>
    <nameField>
        <displayFormat>MICAMP-{0000}</displayFormat>
        <label>Market Intel Associated Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Campaign__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Market Intel (Campaign)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Campaigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Campaign__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipLabel>Market Intel Associated Campaigns</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/Market_Intel_Associated_Contact__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Contact</label>
    <nameField>
        <displayFormat>MIC-{0000}</displayFormat>
        <label>Market Intel Associated Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Market Intel (Contact)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipLabel>Market Intel Associated Contacts</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/Market_Intel_Associated_Opportunities__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Opportunities</label>
    <nameField>
        <displayFormat>MIO-{0000}</displayFormat>
        <label>Market Intel Associated Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipName>Market_Intel_Associated_Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Market Intel (Opportunity)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Opportunity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/Market_Intelligence__c.object-meta.xml
<CustomObject>
    <description>Custom object to capture Marketing Intelligence for Executive &amp; Marketing ConnectNS users.</description>
    <label>Market Intel</label>
    <nameField>
        <label>Market Intel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Intel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intelligence__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <inlineHelpText>Multi-pick; Use Detail to refine Geography.</inlineHelpText>
    <label>Geography</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US-East</fullName>
            </value>
            <value>
                <fullName>US-West</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Asia Pac Rim</fullName>
            </value>
            <value>
                <fullName>So America</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Worldwide</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Norfolk Southern Terriroty</fullName>
                <isActive>false</isActive>
                <label>Norfolk Southern Terriroty</label>
            </value>
            <value>
                <fullName>North America</fullName>
                <isActive>false</isActive>
                <label>North America</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <inlineHelpText>Multi-pick; Use Carrier to refine Mode.</inlineHelpText>
    <label>Mode</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>IM</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>Ocean</fullName>
            </value>
            <value>
                <fullName>Transload</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
            <value>
                <fullName>Water Inland</fullName>
                <isActive>false</isActive>
                <label>Water Inland</label>
            </value>
            <value>
                <fullName>Water Ocean</fullName>
                <isActive>false</isActive>
                <label>Water Ocean</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>If more than one, select Other; put details in the body of Intel section.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>NS Marketing Event</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Intelligence__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business At Risk / Lost</fullName>
            </value>
            <value>
                <fullName>Business or Plant Closure / Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Competitor Capacity</fullName>
            </value>
            <value>
                <fullName>Competitor Customer Service</fullName>
            </value>
            <value>
                <fullName>Competitor Service Change</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Economic</fullName>
            </value>
            <value>
                <fullName>Equipment Capacity/Quality</fullName>
                <label>Equipment Capacity / Quality</label>
            </value>
            <value>
                <fullName>Market Conditions</fullName>
            </value>
            <value>
                <fullName>Mergers / Acquisitions</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>New or Cancelled Service</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Project Announcement</fullName>
            </value>
            <value>
                <fullName>Site Search</fullName>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Site Selection</fullName>
                <isActive>false</isActive>
                <label>Site Selection</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/NS_Market_Intel_Account__c.object-meta.xml
<CustomObject>
    <description>This is a junction object allowing multiple Market Intel records to be associated to multiple accounts</description>
    <label>Market Intel Associated Account</label>
    <nameField>
        <displayFormat>MIA-{0000}</displayFormat>
        <label>Market Intel Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Intel (Account)</relationshipLabel>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NSSales_MarketIntelControllerTest.cls
/**@author  Accenture
* @Created Date Oct,2019
* @version  1.0 
* @description This is the test class for NSSales_MarketIntelController
*/
@isTest
public class NSSales_MarketIntelControllerTest {
    
    @istest
    private static void createMarketIntelAssociatedObjectRecTest(){
     
        system.test.StartTest();
        Account testAccount = null;
        Contact testContact = null;
        Opportunity testOpty = null;
        Campaign testCampaign = null;
        Market_Intelligence__c testMIRec = null;
        
        //Creating an admin user
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        //Creating a Sales Manager user
        Profile testUserProfile=UserTestFactory.createProfile('NS Sales Manager');
        User testUser= UserTestFactory.createUser(87, testUserProfile.Id);
        
        system.runAs(admin){
            //Creating an Account
            testAccount = AccountTestFactory.getOnlineAccountRecord('Test Account');
            Database.insert(testAccount,false);
            
            //Creating a Contact
            testContact = ContactTestFactory.createContactRecord(testAccount.id,NS_StaticVariablesUtility.CONST_BLANK);
            
            //Creating an Opportunity
            testOpty = NSSales_OpportunityFactory.createOpportunityForHelper();
            
            //Creating a Campaign
            testCampaign = new Campaign();
            testCampaign.name = 'Test Campaign';
            Database.insert(testCampaign,false);
        }
        
        system.assertNotEquals(null, testAccount.id); 
        system.assertNotEquals(null, testContact.id); 
        system.assertNotEquals(null, testOpty.id); 
        system.assertNotEquals(null, testCampaign.id); 
        
        system.runAs(testUser){  
            //Creating a Market Intel Record
            testMIRec = new Market_Intelligence__c();
            testMIRec.Name = 'test Market Intel';
           	testMIRec.Type__c = 'Economic';
            testMIRec.Source__c ='Conference';
            testMIRec.Mode__c = 'Ocean';
            testMIRec.Geography__c = 'US-West';
            Database.insert(testMIRec,false);
        }
        
        system.assertNotEquals(null, testMIRec.id);
        
        //Checking if a Market Intel Associated Account Record has been created when a MI record is created from Account
        NSSales_MarketIntelController.createMarketIntelAssociatedObjectRec(testAccount.id,testMIRec.id);
        NS_Market_Intel_Account__c miAssocAccountRec = [Select id from NS_Market_Intel_Account__c where NSSales_Account__c = :testAccount.id and NSSales_Market_Intel__c = :testMIRec.id];
        system.assertNotEquals(null, miAssocAccountRec.id);
        
        
        //Checking if a Market Intel Associated Contact Record has been created when a MI record is created from Contact
        NSSales_MarketIntelController.createMarketIntelAssociatedObjectRec(testContact.id,testMIRec.id);
        Market_Intel_Associated_Contact__c miAssocContactRec = [Select id from Market_Intel_Associated_Contact__c where Contact__c = :testContact.id and Market_Intel__c = :testMIRec.id];
        system.assertNotEquals(null, miAssocContactRec.id);
        
        //Checking if a Market Intel Associated Opportunity Record has been created when a MI record is created from Opportunity
        NSSales_MarketIntelController.createMarketIntelAssociatedObjectRec(testOpty.id,testMIRec.id);
        Market_Intel_Associated_Opportunities__c miAssocOptyRec = [Select id from Market_Intel_Associated_Opportunities__c where Opportunity__c = :testOpty.id and Market_Intel__c = :testMIRec.id];
        system.assertNotEquals(null, miAssocOptyRec.id);
        
        
       //Checking if a Market Intel Associated Campaign Record has been created when a MI record is created from Campaign
        NSSales_MarketIntelController.createMarketIntelAssociatedObjectRec(testCampaign.id,testMIRec.id);
        Market_Intel_Associated_Campaign__c miAssocCampRec = [Select id from Market_Intel_Associated_Campaign__c where Campaign__c = :testCampaign.id and Market_Intel__c = :testMIRec.id];
        system.assertNotEquals(null, miAssocCampRec.id);
        system.test.StopTest();
    }
    
    @isTest
    private static void testMethodException(){
        String objectName = NSSales_MarketIntelController.findObjectNameFromRecordId('10');
        System.assertEquals(objectName,'');
    }
    
}