force-app/main/default/objects/Market_Intel_Associated_Campaign__c/Market_Intel_Associated_Campaign__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Campaign</label>
    <nameField>
        <displayFormat>MICAMP-{0000}</displayFormat>
        <label>Market Intel Associated Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Campaign__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Market Intel (Campaign)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Campaigns</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Campaign__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipLabel>Market Intel Associated Campaigns</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Campaigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/Market_Intel_Associated_Contact__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Contact</label>
    <nameField>
        <displayFormat>MIC-{0000}</displayFormat>
        <label>Market Intel Associated Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Market Intel (Contact)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Contact__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipLabel>Market Intel Associated Contacts</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/Market_Intel_Associated_Opportunities__c.object-meta.xml
<CustomObject>
    <label>Market Intel Associated Opportunities</label>
    <nameField>
        <displayFormat>MIO-{0000}</displayFormat>
        <label>Market Intel Associated Opportunity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/fields/Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipName>Market_Intel_Associated_Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Market_Intel_Associated_Opportunities__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Market Intel (Opportunity)</relationshipLabel>
    <relationshipName>Market_Intel_Associated_Opportunity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/NS_Market_Intel_Account__c.object-meta.xml
<CustomObject>
    <description>This is a junction object allowing multiple Market Intel records to be associated to multiple accounts</description>
    <label>Market Intel Associated Account</label>
    <nameField>
        <displayFormat>MIA-{0000}</displayFormat>
        <label>Market Intel Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Intel Associated Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Intel (Account)</relationshipLabel>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NS_Market_Intel_Account__c/fields/NSSales_Market_Intel__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Market_Intel__c</fullName>
    <label>Market Intel</label>
    <referenceTo>Market_Intelligence__c</referenceTo>
    <relationshipName>Market_Intel_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NSSales_MarketIntelController.cls
/**@author  Accenture
* @Created Date Oct,2019
* @version  1.0 
* @description This class contains Server side controller for Marketing Intel functionalities 
*/ 
public class NSSales_MarketIntelController {
    private static final String CLASS_NAME = 'NSSales_MarketIntelController';
    private static final String METHOD_NAME1 = 'createMarketIntelAssociatedObjectRec';
    private static final String METHOD_NAME2 = 'findObjectNameFromRecordId';
    private static final String METHOD_NAME3 = 'createMarketIntelAssociatedAccountRec';
    private static final String METHOD_NAME4 = 'createMarketIntelAssociatedContactRec';
    private static final String METHOD_NAME5 = 'createMarketIntelAssociatedOptyRec';
    private static final String METHOD_NAME6 = 'createMarketIntelAssociatedCampRec';
    
    @AuraEnabled
    public static void createMarketIntelAssociatedObjectRec(String sourceId,String marketIntelRecordId){
        try{
            String objectName = findObjectNameFromRecordId(sourceId);
            if(objectName.equalsIgnoreCase('Account'))
            {
                createMarketIntelAssociatedAccountRec(sourceId,marketIntelRecordId);
            }
            if(objectName.equalsIgnoreCase('Contact'))
            {
                createMarketIntelAssociatedContactRec(sourceId,marketIntelRecordId);
            }
            if(objectName.equalsIgnoreCase('Opportunity'))
            {
                createMarketIntelAssociatedOptyRec(sourceId,marketIntelRecordId);
            }
            if(objectName.equalsIgnoreCase('Campaign'))
            {
                createMarketIntelAssociatedCampRec(sourceId,marketIntelRecordId);
            }
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME1);
        } 
    }
    
    @AuraEnabled
    public static String findObjectNameFromRecordId(String recordId){
        String objName = '';
        try{
            String keyCode = recordId.subString(0,3);
            Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
            for(Schema.SObjectType objectInstance : gd.values())
            {
                if(objectInstance.getDescribe().getKeyPrefix() == keyCode)
                {
                    objName = objectInstance.getDescribe().getName();
                }
            }
        }
        catch (Exception exp) {
            /*Inserting a record in Exception object*/
            system.debug('exp-->'+exp);
            NS_StaticVariablesUtility.createExceptionRecord(exp, CLASS_NAME, METHOD_NAME2);
        } 
        return objName;
    }
    
    @AuraEnabled
    public static void createMarketIntelAssociatedAccountRec(String sourceId,String marketIntelRecordId){
        
        NS_Market_Intel_Account__c newRec = new NS_Market_Intel_Account__c();
        newRec.NSSales_Account__c = sourceId;
        newRec.NSSales_Market_Intel__c = marketIntelRecordId;
        try{
            Database.insert(newRec,false);
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME3);
        } 
        
    }
    
    public static void createMarketIntelAssociatedContactRec(String sourceId,String marketIntelRecordId){
        
        Market_Intel_Associated_Contact__c newRec = new Market_Intel_Associated_Contact__c();
        newRec.Contact__c = sourceId;
        newRec.Market_Intel__c = marketIntelRecordId;
        try{
            Database.insert(newRec,false);
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME3);
        } 
        
    }
    public static void createMarketIntelAssociatedOptyRec(String sourceId,String marketIntelRecordId){
        
        Market_Intel_Associated_Opportunities__c newRec = new Market_Intel_Associated_Opportunities__c();
        newRec.Opportunity__c = sourceId;
        newRec.Market_Intel__c = marketIntelRecordId;
        try{
            Database.insert(newRec,false);
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME5);
        } 
        
    }
    
     public static void createMarketIntelAssociatedCampRec(String sourceId,String marketIntelRecordId){
        
        Market_Intel_Associated_Campaign__c newRec = new Market_Intel_Associated_Campaign__c();
        newRec.Campaign__c = sourceId;
        newRec.Market_Intel__c = marketIntelRecordId;
        try{
            Database.insert(newRec,false);
        }
        catch(Exception exp) 
        {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp,CLASS_NAME,METHOD_NAME6);
        } 
        
    }
}