force-app/main/default/objects/Account/recordTypes/NS_OnlineCustomerBusiness.recordType-meta.xml
<RecordType>
    <fullName>NS_OnlineCustomerBusiness</fullName>
    <active>true</active>
    <description>A Business Account is used for a customer entity that Norfolk Southern contacts for billing purposes</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/NSSales_NPO_Approval__c/NSSales_NPO_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing approvers for NPO Approval Process.</description>
    <label>NPO Approval</label>
    <nameField>
        <displayFormat>NPO-{00000}</displayFormat>
        <label>NPO Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPO Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Approval_Type__c</fullName>
    <description>Approval Type for the related opportunity</description>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPS Planning North</fullName>
            </value>
            <value>
                <fullName>OPS Planning Central</fullName>
            </value>
            <value>
                <fullName>OPS Planning South</fullName>
            </value>
            <value>
                <fullName>OPS Planning West</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Network Capacity</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Commercial Planning</fullName>
            </value>
            <value>
                <fullName>Interline Services</fullName>
            </value>
            <value>
                <fullName>Auto/Intermodal</fullName>
            </value>
            <value>
                <fullName>Industrial Products/Unit</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>OPS Planning NOC</fullName>
            </value>
            <value>
                <fullName>OPS Planning East</fullName>
                <isActive>false</isActive>
                <label>OPS Planning East</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>NPO Approvals</relationshipLabel>
    <relationshipName>NPO_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Status__c</fullName>
    <description>It captures the approval status i.e, approved or rejected</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_SalesNPO_Approvers__c.field-meta.xml
<CustomField>
    <fullName>NS_SalesNPO_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_East__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_East__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>OPS Planning East</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_North__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_North__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>OPS Planning North</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NS_General_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NS_General_Opportunity</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>General Opportunity</label>
</RecordType>

force-app/main/default/classes/NSSales_NPOApprovalProcessControllerTest.cls
@istest
public class NSSales_NPOApprovalProcessControllerTest {
    @istest
    public static void NSSales_NPOApprovalProcessControllerTestPositive()
    {
        Opportunity op =  simpleOpty();
        Profile testIDProf = UserTestFactory.createProfile(NS_StaticVariablesUtility.NSSalesIDProfile);
        User testIDUser= UserTestFactory.createUser(13, testIDProf.Id);
        User testIDUser2= UserTestFactory.createUser(121, testIDProf.Id);
        
        op.NS_SalesNPO_Approvers__c=testIDUser.Id;
        op.NSSales_OPS_Planning_North__c = True;
        update op;
        op.NSSales_OPS_Planning_North__c = False;
        op.NSSales_OPS_Planning_East__c = True;
        update op;
        List<NSSales_NPO_Approval__c> childNPO2Opty= [select id,NSSales_Approval_Type__c,NSSales_Status__c from NSSales_NPO_Approval__c where NSSales_Related_Opportunity__c =: op.Id];
        List<ProcessInstanceWorkitem> pI = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :childNPO2Opty[0].Id];
        List<ProcessInstanceWorkitem> piDetails = NSSales_NPOApprovalProcessController.fetchProcessItemDetails(pI[0].ProcessInstanceId);
        String piDetailsString = NSSales_NPOApprovalProcessController.fetchProcessInstanceStepId(pI[0].ProcessInstanceId);
        String npoObjReq = NSSales_NPOApprovalProcessController.findObjectNameFromRecordId(childNPO2Opty[0].Id);
        String ObjVisibility = NSSales_NPOApprovalProcessController.getVisibility(pI[0].id);//npoObjReq
        String piObjId = NSSales_NPOApprovalProcessController.fetchObjectId(pI[0].id);
        
        NSSales_NPOApprovalProcessController.callReassignProcess(pI[0].id, testIDUser2.id,'Reassigned','Reassigned');
        NSSales_NPOApprovalProcessController.callApprovalProcess(pI[0].id, 'ApprovedTest', 'Approve');
        NSSales_NPOApprovalProcessController.callApprovalProcess(pI[0].id,'Rejecting request for Opportunity', 'Reject');
    }
    
    public static Opportunity simpleOpty()
    {
        Account acc = new Account(
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                            SobjectType ='Account' Limit 1].id,
            Name='AccountForOppotunity');
        insert acc;
        system.assertNotEquals(null,acc.id); 
        Opportunity opty = new Opportunity();
        opty.Name = 'Test';
        opty.AccountId = acc.Id;
        opty.NS_Originating_Department__c = 'Automotive';
        opty.StageName = 'Qualification/Analysis';                
        opty.CloseDate = System.Today();
        opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NS_General_Opportunity').getRecordTypeId();
        insert opty;
        return opty;
    }
    
}