force-app/main/default/objects/Account/recordTypes/NS_OnlineCustomerService.recordType-meta.xml
<RecordType>
    <fullName>NS_OnlineCustomerService</fullName>
    <active>true</active>
    <description>A Service Account is used for a customer located on and serviced by Norfolk Southern</description>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BU__c/fields/NS_Account_Type_BU__c.field-meta.xml
<CustomField>
    <fullName>NS_Account_Type_BU__c</fullName>
    <description>Sales - Classify the type of Account the customer is based on the NS Business group or user.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Beneficial Cargo Owner</fullName>
            </value>
            <value>
                <fullName>Port</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Drayage Provider</fullName>
            </value>
            <value>
                <fullName>Broker/3PL</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Economic Development Ally</fullName>
            </value>
            <value>
                <fullName>Engineering Consultant</fullName>
            </value>
            <value>
                <fullName>Railroad</fullName>
            </value>
            <value>
                <fullName>Site Selector</fullName>
            </value>
            <value>
                <fullName>State or Local EDC</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
            <value>
                <fullName>Shipper/Receiver</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
                <isActive>false</isActive>
                <label>Broker</label>
            </value>
            <value>
                <fullName>Direct Customer</fullName>
                <isActive>false</isActive>
                <label>Direct Customer</label>
            </value>
            <value>
                <fullName>Indirect Customer</fullName>
                <isActive>false</isActive>
                <label>Indirect Customer</label>
            </value>
            <value>
                <fullName>Partner</fullName>
                <isActive>false</isActive>
                <label>Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Consignee / Beneficial Cargo Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Consignee)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>NS_Contract_Start_Date__c</fullName>
    <description>The date contract goes into effect</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_Carrier__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_Carrier__c</fullName>
    <label>Destination Carrier</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_City__c</fullName>
    <description>the destination city will come from Workbench when possible</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_State__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_State__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Estimated_Volume__c.field-meta.xml
<CustomField>
    <fullName>NS_Estimated_Volume__c</fullName>
    <description>Volume (workbench in calcualtes volume in Carloads)</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Estimated Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_Carrier__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_Carrier__c</fullName>
    <label>Origin Carrier</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_City__c</fullName>
    <description>The origin city will come from Workbench when possible. This field is required to move the Opportunity to the Internal Review Stage</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_SalesNPO_Approvers__c.field-meta.xml
<CustomField>
    <fullName>NS_SalesNPO_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_WB_RequestID__c.field-meta.xml
<CustomField>
    <fullName>NS_WB_RequestID__c</fullName>
    <description>Workbench request unique identifier</description>
    <label>Request ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Account Classification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>You cannot select an Account Classification record that does not belong to this Account.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities (Account Classification)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Commodity_Group__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Commodity_Group__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Commodity Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Need_by_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Need_by_Date__c</fullName>
    <inlineHelpText>The date marketing needs the final NPO Review decision. This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Need by Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_NPO_Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>NSSales_NPO_Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NPO Final Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_North__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_North__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>OPS Planning North</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Route__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Route__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Shipper__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a required field that is part of the NPO Process</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Shipper)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Spot_Contract__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Spot_Contract__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Spot/Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Origin_State__c.field-meta.xml
<CustomField>
    <fullName>Origin_State__c</fullName>
    <description>will come from workbench</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Start_Date__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Projected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NS_OppWorkBenchRequestTest.cls
@isTest(SeeAllData=false)
private class NS_OppWorkBenchRequestTest {
    
    static testmethod void testOpportunityWBInsert(){
        String StageNameInternalReview = 'Internal Review';
        NS_TriggerSettings__c customSet1 = new NS_TriggerSettings__c();
        customSet1.Name=NS_StaticVariablesUtility.assocTrigger;
        customSet1.NS_IsActive__c=true;
        Database.insert(customSet1,false);
        System.debug('CustomSet: '+customSet1.id);
        NS_Integration_Endpoints__c ie = new NS_Integration_Endpoints__c();
        ie.Name = 'CustomerContactChange_Teams';
        ie.Endpoint_URL__c = 'https://www.google.com';
        insert ie;
        
        Account newAcc = new Account(Name='Test',RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerService' AND 
                                                                 SobjectType ='Account' Limit 1].id);
        insert newAcc;
         BU__c asso = new BU__c();
         asso.Account__c=newAcc.id;
         //asso.NS_Account_Type_BU__c='Direct Customer';
         asso.RecordTypeId=Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Industrial Products').getRecordTypeId();              
         insert asso;     
        User atest;
        Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
        atest = UserTestFactory.createUserSales(22,agent.Id);
        Opportunity opp = new Opportunity();
         opp.Name = 'Test';
         opp.AccountId = newAcc.Id;
         opp.NS_Originating_Department__c = 'Industrial Products';
         opp.StageName = 'Qualification/Analysis';
         opp.NS_Origin_Carrier__c = 'NS';
         opp.NS_Origin_City__c = 'Norfolk';
         opp.Origin_State__c = 'VA';
         opp.NS_Destination_Carrier__c = 'NS';
        opp.NS_Destination_City__c = 'Atlanta';
         opp.NS_Destination_State__c = 'NA';
         opp.CloseDate = System.Today();
        
         opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('General Opportunity').getRecordTypeId();
        insert opp;
       // Opp.NS_SalesNPO_Approvers__c = atest.id;
        Opp.StageName=StageNameInternalReview;
        Opp.NS_Origin_Station__c='Test';                 
        Opp.NS_Estimated_Volume__c=100;
        Opp.NS_Destination_Station__c='Test123';
        Opp.NSSales_Commodity_Group__c='Test123';
        Opp.Projected_Start_Date__c=System.Today();
        Opp.NS_Contract_Start_Date__c=System.Today();
        Opp.NS_Destination_State__c='Test';
        Opp.Frequency__c='Weekly';
        Opp.NSSales_Spot_Contract__c='Spot';
        Opp.NSSales_Need_by_Date__c=System.Today();
        Opp.NS_Origin_City__c='Kolkata';
        Opp.NSSales_Route__c='Test';
        Opp.NS_Destination_City__c='Kolkata';
        Opp.Consignee__c=newAcc.id;                
        Opp.NSSales_Shipper__c=newAcc.id;
        Opp.NSSales_Account_Classification__c=asso.id;
        //opp.NS_WB_RequestID__c ='123456789012';
        update opp;
        Opp.NS_SalesNPO_Approvers__c = atest.id;
        //Opp.NSSales_OPS_Planning_North__c = true;
        Opp.NSSales_NPO_Final_Approval__c = true;
        opp.StageName ='Proposal';
        update opp;
       Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, new NscorpWSCalloutRequestHandler_Mock());
        Test.stopTest();
    }

}