force-app/main/default/objects/Account/recordTypes/NS_OnlineCustomerBusiness.recordType-meta.xml
<RecordType>
    <fullName>NS_OnlineCustomerBusiness</fullName>
    <active>true</active>
    <description>A Business Account is used for a customer entity that Norfolk Southern contacts for billing purposes</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/BU__c/BU__c.object-meta.xml
<CustomObject>
    <description>Object to store Business Unit Account Classifications for NS Sales</description>
    <label>Account Classification</label>
    <nameField>
        <displayFormat>Acct-Classification-{0000000000}</displayFormat>
        <label>Account Classification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BU__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BU</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Consignee / Beneficial Cargo Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Consignee)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>NS_Contract_Start_Date__c</fullName>
    <description>The date contract goes into effect</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_City__c</fullName>
    <description>the destination city will come from Workbench when possible</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_State__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_State__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Destination_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Destination_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Destination Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Estimated_Volume__c.field-meta.xml
<CustomField>
    <fullName>NS_Estimated_Volume__c</fullName>
    <description>Volume (workbench in calcualtes volume in Carloads)</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Estimated Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_City__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_City__c</fullName>
    <description>The origin city will come from Workbench when possible. This field is required to move the Opportunity to the Internal Review Stage</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Origin_Station__c.field-meta.xml
<CustomField>
    <fullName>NS_Origin_Station__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Origin Station</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_SalesNPO_Approvers__c.field-meta.xml
<CustomField>
    <fullName>NS_SalesNPO_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Account Classification</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>You cannot select an Account Classification record that does not belong to this Account.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>BU__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BU__c</referenceTo>
    <relationshipLabel>Opportunities (Account Classification)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Commodity_Group__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Commodity_Group__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Commodity Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Need_by_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Need_by_Date__c</fullName>
    <inlineHelpText>The date marketing needs the final NPO Review decision. This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Need by Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity_Number__c</fullName>
    <displayFormat>ON{0000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_Central__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_Central__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPS Planning Central</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Route__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Route__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Shipper__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a required field that is part of the NPO Process</description>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Shipper)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Spot_Contract__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Spot_Contract__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Spot/Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Start_Date__c</fullName>
    <inlineHelpText>This field is required to move the Opportunity to the Internal Review Stage</inlineHelpText>
    <label>Projected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NPOInboundEmailTest.cls
@isTest
public class NPOInboundEmailTest {
    
             
        Public static String approvedStatus = 'Approved';
        Public static String StageNameInternalReview = 'Internal Review';  
    
        public static testmethod void testNPOInboundEmail(){    
        
        //Creating Admin User  
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User atest;   
          
    //Creating Sales manager test User  
     System.runAs( admin ){ 
            Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            atest = UserTestFactory.createUserSales(22,agent.Id);
        
     
     } 
            
        //Creating Opportunity    
        // Creating an account for Opportunity
            Account acc = new Account(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                                SobjectType ='Account' Limit 1].id,
                Name='AccountForOppotunity');
            insert acc;
           //Account classification Creation            
            BU__c accclassi= new BU__c();
            accclassi.RecordTypeId=Schema.SObjectType.BU__c.getRecordTypeInfosByName().get('Automotive').getRecordTypeId();
            accclassi.Account__c=acc.id;
            insert accclassi;
            // Creating a New Opportunity
            Opportunity Opty = new Opportunity();
            Opty.Name = 'Test';
            Opty.AccountId = acc.Id;
            Opty.NS_Originating_Department__c = 'Automotive';
            Opty.NS_Origin_Station__c='Test';	
            Opty.StageName = 'Qualification/Analysis';                
            Opty.CloseDate = System.Today();
            Opty.NS_Estimated_Volume__c=50;
            Opty.NS_Destination_Station__c='Test123';
            Opty.NSSales_Commodity_Group__c='Test123';
            Opty.Projected_Start_Date__c=System.Today();
            Opty.NS_Contract_Start_Date__c=System.Today();
            Opty.NS_Destination_State__c='Test';
            Opty.Frequency__c='Weekly';
            Opty.NSSales_Spot_Contract__c='Spot';
            Opty.NSSales_Need_by_Date__c=System.Today();
            Opty.NS_Origin_City__c='Kolkata';
            Opty.NSSales_Route__c='Test';
            Opty.NS_Destination_City__c='Kolkata';
            Opty.Consignee__c=acc.id;                
            Opty.NSSales_Shipper__c=acc.id;
            Opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('General Opportunity').getRecordTypeId();
            //Opty.NSSales_Account_Classification__c =  accclassi.id;      
            insert Opty;
            

       //Update Opportunity   
        Opty.NS_SalesNPO_Approvers__c = atest.id;
            
        Opty.StageName=StageNameInternalReview;
        Opty.NSSales_OPS_Planning_Central__c = TRUE;
        Opty.NSSales_Account_Classification__c =  accclassi.id; 
        
        update Opty;
        Opportunity sNew = [select Id, NSSales_Opportunity_Number__c from Opportunity where id = : Opty.id];
    
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        email.subject = 'Sandbox: '+sNew.NSSales_Opportunity_Number__c;//string.valueof(Opty.id);
        email.plainTextBody = 'Hello, this a test email body. For testing purposes only';
        email.HtmlBody = 'Hello, this a test email body. For testing purposes only.';
        email.toAddresses = new List<String>{System.Label.emailServiceAddress};   
        email.ccAddresses = new List<String>{'nsTest@testmail.com'};
            
        Messaging.InboundEmail.Header hditem= new Messaging.InboundEmail.Header();   
        hditem.name='Date'; 
        hditem.value='< image Tue, 28 Apr 2009 14:08:37 -0700 >';
        email.headers=new Messaging.inboundEmail.Header[]{hditem}; 
       
   
        envelope.fromAddress = 'test.testing@sometest.com'; 
         
        

        NPOInboundEmail emailServiceHandler = new NPOInboundEmail();
        system.debug(email.headers);
        Messaging.InboundEmailResult result =  emailServiceHandler.handleInboundEmail(email, envelope);
        
  
      
         
         }
    

}