force-app/main/default/objects/Account/recordTypes/NS_OnlineCustomerBusiness.recordType-meta.xml
<RecordType>
    <fullName>NS_OnlineCustomerBusiness</fullName>
    <active>true</active>
    <description>A Business Account is used for a customer entity that Norfolk Southern contacts for billing purposes</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/Opportunity_Site__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to connect Sites and Opportunities</description>
    <label>Opportunity Site</label>
    <nameField>
        <displayFormat>OPPSTE - {0}</displayFormat>
        <label>Opportunity Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Site__c/fields/NSSales_Stage__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
                <default>true</default>
                <label>Working</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_opportunitySiteTriggerHelperTest.cls
/**************************************************************************
Description  : Test Class for NSSales_opportunitySiteTriggerHelper class
Developer    : Accenture Solutions
Date         : 05-07-2019
****************************************************************************/
@isTest
public class NSSales_opportunitySiteTriggerHelperTest {
    
    static testMethod void updateOpportunityTestMethod(){
        
        Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
        User atest = UserTestFactory.createUserSales(22,agent.Id);
        
        system.test.StartTest();
        System.runAs(atest){
            
            Account acc = new Account(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName ='NS_OnlineCustomerBusiness' AND 
                                SobjectType ='Account' Limit 1].id,Name='AccountForOppotunity');
            insert acc;
            
            Opportunity Opty = new Opportunity();
            Opty.Name = 'test Opty';
            Opty.AccountId = acc.id;
            Opty.StageName = 'Suspect';
            Opty.CloseDate = System.Today();
            Opty.NS_Originating_Department__c = 'Industrial Development';
            Opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('ID').getRecordTypeId();
            insert Opty;
            
            Site__c siteWon1 = new Site__c();
            Site__c siteWon2 = new Site__c();
            Opportunity_Site__c opSite1 = new Opportunity_Site__c();
            Opportunity_Site__c opSite2 = new Opportunity_Site__c();
            
            
            siteWon1.Name = 'Test Site 1';
            insert siteWon1;
            siteWon1.Name = 'Test Site 2';
            insert siteWon2;
            
            opSite1.Opportunity__c = Opty.Id;
            opSite1.Site__c = siteWon1.id;
            opSite1.NSSales_Stage__c = 'Working';
            insert opSite1;
            opSite1.NSSales_Stage__c = 'Won';
            update opSite1;
            
            opSite2.Opportunity__c = Opty.Id;
            opSite2.Site__c = siteWon1.id;
            opSite2.NSSales_Stage__c = 'Working';
            insert opSite2;
            opSite2.NSSales_Stage__c = 'Won';
            update opSite2;
            
            opSite1.NSSales_Stage__c = 'Lost';
            update opSite1;
            opSite2.NSSales_Stage__c = 'Lost';
            update opSite2;
        }
        System.test.StopTest();
        
    }
    
    
}