force-app/main/default/objects/NSSales_NPO_Approval__c/NSSales_NPO_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object for storing approvers for NPO Approval Process.</description>
    <label>NPO Approval</label>
    <nameField>
        <displayFormat>NPO-{00000}</displayFormat>
        <label>NPO Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPO Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>NPO Approvals</relationshipLabel>
    <relationshipName>NPO_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_NPO_Approval__c/fields/NSSales_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Status__c</fullName>
    <description>It captures the approval status i.e, approved or rejected</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Any_NPO_Rejected__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Any_NPO_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Any NPO Rejected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity_Number__c</fullName>
    <displayFormat>ON{0000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/NSSalesNPORejectionTriggerHelper.cls
public class NSSalesNPORejectionTriggerHelper {
    /*******not in use******/
    /*public static Final String npo_REJECTED = 'Rejected';
    public static Final String npo_REJECTION_REASON = 'Recalled due to Rejection';
    
    public static void retriveOptyData(List<NSSales_NPO_Approval__c> npoList){
        
        List<Id> npoRelatedOptyId = new List<Id>();
        List<Opportunity> optyFieldUpdate = new List<Opportunity>();
        List<string> OppNumList = new List<string>();
        boolean run = false;
        for(NSSales_NPO_Approval__c npo : npoList)
        {
            if(run == false){
                run = true;
                if(npo.NSSales_Status__c == npo_REJECTED)
                {
                    npoRelatedOptyId.add(npo.NSSales_Related_Opportunity__c);
                }   
            }
        }
        if(npoRelatedOptyId.size()>0){
        for(Opportunity op: [SELECT Id,NSSales_Any_NPO_Rejected__c,NSSales_Opportunity_Number__c from Opportunity WHERE ID IN: npoRelatedOptyId]){
            op.NSSales_Any_NPO_Rejected__c= TRUE;
            optyFieldUpdate.add(op);
            OppNumList.add(op.NSSales_Opportunity_Number__c);
        }
        update optyFieldUpdate;
        
        NSSales_RecallNPO.recall(OppNumList,npo_REJECTION_REASON);  
        }
    }
    */
}