force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/NSSales_Marketing_Manager_Assignment__c.object-meta.xml
<CustomObject>
    <description>This custom objects allows ConnectNS users to associate Marketing Manager Assignments to an Account. An Account can contain multiple marketing manager assignments.</description>
    <label>Marketing Manager Assignment</label>
    <nameField>
        <displayFormat>MA-{0}</displayFormat>
        <label>Marketing Manager Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Account Name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignments</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NSSales_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing Research &amp; Forecasting</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the Marketing Manager user name of the related record</description>
    <label>Marketing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Marketing_Manager_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_Marketing_Manager_Assignment__c/fields/NSSales_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Field Sales Manager</fullName>
            </value>
            <value>
                <fullName>Group Manager</fullName>
            </value>
            <value>
                <fullName>Industrial Development Manager</fullName>
            </value>
            <value>
                <fullName>Market Manager</fullName>
            </value>
            <value>
                <fullName>National Account Manager</fullName>
            </value>
            <value>
                <fullName>Pricing Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Automotive Account Manager</fullName>
                <isActive>false</isActive>
                <label>Automotive Account Manager</label>
            </value>
            <value>
                <fullName>Industrial Products Account Manager</fullName>
                <isActive>false</isActive>
                <label>Industrial Products Account Manager</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/NSSales_MarketingManagerAssignmentLog__c.object-meta.xml
<CustomObject>
    <description>This object captures the history of Marketing Manager Assignment object</description>
    <label>Marketing Manager Assignment Log</label>
    <nameField>
        <displayFormat>MMLog-{0}</displayFormat>
        <label>Marketing Manager Assignment Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignment Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the account name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignment Logs</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignment_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NSSales_BusinessUnit__c</fullName>
    <description>It stores the related marketing manager&#39;s Business Unit</description>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <description>It stores the Marketing Manager user name of the record</description>
    <label>Marketing Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Role__c</fullName>
    <description>It stores the role of the Marketing Manager</description>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_MktMngrLogContTest.cls
/**@author  Accenture
* @Created Date 21stOct,2019
* @version  1.0
* @description This is the test class of NSSales_MrktMngrAssgnmntLogsController
*/ 
@isTest(SeeAllData=false)
private class NSSales_MktMngrLogContTest {
    static testmethod void testTerminalInsert(){
        Test.startTest();
        // Create a account
        Account acc = AccountTestFactory.createAccountRecord('NFS');
        system.assertNotEquals(null,acc.id); 
        //Create a profile
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User testUser = UserTestFactory.createUser(14,sysprof.Id);
        system.assertNotEquals(null,testUser.id); 
        // Create a marketing manager assignment
        NSSales_Marketing_Manager_Assignment__c createAsgn=new NSSales_Marketing_Manager_Assignment__c();
        createAsgn.NSSales_BusinessUnit__c='Automotive';
        createAsgn.NSSales_MarketingManager__c=testUser.id;
        createAsgn.NSSales_Role__c='Service Manager';
        createAsgn.NSSales_Account__c=acc.Id;
        insert createAsgn;
        system.assertNotEquals(null,createAsgn.id); 
        //Check to see whetermarketing manager assignment is associated with the log 
        NSSales_MarketingManagerAssignmentLog__c logDetails=[SELECT Id,NSSales_BusinessUnit__c,NSSales_MarketingManager__c,NSSales_Role__c,NSSales_Account__c FROM NSSales_MarketingManagerAssignmentLog__c WHERE NSSales_Account__c = :acc.Id];
        system.assertNotEquals(null,logDetails.Id); 
        NSSales_MrktMngrAssgnmntLogsController.getMarketingManagerAssignmentLog(acc.Id);
        Test.stopTest();
    }
}