force-app/main/default/objects/Account/fields/NS_AssociatedBusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NS_AssociatedBusinessUnit__c</fullName>
    <defaultValue>IF( $RecordType.Name=&#39;Industrial Development&#39;, &#39;Industrial Development&#39;, &#39; &#39;)</defaultValue>
    <description>It indicates the Business Unit or Units with whom a particular Account does business</description>
    <inlineHelpText>Business Unit or Units who do business with that particular Account</inlineHelpText>
    <label>Associated NS Business Unit(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Revenue Accounting</fullName>
            </value>
            <value>
                <fullName>Revenue Waybilling</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Classification__c.field-meta.xml
<CustomField>
    <fullName>Contact_Classification__c</fullName>
    <description>A way to classify the type of contact</description>
    <inlineHelpText>Select the primary Contact type</inlineHelpText>
    <label>Contact Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Economic Development</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>NS Internal</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Days__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Days__c</fullName>
    <description>contact notification subscription window days of the week preference</description>
    <label>Notification Delivery Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_the_week</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Hour_Ending__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Hour_Ending__c</fullName>
    <label>Notification Delivery Hour Ending</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Hour_Starting__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Hour_Starting__c</fullName>
    <description>ENS subscription window delivery hour starting</description>
    <label>Notification Delivery Hour Starting</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Window_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Window_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the contact has or has not subscribed to receive NS ENS notification.</description>
    <inlineHelpText>Whether the contact has or has not subscribed to receive NS ENS notification.</inlineHelpText>
    <label>Delivery Window Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Email_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether contact subscribed to receive notification via email</description>
    <label>Notification Email Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Phone_Number__c</fullName>
    <description>Mobile phone number used to received sms notification</description>
    <label>Notification Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Push_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Push_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether  contact subscribed to receive notification via mobile push.</description>
    <label>Notification Push Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_SMS_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_SMS_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether contact subscribed to receive notification via SMS</description>
    <label>Notification SMS Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NS_BusinessUnit__c</fullName>
    <description>Business Unit or Units who do business with that particular individual.</description>
    <inlineHelpText>Business Unit or Units who do business with that particular individual.</inlineHelpText>
    <label>Associated NS Business Unit(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Revenue Accounting</fullName>
            </value>
            <value>
                <fullName>Revenue Waybilling</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_ContactRole__c.field-meta.xml
<CustomField>
    <fullName>NS_ContactRole__c</fullName>
    <label>Contact Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_ContactStatus__c.field-meta.xml
<CustomField>
    <fullName>NS_ContactStatus__c</fullName>
    <description>Indicates whether the Contact is Active or Inactive for use.</description>
    <inlineHelpText>Contact Status denotes if Contact is active or inactive or requested for deactivation.</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Request Deactivation</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_OSSContactRole__c.field-meta.xml
<CustomField>
    <fullName>NS_OSSContactRole__c</fullName>
    <description>It denotes the OSS Role in Contacts.</description>
    <label>OSS Account Contact Role</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_PrefConMethd__c.field-meta.xml
<CustomField>
    <fullName>NS_PrefConMethd__c</fullName>
    <description>Form of communication that the Contact would prefer to be used</description>
    <inlineHelpText>Form of communication that the Contact would prefer to be used</inlineHelpText>
    <label>Preferred Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Phone</fullName>
            </value>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Other Phone 1</fullName>
            </value>
            <value>
                <fullName>Other Phone 2</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_PreferredName__c.field-meta.xml
<CustomField>
    <fullName>NS_PreferredName__c</fullName>
    <description>Preferred Name or nickname of Contact</description>
    <inlineHelpText>Preferred Name or nickname of Contact</inlineHelpText>
    <label>Preferred Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_RACF_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_RACF_ID__c</fullName>
    <label>RACF ID</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/ENS_Message_Payload__c.field-meta.xml
<CustomField>
    <fullName>ENS_Message_Payload__c</fullName>
    <description>ENS notification message payload field content, unparsed</description>
    <label>ENS Message Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Event Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/isInternalUser__c.field-meta.xml
<CustomField>
    <fullName>isInternalUser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>whether the receiver is an internal norfolk southern employee</description>
    <label>is Internal User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_Email_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Box is checked if subscriber selects email as a notification channel.</description>
    <inlineHelpText>Box is checked if subscriber selects email as a notification channel.</inlineHelpText>
    <label>Email Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_Push_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Push_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Box is checked if subscriber selects Push as a notification channel.</description>
    <inlineHelpText>Box is checked if subscriber selects Push as a notification channel.</inlineHelpText>
    <label>Push Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_SMS_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_SMS_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/RACF_Id__c.field-meta.xml
<CustomField>
    <fullName>RACF_Id__c</fullName>
    <description>subscriber NS RACF Id</description>
    <label>RACF Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Associated_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Associated_Business_Unit__c</fullName>
    <description>This tells Business unit associated with a particular user</description>
    <inlineHelpText>Business unit associated with a particular user</inlineHelpText>
    <label>Associated Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Equipment Planning</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing Research &amp; Forecasting</fullName>
            </value>
            <value>
                <fullName>NPO</fullName>
            </value>
            <value>
                <fullName>OSS</fullName>
            </value>
            <value>
                <fullName>Revenue Accounting</fullName>
            </value>
            <value>
                <fullName>Revenue Waybilling</fullName>
            </value>
            <value>
                <fullName>Unit Train</fullName>
            </value>
            <value>
                <fullName>NS Real Estate</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Days_of_the_week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MON</fullName>
    </customValue>
    <customValue>
        <fullName>TUE</fullName>
    </customValue>
    <customValue>
        <fullName>WED</fullName>
    </customValue>
    <customValue>
        <fullName>THU</fullName>
    </customValue>
    <customValue>
        <fullName>FRI</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>SUN</fullName>
    </customValue>
    <description>days of the week 3 letter abbreviation</description>
    <masterLabel>Days of the week</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NS_LocalServiceNotificationTest.cls
@isTest(SeeAllData=false)
private class NS_LocalServiceNotificationTest {
    static testmethod void testNotificationInsert(){
        //FOR ACCOUNT RECORD
        Account a = new Account();
        a.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service').getRecordTypeId();
        a.Name='NFS';
        a.NS_AssociatedBusinessUnit__c='oss';
        a.Phone='1234567';
        insert a;
        Account aaa=[select Name ,Phone from Account where id=:a.id];
        system.debug('Record Ids Are-->'+aaa);
        //FOR CONTACT RECORD
        Contact obj= new Contact();
        obj.FirstName='XYZ';
        obj.LastName='User';
        obj.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('General Contact').getRecordTypeId();
        obj.NS_ContactStatus__c='Active';
        obj.NS_PreferredName__c='ABC';
        obj.MobilePhone='1234567';
        obj.NS_BusinessUnit__c='oss';
        obj.NS_PrefConMethd__c='Work Phone';
        obj.Notification_Delivery_Hour_Starting__c='750';
        obj.Notification_Delivery_Hour_Ending__c='100';
        obj.NS_OSSContactRole__c='Manager';
        obj.NS_ContactRole__c='Tester';
        obj.NS_RACF_ID__c='ABCD';
        obj.Contact_Classification__c='Customer';
        obj.Notification_Phone_Number__c='1234567';
        obj.Notification_SMS_Enabled__c=true;
        obj.Notification_Push_Enabled__c=true;
        obj.Notification_Email_Enabled__c=true;
        obj.Notification_Delivery_Window_Enabled__c=true;
        obj.Notification_Delivery_Days__c='Mon;Tue;Wed;Fri;';
        obj.Accountid= a.id;
        insert obj;
        //FOR USER RECORD
        User atest;
        Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
        atest = UserTestFactory.createUserSales(22,agent.Id);
        atest.FederationIdentifier='ABCD';
        update atest;
        atest=[SELECT  Associated_Business_Unit__c from User WHERE Id=:atest.Id ];
        System.assertEquals('OSS', atest.Associated_Business_Unit__c);
        //FOR NOTIFICATION RECORD
        Notification_Log__c notifi = new Notification_Log__c();//
        notifi.Event_Name__c = 'PLANNED';
        notifi.ENS_Message_Payload__c='{"eventtype":"PLANNED","eventdesc":"Local Service Planned","custclasscd":"H11","eqdtls":{"eqdtl":[{"action":"PLCE","eqinit":"BKTY","eqnr":"0000152146","wbsernr":"6460642492","emptyind":"L","cartype":"BOXCAR","classcd":"H11","commodity":"PPBRD","stcc":"2631117","wgt":"91","rlsereqtype":null,"fromtk":null,"fromspot":"0","totk":null,"tospot":"0","eqloparsn":"test lopa"},{"action":"PULL","eqinit":"NS","eqnr":"0000150291","wbsernr":"6460710473","emptyind":"L","cartype":"BOXCAR","classcd":"H11","commodity":"PPBRD","stcc":"2631117","wgt":"98","rlsereqtype":null,"fromtk":null,"fromspot":"0","totk":null,"tospot":"0","eqloparsn":"test lopa2"},{"action":"PLCE","eqinit":"TBOX","eqnr":"0000664011","wbsernr":"6460480971","emptyind":"E","cartype":"HOPPER","classcd":"B12","commodity":"CORN","stcc":"2631117","wgt":"125","rlsereqtype":"Loaded full","fromtk":null,"fromspot":"0","totk":2,"tospot":"1","eqloparsn":null}]}}';
        notifi.RACF_Id__c='ABCD';
        notifi.isInternalUser__c=false;
        notifi.Total_Cars_to_Place__c=1;
        notifi.Total_Cars_to_Pull__c=2;
        notifi.Est_Service_Window_From__c=datetime.newInstance(2019, 10, 10, 12, 30, 0);
        notifi.Est_Service_Window_To__c=datetime.newInstance(2019, 10, 11, 12, 30, 0);
        Test.startTest();  
        insert notifi;
        Test.stopTest();   
        notifi=[SELECT Event_Name__c from  Notification_Log__c WHERE Id =:notifi.Id];
        System.assertEquals('PLANNED', notifi.Event_Name__c);
    }
}