force-app/main/default/objects/Campaign_Member_Log__c/Campaign_Member_Log__c.object-meta.xml
<CustomObject>
    <label>Campaign Member Log</label>
    <nameField>
        <label>Campaign Member Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Action__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Action__c</fullName>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Audit_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Audit_Date__c</fullName>
    <label>Audit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member Log</relationshipLabel>
    <relationshipName>Campaign_Member_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Campaign_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Campaign_Member_Name__c</fullName>
    <label>Campaign Member Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Company__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Company__c</fullName>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_First_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_New_Value__c.field-meta.xml
<CustomField>
    <fullName>NSSales_New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Object__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Old_Value__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Phone__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Phone__c</fullName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Role__c</fullName>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_Log__c/fields/NSSales_Type__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/logsController.cls
public class logsController {
    
      @AuraEnabled
      public static List <Campaign_Member_Log__c> getLogs(string artId) {
        return [SELECT   NSSales_Campaign_Member_Name__c,NSSales_Role__c,NSSales_Phone__c,NSSales_Action__c,NSSales_Old_Value__c, NSSales_New_Value__c ,NSSales_Audit_Date__c,CreatedBy.Name
                FROM Campaign_Member_Log__c where NSSales_Campaign__c =: artId AND NSSales_Object__c='InternalCampaign' ORDER BY createdDate DESC];
      }
    
    
    @AuraEnabled
      public static List <Campaign_Member_Log__c> getCampaignMemberLogs(string artId) {
        return [SELECT  NSSales_Action__c,
                NSSales_Old_Value__c, 
                NSSales_New_Value__c,
                NSSales_Audit_Date__c,
                CreatedBy.Name,
                NSSales_Type__c,
                NSSales_First_Name__c,
                NSSales_Last_Name__c,
                NSSales_Company__c,
                NSSales_Status__c
                FROM Campaign_Member_Log__c where NSSales_Campaign__c =: artId AND NSSales_Object__c='CampaignMember' ORDER BY createdDate DESC];
      }
   
    

}