force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/NSSales_609_1_Manager_Routing__c.object-meta.xml
<CustomObject>
    <label>609.1 Manager Routing</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>609.1 Manager Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1 Managers Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_City_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_County_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_County_Name__c</fullName>
    <label>County Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_ID_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ID_Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industrial Development Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X609_1_Managers_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_State_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_State__c/NSSales_State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This contains the list of unique States of NSSales_609_1_Manager_Routing__c object.</description>
    <label>State</label>
</CustomObject>

force-app/main/default/classes/NSSales_609_1_MgrRoutrTriggerHelperTest.cls
@isTest(seeAllData=false)
public class  NSSales_609_1_MgrRoutrTriggerHelperTest {
    static testMethod void updateNSSales_609_1_MgrRoutinsert() {
        Test.startTest();
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        NSSales_State__c cstState= new NSSales_State__c();
        cstState.Name='testState';
        insert cstState;
        
        NSSales_609_1_Manager_Routing__c routingRec=new NSSales_609_1_Manager_Routing__c();
        routingRec.NSSales_City_Name__c ='Kolkata';
        routingRec.NSSales_State_Name__c='West Bengal';
        routingRec.NSSales_ID_Manager_Name__c=admin.id;
        routingRec.NSSales_Territory_Name__c='test';
        insert routingRec;
       
        NSSales_State__c cstState1= [select name from NSSales_State__c where name ='West Bengal'];
        system.assertNotEquals(null, cstState1.id);
        Test.stopTest();
        
    }
    
    
    static testMethod void updateNSSales_609_1_MgrRoutdelete() {
        
        Test.startTest();
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        NSSales_609_1_Manager_Routing__c routingRec=new NSSales_609_1_Manager_Routing__c();
        routingRec.NSSales_City_Name__c ='Kolkata';
        routingRec.NSSales_State_Name__c='West Bengal';
        routingRec.NSSales_County_Name__c='test county';
        routingRec.NSSales_ID_Manager_Name__c=admin.id;
        routingRec.NSSales_Territory_Name__c='test';
        insert routingRec;
        system.assertNotEquals(null, routingRec.id);
        
        NSSales_609_1_Manager_Routing__c delRecord=[Select id from NSSales_609_1_Manager_Routing__c 
                                                   where NSSales_State_Name__c='West Bengal'
                                                   and NSSales_City_Name__c ='Kolkata'
                                                  and NSSales_County_Name__c='test county'];
        delete delRecord;
        Test.stopTest();
    }  
    
    /*static testMethod void updateNSSales_609_1_MgrRoutedit() {   
        
        Test.startTest();
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        
        NSSales_609_1_Manager_Routing__c routingRec=new NSSales_609_1_Manager_Routing__c();
        routingRec.NSSales_City_Name__c ='Kolkata';
        routingRec.NSSales_State_Name__c='West Bengal';
        routingRec.NSSales_ID_Manager_Name__c=admin.id;
        routingRec.NSSales_Territory_Name__c='test';
        insert routingRec; 
        
        routingRec.NSSales_State_Name__c='Test State';
        update routingRec;
        
        NSSales_State__c cstState1= [select name from NSSales_State__c where name ='Test State'];
        system.assertNotEquals(null, cstState1.id);
       
        Test.stopTest();
    }*/
}