force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/NSSales_609_1_Manager_Routing__c.object-meta.xml
<CustomObject>
    <label>609.1 Manager Routing</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>609.1 Manager Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1 Managers Routing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_City_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_County_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_County_Name__c</fullName>
    <label>County Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_ID_Manager_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ID_Manager_Email_ID__c</fullName>
    <formula>NSSales_ID_Manager_Name__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Industrial Manager Email ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_ID_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ID_Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Industrial Development Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X609_1_Managers_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_LocationIdentifier__c.field-meta.xml
<CustomField>
    <fullName>NSSales_LocationIdentifier__c</fullName>
    <description>This field stores the combination of State, Country and City of a record.</description>
    <formula>NSSales_State_Name__c +&#39;:&#39;+NSSales_County_Name__c+&#39;:&#39;+NSSales_City_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1_Manager_Routing__c/fields/NSSales_State_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_State_Name__c</fullName>
    <label>State Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/NSSales_609_1FSSalesManager__c.object-meta.xml
<CustomObject>
    <label>609.1 FS Manager Routing</label>
    <nameField>
        <displayFormat>FSMR-{0000}</displayFormat>
        <label>NSSales_609.1FSSalesManager Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>609.1FSSalesManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSSales_609_1FSSalesManager__c/fields/NSSales_609_1_Suffix__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Suffix__c</fullName>
    <label>Suffix</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NSSales_609_1_OperatingDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BY</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>DW</fullName>
            </value>
            <value>
                <fullName>EB</fullName>
            </value>
            <value>
                <fullName>EJ</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>KB</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>LS</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>MB</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_City__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_County__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_County__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_FSManagerApprovalOwner__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_FSManagerApprovalOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>609.1 Field Sales Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_FSMngrApprvlOwnerEmail__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_FSMngrApprvlOwnerEmail__c</fullName>
    <description>It stores the 609.1 FS Mngr Apprvl Owner Email</description>
    <label>609.1 FS Mngr Apprvl Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_IDManagerApprovalOwner__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_IDManagerApprovalOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>609.1 Industrial Development Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_IDManagerApprovalOwnerEmai__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_IDManagerApprovalOwnerEmai__c</fullName>
    <description>It stores email id for 609.1 ID Manager Approval Owner Email</description>
    <label>609.1 ID Manager Approval Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
            <value>
                <fullName>ALAB</fullName>
                <isActive>false</isActive>
                <label>ALAB</label>
            </value>
            <value>
                <fullName>DEAR</fullName>
                <isActive>false</isActive>
                <label>DEAR</label>
            </value>
            <value>
                <fullName>GEOR</fullName>
                <isActive>false</isActive>
                <label>GEOR</label>
            </value>
            <value>
                <fullName>HARR</fullName>
                <isActive>false</isActive>
                <label>HARR</label>
            </value>
            <value>
                <fullName>ILLN</fullName>
                <isActive>false</isActive>
                <label>ILLN</label>
            </value>
            <value>
                <fullName>PIED</fullName>
                <isActive>false</isActive>
                <label>PIED</label>
            </value>
            <value>
                <fullName>PITT</fullName>
                <isActive>false</isActive>
                <label>PITT</label>
            </value>
            <value>
                <fullName>POCA</fullName>
                <isActive>false</isActive>
                <label>POCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_Prefix__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Prefix__c</fullName>
    <label>Prefix</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NSSales_609_1_OperatingDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BK</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>BV</fullName>
            </value>
            <value>
                <fullName>BX</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_State__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_Submitter__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Submitter__c</fullName>
    <description>Craeted as part of 609.1 Switch Removal Approval Process</description>
    <label>609.1 Submitter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_SubmitterEmail__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_SubmitterEmail__c</fullName>
    <description>Created as part of 609.1 Switch Removal Approval Process</description>
    <label>609.1 Submitter Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_SendFor609_1_Approval__c.field-meta.xml
<CustomField>
    <fullName>NSSales_SendFor609_1_Approval__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is checked when 609.1 Opportunity is in Internal Review stage</description>
    <label>Send for 609.1 Approval</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NSSales_ID_Opportunity_StateSelection.cls
public class NSSales_ID_Opportunity_StateSelection {
 @AuraEnabled
    public static Opportunity fetchStageName(Id optyRecordId){
        return [SELECT StageName FROM Opportunity where Id = :optyRecordId];
    }
    @AuraEnabled
    public static String[] fetchState(){
        //return [SELECT NSSales_State_Name__c FROM NSSales_609_1_Manager_Routing__c ORDER BY NSSales_State_Name__c];
        String stateList = label.NSSales_IDManagerRouting_State;
        List<String> stateAdd = stateList.split(',');
        //system.debug('stateAdd' +stateAdd);
        return stateAdd;        
    }
    @AuraEnabled
    public static NSSales_609_1_Manager_Routing__c[] fetchCounty(String state){
        return [SELECT NSSales_County_Name__c FROM NSSales_609_1_Manager_Routing__c where NSSales_State_Name__c = :state
                ORDER BY NSSales_County_Name__c];        
    }
      @AuraEnabled
    public static NSSales_609_1_Manager_Routing__c[] fetchCity(String county,String state){
        return [SELECT NSSales_City_Name__c FROM NSSales_609_1_Manager_Routing__c where NSSales_County_Name__c = :county 
                and NSSales_State_Name__c = :state
                ORDER BY NSSales_City_Name__c];    
    }
     @AuraEnabled
    public static void changeOptyStageOn_609_1_LocationSelect(String optyRecordId, String selectedState, String selectedCounty, String selectedCity, String operatingDivision, String prefix, String suffix, String milepost){
        
        Opportunity optyRec = [Select NSSales_609_1_Submitter__c,NSSales_609_1_SubmitterEmail__c, 
                               NSSales_609_1_IDManagerApprovalOwner__c,NSSales_609_1_IDManagerApprovalOwnerEmai__c,
                               NSSales_609_1_FSManagerApprovalOwner__c, NSSales_609_1_FSMngrApprvlOwnerEmail__c, StageName, NSSales_SendFor609_1_Approval__c,
                               NSSales_609_1_State__c, NSSales_609_1_County__c, NSSales_609_1_City__c
                               from Opportunity 
                               where id = :optyRecordId];
        
        String routingLocation = selectedState+':'+selectedCounty+':'+selectedCity;
        NSSales_609_1_Manager_Routing__c routingRec = [SELECT id,NSSales_ID_Manager_Name__c, NSSales_ID_Manager_Email_ID__c,
                                                       NSSales_State_Name__c, NSSales_County_Name__c, NSSales_City_Name__c
                                                       FROM NSSales_609_1_Manager_Routing__c
                                                       WHERE NSSales_LocationIdentifier__c = :routingLocation LIMIT 1];
       
        optyRec.NSSales_609_1_State__c = selectedState;
        optyRec.NSSales_609_1_County__c = selectedCounty;
        optyRec.NSSales_609_1_City__c = selectedCity;
        optyRec.NSSales_609_1_OperatingDivision__c = operatingDivision;
        optyRec.NSSales_609_1_Prefix__c = prefix;
        optyRec.NSSales_609_1_Suffix__c = suffix;
        optyRec.NSSales_609_1_Milepost__c = decimal.valueOf(milepost);
        NSSales_609_1FSSalesManager__c fsRoutingRec = selectFieldSalesManager(operatingDivision, prefix, suffix, milepost);  
        optyRec.NSSales_SAM__c = fsRoutingRec.NSSales_609_1_Field_Sales_Manager__c;
       
        
        update optyRec;
        
    }
      @AuraEnabled
      public static String getMilepost(Id OpprecordId)
      {
          String val;
       for(Opportunity op: [Select NSSales_609_1_Milepost__c from Opportunity where id=:OpprecordId])
       {
           if(op.NSSales_609_1_Milepost__c != NULL)
           {
               val = String.valueOf(op.NSSales_609_1_Milepost__c);//.valueOf(op.NSSales_609_1_Milepost__c);
           }
           else
           {
               val = null;
           }
       }
           return val;
      }
     @AuraEnabled
    public static Boolean checkMilepostRange(String operatingDivision, String prefix, String suffix, String milepost){
        Boolean isValidMilepost = false;
        String uniqueKey =  operatingDivision +':'+ (prefix != '' ? prefix : 'NA') +':'+ (suffix != '' ? suffix : 'NA'); 
        system.debug('uniqueKey-->'+uniqueKey);
        List<NSSales_609_1FSSalesManager__c> fsRoutingRecList = [SELECT NSSales_609_1_LMP__c, NSSales_609_1_HMP__c 
                                                                 From NSSales_609_1FSSalesManager__c
                                                                 WHERE NSSales_609_1_UniqueIdentifier__c = : uniqueKey];
        system.debug('fsRoutingRecList-->'+fsRoutingRecList);
        if(fsRoutingRecList.size()>0){
            for(NSSales_609_1FSSalesManager__c fsRoutingRec : fsRoutingRecList){
                if((decimal.valueOf(milepost) >= fsRoutingRec.NSSales_609_1_LMP__c 
                     && decimal.valueOf(milepost) <= fsRoutingRec.NSSales_609_1_HMP__c)){
                         isValidMilepost = true;
                     }
            }
        }
        system.debug('isValidMilepost-->'+isValidMilepost);
       return isValidMilepost;
    }      
    @AuraEnabled
    public static opportunity getValues(id oppoId){
           Opportunity optyRecall = [Select NSSales_609_1_Suffix__c,NSSales_609_1_Prefix__c,NSSales_609_1_OperatingDivision__c, 
                               NSSales_609_1_IDManagerApprovalOwner__c,NSSales_609_1_IDManagerApprovalOwnerEmai__c,
                               NSSales_609_1_FSManagerApprovalOwner__c, NSSales_609_1_FSMngrApprvlOwnerEmail__c, StageName, NSSales_SendFor609_1_Approval__c,
                               NSSales_609_1_State__c, NSSales_609_1_County__c, NSSales_609_1_City__c,NSSales_609_1_Milepost__c
                               from Opportunity 
                               where id = :oppoId];
        return optyRecall;
    }
    


 @AuraEnabled
    public static NSSales_609_1FSSalesManager__c selectFieldSalesManager(String operatingDivision, String prefix, String suffix, String milepost){
        
        /* Opportunity optyRec = [Select NSSales_609_1_OperatingDivision__c, NSSales_609_1_Prefix__c, NSSales_609_1_Suffix__c,
NSSales_609_1_Milepost__c,  NSSales_609_1_FSManagerApprovalOwner__c, NSSales_609_1_FSMngrApprvlOwnerEmail__c                             
from Opportunity 
where id = :optyRecordId];*/
        NSSales_609_1FSSalesManager__c fsRoutingRec = new NSSales_609_1FSSalesManager__c();
        
        if(prefix!= null){
            fsRoutingRec = [Select  NSSales_609_1_Field_Sales_Manager__c, NSSales_609_1_FSM_Email__c                              
                            from NSSales_609_1FSSalesManager__c 
                            where NSSales_609_1_OperatingDivision__c = :operatingDivision
                            and NSSales_609_1_Sales_Prefix__c = :prefix 
                            and NSSales_609_1_LMP__c <= : decimal.valueOf(milepost)
                            and NSSales_609_1_HMP__c >= : decimal.valueOf(milepost) limit 1
                           ];               
        }
        else if(suffix!= null){
            fsRoutingRec = [Select  NSSales_609_1_Field_Sales_Manager__c, NSSales_609_1_FSM_Email__c                              
                            from NSSales_609_1FSSalesManager__c 
                            where NSSales_609_1_OperatingDivision__c = :operatingDivision
                            and NSSales_609_1_Suffix__c = :suffix
                            and NSSales_609_1_LMP__c <= : decimal.valueOf(milepost)
                            and NSSales_609_1_HMP__c >= : decimal.valueOf(milepost) limit 1];
            
        }
        return fsRoutingRec;
    }
}