force-app/main/default/objects/NSSales_State__c/NSSales_State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This contains the list of unique States of NSSales_609_1_Manager_Routing__c object.</description>
    <label>State</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_Milepost__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Milepost__c</fullName>
    <label>Milepost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_OperatingDivision__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_OperatingDivision__c</fullName>
    <label>Operating Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALABAMA</fullName>
            </value>
            <value>
                <fullName>DEARBORN</fullName>
            </value>
            <value>
                <fullName>GEORGIA</fullName>
            </value>
            <value>
                <fullName>HARRISBURG</fullName>
            </value>
            <value>
                <fullName>ILLINOIS</fullName>
            </value>
            <value>
                <fullName>LAKE</fullName>
            </value>
            <value>
                <fullName>PIEDMONT</fullName>
            </value>
            <value>
                <fullName>PITTSBURGH</fullName>
            </value>
            <value>
                <fullName>POCAHONTAS</fullName>
            </value>
            <value>
                <fullName>ALAB</fullName>
                <isActive>false</isActive>
                <label>ALAB</label>
            </value>
            <value>
                <fullName>DEAR</fullName>
                <isActive>false</isActive>
                <label>DEAR</label>
            </value>
            <value>
                <fullName>GEOR</fullName>
                <isActive>false</isActive>
                <label>GEOR</label>
            </value>
            <value>
                <fullName>HARR</fullName>
                <isActive>false</isActive>
                <label>HARR</label>
            </value>
            <value>
                <fullName>ILLN</fullName>
                <isActive>false</isActive>
                <label>ILLN</label>
            </value>
            <value>
                <fullName>PIED</fullName>
                <isActive>false</isActive>
                <label>PIED</label>
            </value>
            <value>
                <fullName>PITT</fullName>
                <isActive>false</isActive>
                <label>PITT</label>
            </value>
            <value>
                <fullName>POCA</fullName>
                <isActive>false</isActive>
                <label>POCA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_Prefix__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_Prefix__c</fullName>
    <label>Prefix</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NSSales_609_1_OperatingDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>AB</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BK</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BT</fullName>
            </value>
            <value>
                <fullName>BV</fullName>
            </value>
            <value>
                <fullName>BX</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>GJ</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_City__c.field-meta.xml
<CustomField>
    <fullName>NSSales_City__c</fullName>
    <label>Shipping City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_State__c.field-meta.xml
<CustomField>
    <fullName>NSSales_State__c</fullName>
    <label>Shipping State</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Street__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Street__c</fullName>
    <label>Shipping Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NSSales_OpptyAddress_Test.cls
@isTest
public class NSSales_OpptyAddress_Test {

    @isTest static void oppAddress()
    {
     Opportunity od = new Opportunity();   
     od.NSSales_609_1_OperatingDivision__c = 'DEARBORN';
     od.NSSales_609_1_Prefix__c = 'GJ';
     od.NSSales_State__c = 'ND';
     od.NSSales_Street__c = '7, Lok Kalyan Marg';
     od.NSSales_City__c = 'New Delhi';
     od.NSSales_609_1_Milepost__c = 100.00;
     System.debug(od.Id);
     NSSales_Oppty_Address.getaddress(od.Id);
     //stem.assertEquals(od!=null);          
    }   
    
}