force-app/main/default/objects/Opportunity/fields/Building_Clear_Height_ft__c.field-meta.xml
<CustomField>
    <fullName>Building_Clear_Height_ft__c</fullName>
    <label>Minimum Building Clear Height (ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_of_State_Lead__c.field-meta.xml
<CustomField>
    <fullName>Date_of_State_Lead__c</fullName>
    <label>Date of State Lead</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incentive_Per_Car__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Per_Car__c</fullName>
    <description>This field shows the incentive value per car for ID Opportunities only.</description>
    <label>Incentive Per Car ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Contact_Date__c</fullName>
    <label>Initial Contact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Building_Size_sq_ft__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Building_Size_sq_ft__c</fullName>
    <label>Maximum Building Size (Sq Ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Daily_Truck_Volume__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Daily_Truck_Volume__c</fullName>
    <label>Maximum Daily Truck Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Investment__c</fullName>
    <label>Maximum Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Jobs__c</fullName>
    <label>Maximum Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Power_Requirements_MW__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Power_Requirements_MW__c</fullName>
    <label>Maximum Power Requirement (MW)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Site_Size_Acres__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Site_Size_Acres__c</fullName>
    <label>Maximum Site Size (Acres)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maximum_Weekly_Rail_Volume__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Weekly_Rail_Volume__c</fullName>
    <label>Maximum Weekly Rail Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Building_Size_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Building_Size_Sq_Ft__c</fullName>
    <label>Minimum Building Size (Sq Ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Daily_Truck_Volume__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Daily_Truck_Volume__c</fullName>
    <label>Minimum Daily Truck Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Investment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Investment__c</fullName>
    <label>Minimum Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Jobs__c</fullName>
    <label>Minimum Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Power_Requirement_MW__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Power_Requirement_MW__c</fullName>
    <label>Minimum Power Requirement (MW)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Site_Size_Acres__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Site_Size_Acres__c</fullName>
    <label>Minimum Site Size (Acres)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Weekly_Rail_Volume__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Weekly_Rail_Volume__c</fullName>
    <label>Minimum Weekly Rail Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Facility_Type__c.field-meta.xml
<CustomField>
    <fullName>NS_Facility_Type__c</fullName>
    <description>ID request</description>
    <label>Facility Type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Industry_Investment__c.field-meta.xml
<CustomField>
    <fullName>NS_Industry_Investment__c</fullName>
    <description>ID Requirement</description>
    <label>Industry Investment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Private__c.field-meta.xml
<CustomField>
    <fullName>NS_Private__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Annual_System_Revenue__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Annual_System_Revenue__c</fullName>
    <label>Annual System Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Converted_RecordType__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Converted_RecordType__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted RecordType</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Date_Reported__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Date_Reported__c</fullName>
    <label>Date Reported</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_High_Priority__c.field-meta.xml
<CustomField>
    <fullName>NSSales_High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Incentive_Capital__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Incentive_Capital__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incentive Capital</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Marketing_Involved__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Marketing_Involved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Involved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_New_Employees__c.field-meta.xml
<CustomField>
    <fullName>NSSales_New_Employees__c</fullName>
    <label>New Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_New_Exp__c.field-meta.xml
<CustomField>
    <fullName>NSSales_New_Exp__c</fullName>
    <label>New/Exp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Expansion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Owner_Name__c</fullName>
    <formula>Owner.FirstName + &quot; &quot; + Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_SAM_User_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_SAM_User_Name__c</fullName>
    <formula>NSSales_SAM__r.FirstName + &quot; &quot; +  NSSales_SAM__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAM User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_System_Cars__c.field-meta.xml
<CustomField>
    <fullName>NSSales_System_Cars__c</fullName>
    <label>System Cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Traffic_Beginning__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Traffic_Beginning__c</fullName>
    <label>Traffic Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site_Selection_Company__c.field-meta.xml
<CustomField>
    <fullName>Site_Selection_Company__c</fullName>
    <label>Site Selection Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Project__c</fullName>
    <label>Type of Project</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_OpportunityRecordTypeConvertion.cls
public class NSSales_OpportunityRecordTypeConvertion {
   
    @AuraEnabled
    public static void opportunityConvert(Id oppId)
    {
        Opportunity opp = [Select Id,RecordTypeId, StageName from Opportunity where Id=:oppId];
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('General Opportunity').getRecordTypeId();
        opp.StageName = 'Qualification/Analysis';
        opp.NSSales_Converted_RecordType__c = true;
        update opp;
    }
    
    @AuraEnabled
    public static Opportunity showIDOptyInfo(Id oppId){
        
        return ([Select Id,
                 NSSales_Owner_Name__c,
                 NSSales_Annual_System_Revenue__c,
                 Date_of_State_Lead__c,
                 NSSales_Date_Reported__c,
                 NS_Facility_Type__c,
                 NSSales_High_Priority__c,
                 NSSales_Incentive_Capital__c,
                 Incentive_Per_Car__c,
                 NS_Industry_Investment__c,
                 Initial_Contact_Date__c,
                 NSSales_Marketing_Involved__c,
                 Maximum_Building_Size_sq_ft__c,
                 Maximum_Daily_Truck_Volume__c,
                 Maximum_Investment__c,
                 Maximum_Jobs__c,
                 Maximum_Power_Requirements_MW__c,
                 Maximum_Site_Size_Acres__c,
                 Maximum_Weekly_Rail_Volume__c,
                 Building_Clear_Height_ft__c,
                 Minimum_Building_Size_Sq_Ft__c,
                 Minimum_Daily_Truck_Volume__c,
                 Minimum_Investment__c,
                 Minimum_Jobs__c,
                 Minimum_Power_Requirement_MW__c,
                 Minimum_Site_Size_Acres__c,
                 Minimum_Weekly_Rail_Volume__c,
                 NSSales_New_Employees__c,
                 NSSales_New_Exp__c,
                 NS_Private__c,
                 Project_Name__c,
                 NSSales_SAM_User_Name__c,
                 Site_Selection_Company__c,
                 NSSales_System_Cars__c,
                 NSSales_Traffic_Beginning__c,
                 Type_of_Project__c FROM Opportunity Where Id=:oppId]);
    }
}