force-app/main/default/objects/Opportunity/fields/NS_Originating_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Originating_Department__c</fullName>
    <description>Sales - Required field to indicate the NS Business Unit that the Opportunity derived. Field will drive workbench data as well as account classification</description>
    <label>Originating Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Industrial Development</fullName>
            </value>
            <value>
                <fullName>Industrial Products</fullName>
            </value>
            <value>
                <fullName>Intermodal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Network Optimization</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
                <default>true</default>
                <label>Transportation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Implementation_Date__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Implementation_Date__c</fullName>
    <label>Implementation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NSSales_BatchForUpdateOpportunityTest.cls
@isTest 
public class NSSales_BatchForUpdateOpportunityTest {
    
static testMethod void testMethod1()
    {
        List<Opportunity> lstOpps= new List<Opportunity>();
        Account masterAccount= AccountTestFactory.createAccountRecord('BacthTest');
        
        
        
        for(Integer i=0 ;i < 5;i++)
        {
            Opportunity opp = new Opportunity();
            opp.Name ='Name'+i;
            opp.CloseDate=(system.today()+3);
            opp.AccountId=masterAccount.id;
            opp.NS_Originating_Department__c='Automotive';
            opp.NSSales_Implementation_Date__c=system.today();
            opp.StageName='Closed: Implementation Pending';
            opp.RecordTypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('NPO Operations Opportunity').getRecordTypeId();
            lstOpps.add(opp);
        }
        
        insert lstOpps;
        
        Test.startTest();

            NSSales_BatchForUpdateOpportunity obj = new NSSales_BatchForUpdateOpportunity();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    


	public static testMethod void testschedule() {
		Test.StartTest();
		NSSales_BatchForupdateOppScheduler testsche = new NSSales_BatchForupdateOppScheduler();
		String sch = '0 0 01 * * ?';
		system.schedule('Test status Check', sch, testsche );
		Test.stopTest();
	}

 
}