force-app/main/default/objects/Opportunity/fields/NS_SalesNPO_Approvers__c.field-meta.xml
<CustomField>
    <fullName>NS_SalesNPO_Approvers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Approval_Needed__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Approval_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field provisioning the user to go through the whole NPO approval process even if the Volume threshold criteria not met. Checking on this field will trigger process builder to lock the record, notify Approval owner.</description>
    <inlineHelpText>By checking this checkbox the NPO approval process can be initiated manually</inlineHelpText>
    <label>Approval Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Auto_Intermodal__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Auto_Intermodal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto/Intermodal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Auto_Intermodal_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Auto_Intermodal_Status__c</fullName>
    <label>Auto/Intermodal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Industrial_Products_Unit__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Industrial_Products_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Industrial Products/Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Industrial_Products_Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Industrial_Products_Unit_Status__c</fullName>
    <label>Industrial Products/Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Interline_Services__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Interline_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Interline Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Interline_Services_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Interline_Services_Status__c</fullName>
    <label>Interline Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_isRecalled__c.field-meta.xml
<CustomField>
    <fullName>NSSales_isRecalled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRecalled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Network_Capacity__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Network_Capacity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Network Capacity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Network_Capacity_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Network_Capacity_Status__c</fullName>
    <label>Network Capacity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Network_Optimization__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Network_Optimization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Network Optimization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Network_Optimization_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Network_Optimization_Status__c</fullName>
    <label>Network Optimization Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Opportunity_Number__c</fullName>
    <displayFormat>ON{0000000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_Central__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_Central__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPS Planning Central</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_Central_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_Central_Status__c</fullName>
    <label>OPS Planning Central Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_NOC__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_NOC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OPS Planning NOC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_NOC_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_NOC_Status__c</fullName>
    <label>OPS Planning NOC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_North__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_North__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>OPS Planning North</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_North_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_North_Status__c</fullName>
    <description>It stores the related approval record status</description>
    <label>OPS Planning North Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_South__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_South__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>OPS Planning South</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_OPS_Planning_South_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OPS_Planning_South_Status__c</fullName>
    <description>It stores the related approval record status</description>
    <label>OPS Planning South Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Power__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Power__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Power</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Power_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Power_Approval_Status__c</fullName>
    <label>Power Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_StageChanged__c.field-meta.xml
<CustomField>
    <fullName>NSSales_StageChanged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>StageChanged?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Unit_Train__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Unit_Train__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NPO requirement for approval process during Needs Analysis stage.</description>
    <label>Unit Train</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Unit_Train_Status__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Unit_Train_Status__c</fullName>
    <label>Unit Train Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NSSales_RecallNPO.cls
public class NSSales_RecallNPO {
    
    public static Final String StageName_SUSPECT = NSSales_NPOConstants.StageName_SUSPECT;
    public static Final String StageName_QA = NSSales_NPOConstants.StageName_QA;
    //Added by Sudipta for New OPS record type
    public static Final String StageName_NEW = NSSales_NPOConstants.StageName_NEW;
    
    @AuraEnabled
    public static boolean CheckAccess(Id oppId){
        
        Id usrId = UserInfo.getUserId();
        Opportunity op = [SELECT id, OwnerId, NS_SalesNPO_Approvers__c from Opportunity WHERE Id=:oppId LIMIT 1];
        if(usrId == op.OwnerId || usrId == op.NS_SalesNPO_Approvers__c){
            return false;
        }
        else{
            return true;
        }
    }
    
    
    @AuraEnabled
    public static void RecallAction(Id optyId, String recallComment) {
        
        List<Id> opportunityIds = new List<Id>();
        Opportunity op = [SELECT id,NSSales_isRecalled__c from Opportunity WHERE id=:optyId];
        op.NSSales_isRecalled__c = TRUE;
        update op;
        opportunityIds.add(op.id);
        
        BulkRecall(opportunityIds,recallComment);
        
    }
    
    public static void BulkRecall(List<Id> OptyIds,String recallComment){
        
        if(!NSSales_NPOConstants.updateOpportunity){
            NSSales_NPOConstants.updateOpportunity = true;
            Id RecordTypeIdGeneralOpty =  Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('General Opportunity').getRecordTypeId();
            Id RecordTypeIdIDOpty =  Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('ID').getRecordTypeId();
            Id RecordTypeIdReadOnlyOpty =  Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Read Only').getRecordTypeId();
            //Added New  value by Sudipta for new record type
            Id RecordTypeIdOpsReadOnlyOpty =  Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('NPO Operations ReadOnly').getRecordTypeId();
            Id RecordTypeIdOpsOpty =  Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('NPO Operations Opportunity').getRecordTypeId();
            
            
            
            String emailbody;
            List<String> sendTo = new List<String>();
            List<Opportunity> finalOpporunities = new List<Opportunity>();
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            String emailServiceAddress = Label.emailServiceAddress;
            List<Id> sendToSingleMessage = new List<Id>();
            
            List<Opportunity> Opp = new List<Opportunity>([Select id, StageName, RecordTypeId,OwnerId,
                                                           NSSales_OPS_Planning_North__c,
                                                           NSSales_OPS_Planning_South__c,
                                                           NSSales_OPS_Planning_Central__c,
                                                           NSSales_Network_Capacity__c,
                                                           NSSales_Network_Optimization__c,
                                                           NSSales_Unit_Train__c,
                                                           NSSales_Auto_Intermodal__c,
                                                           NSSales_Interline_Services__c,
                                                           NSSales_Industrial_Products_Unit__c,
                                                           //Added New  value by Sudipta for new record type
                                                           NSSales_Power__c,
                                                           NSSales_OPS_Planning_NOC__c,
                                                           
                                                           NSSales_Industrial_Products_Unit_Status__c,
                                                           NSSales_Interline_Services_Status__c,
                                                           NSSales_Network_Capacity_Status__c,
                                                           NSSales_Network_Optimization_Status__c,
                                                           NSSales_OPS_Planning_Central_Status__c,
                                                           NSSales_OPS_Planning_North_Status__c,
                                                           NSSales_OPS_Planning_South_Status__c,
                                                           NSSales_Unit_Train_Status__c,
                                                           NSSales_Auto_Intermodal_Status__c,
                                                           //Added New  value by Sudipta for new record type
                                                           NSSales_OPS_Planning_NOC_Status__c,
                                                           NSSales_Power_Approval_Status__c,
                                                           
                                                           NSSales_isRecalled__c,
                                                           NSSales_Opportunity_Number__c,
                                                           NSSales_StageChanged__c
                                                           from Opportunity where id IN:OptyIds]);
            for(Opportunity o : Opp){
                if(o.RecordTypeId == RecordTypeIdIDOpty ){
                    // 7.18, jlong, comment stage revert on npo rejection
                    o.StageName= StageName_SUSPECT;
                    // 7.18, jlong, end  
                }
                else if((o.RecordTypeId == RecordTypeIdReadOnlyOpty) && o.NSSales_isRecalled__c == TRUE)
                {
                    // 7.18, jlong, comment stage revert on npo rejection
                    o.StageName = StageName_QA;
                    // 7.18, jlong, end
                    o.RecordTypeId = RecordTypeIdGeneralOpty;
                }
                
                //Added by Sudipta for New OPS record type
                 else if((o.RecordTypeId == RecordTypeIdOpsReadOnlyOpty) && o.NSSales_isRecalled__c == TRUE)
                {
                    // 7.18, jlong, comment stage revert on npo rejection
                    o.StageName = StageName_NEW;
                    // 7.18, jlong, end
                    o.RecordTypeId = RecordTypeIdOpsOpty;
                }
                
                else{
                    system.debug('failed all conditions');
                }
                o.NSSales_Approval_Needed__c = False;
                o.NSSales_OPS_Planning_Central__c = False;
                o.NSSales_OPS_Planning_North__c = False;
                o.NSSales_OPS_Planning_South__c = False;
                o.NSSales_Network_Capacity__c = False;
                o.NSSales_Network_Optimization__c = False;
                o.NSSales_Unit_Train__c = False;
                o.NSSales_Auto_Intermodal__c = False;
                o.NSSales_Interline_Services__c = False;
                o.NSSales_Industrial_Products_Unit__c = False;
                //Added New  value by Sudipta for new record type
                o.NSSales_OPS_Planning_NOC__c = False;
                o.NSSales_Power__c=False;
                
                o.NSSales_Industrial_Products_Unit_Status__c = '';
                o.NSSales_Interline_Services_Status__c = '';
                o.NSSales_Network_Capacity_Status__c = '';
                o.NSSales_Network_Optimization_Status__c = '';
                o.NSSales_OPS_Planning_Central_Status__c = '';
                o.NSSales_OPS_Planning_North_Status__c = '';
                o.NSSales_OPS_Planning_South_Status__c = '';
                o.NSSales_Unit_Train_Status__c = '';
                o.NSSales_Auto_Intermodal_Status__c = '';
                 //Added New  value by Sudipta for new record type
                o.NSSales_Power_Approval_Status__c='';
                o.NSSales_OPS_Planning_NOC_Status__c='';
                
                finalOpporunities.add(o);
                
            }
            update finalOpporunities;
            
            for(Opportunity op:finalOpporunities)
            {
                sendToSingleMessage.add(op.id);
            }
            singleEmailMessageSend(finalOpporunities,recallComment);
        }
    }
    
    public static void singleEmailMessageSend(List<Opportunity> finalOpporunities,String recallComment){
        
        String emailbody;
        List<String> sendTo = new List<String>();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        String emailServiceAddress = Label.emailServiceAddress;
        /*****sending email to the email service named NPOApprovalRecall****/
        for (Opportunity op : finalOpporunities)
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            sendTo.clear();
            sendTo.add(emailServiceAddress);
            mail.setToAddresses(sendTo);
            mail.setSubject(op.NSSales_Opportunity_Number__c);
            emailbody = recallComment;
            mail.setHtmlBody(emailbody);
            emails.add(mail);
        }
        
        if(!Test.isRunningTest())
        {
            Messaging.sendEmail(emails);
        }
        /****end of sending email message****/   
    }
    
}