force-app/main/default/objects/Opportunity/fields/NSSales_Site_Lost__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Site_Lost__c</fullName>
    <label>Site Lost</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_Site_Won__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Site_Won__c</fullName>
    <label>Site Won</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/Opportunity_Site__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to connect Sites and Opportunities</description>
    <label>Opportunity Site</label>
    <nameField>
        <displayFormat>OPPSTE - {0}</displayFormat>
        <label>Opportunity Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Site__c/fields/NSSales_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/fields/NSSales_Stage__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
                <default>true</default>
                <label>Working</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Site__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Opportunity_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/NSSales_opportunitySiteTriggerHelper.cls
/*******************************************************
Description  : Helper class for Opportunity SIte Trigger
Developer    : Accenture Solutions
Date         : 05-07-2019
*********************************************************/
public class NSSales_opportunitySiteTriggerHelper {
    
    public static void updateOpportunity(List<Opportunity_Site__c> opSiteList){
        
        List<Opportunity_Site__c> siteToUpdateWon= new List<Opportunity_Site__c>();
        List<Opportunity_Site__c> siteToUpdateLost= new List<Opportunity_Site__c>();
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        List<Opportunity> oppSiteNameUpdate = new List<Opportunity>();
        List<Opportunity> oppSiteNameUpdateLost = new List<Opportunity>();
        List<Id> oppIdList = new List<Id>();
        
        for(Opportunity_Site__c opsite : opSiteList){
            
            if(opsite.NSSales_Stage__c =='Won')
            {
                siteToUpdateWon.add(opsite);
                oppIdList.add(opsite.Opportunity__c);
            }
            else if(opsite.NSSales_Stage__c =='Lost')
            {
                siteToUpdateLost.add(opsite);
                oppIdList.add(opsite.Opportunity__c);
            }
            else{
                system.debug('no action');
            }
        }
        oppToUpdate = [SELECT Id,NSSales_Site_Won__c,NSSales_Site_Lost__c FROM Opportunity WHERE ID in :oppIdList]; 
        for(Opportunity_Site__c site : siteToUpdateWon){
            for(Opportunity opp : oppToUpdate){
                if(site.Opportunity__c == opp.Id){
                        if(string.isEmpty(opp.NSSales_Site_Won__c)){
                            opp.NSSales_Site_Won__c =  site.NSSales_Site_Name__c;
                        }
                        else{
                            opp.NSSales_Site_Won__c = opp.NSSales_Site_Won__c +';'+ site.NSSales_Site_Name__c;
                        }
                        oppSiteNameUpdate.add(opp);
                    }         
                }
            }
            update oppSiteNameUpdate;
        for(Opportunity_Site__c site : siteToUpdateLost){
            for(Opportunity opp : oppToUpdate){
                if(site.Opportunity__c == opp.Id){
                        if(string.isEmpty(opp.NSSales_Site_Lost__c)){
                            opp.NSSales_Site_Lost__c =  site.NSSales_Site_Name__c;
                        }
                        else{
                            opp.NSSales_Site_Lost__c = opp.NSSales_Site_Lost__c +';'+ site.NSSales_Site_Name__c;
                        }
                        oppSiteNameUpdateLost.add(opp);
                    }         
                }
            }
       update oppSiteNameUpdateLost;
     }
    }