force-app/main/default/objects/Opportunity/fields/NSSales_609_1_FSManagerApprovalOwner__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_FSManagerApprovalOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>609.1 Field Sales Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_IDManagerApprovalOwner__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_IDManagerApprovalOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>609.1 Industrial Development Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSSales_609_1_SwitchRemovalRequest__c.field-meta.xml
<CustomField>
    <fullName>NSSales_609_1_SwitchRemovalRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of Req#3332</description>
    <label>609.1 Switch Removal Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/NS_General_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>NS_General_Opportunity</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>General Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/NSSales_609_1.recordType-meta.xml
<RecordType>
    <fullName>NSSales_609_1</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>Sales</description>
    <label>609.1</label>
</RecordType>

force-app/main/default/classes/NSSales_ApprovalHistoryControllerTest.cls
@istest
public class NSSales_ApprovalHistoryControllerTest {
    @istest
    public static void fetchOpportunityIdfromProcessInstanceStepTest(){
    	//Creating Admin User  
        Profile sysprof = UserTestFactory.createProfile(NS_StaticVariablesUtility.SystemAdministratorProfile);
        User admin = UserTestFactory.createUser(14,sysprof.Id);
        User atest;
        User btest;
        
         //Creating Sales manager test User  
        System.runAs( admin ){ 
            Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            atest = UserTestFactory.createUserSales(22,agent.Id);
            
        }
        System.runAs(admin){
            Profile agent = UserTestFactory.createProfile(NS_StaticVariablesUtility.SalesManager);
            btest = UserTestFactory.createUserSales(24,agent.Id);
        }
        system.debug('atest'+atest.id);
        system.debug('debug'+btest.id);
        
        system.test.StartTest();
        
        //Opportunity Creation
        Opportunity Opty = NSSales_OpportunityFactory.createOpportunityForHelper();
        
        opty.NSSales_609_1_SwitchRemovalRequest__c=true;
        update opty;
        opty.NSSales_609_1_IDManagerApprovalOwner__c=atest.id;
        opty.NSSales_609_1_FSManagerApprovalOwner__c=btest.id;
        opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NSSales_609_1').getRecordTypeId();
        update opty;
        system.assertNotEquals(null, atest.id);
        system.assertNotEquals(null, btest.id);
        NSSales_609_1_ApprovalProcessController.initiate_609_1_ApprovalProcess(opty.Id);
        List<ProcessInstanceWorkitem> p = [select id, ProcessInstanceId from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId = :opty.Id];
        List<ProcessInstanceStep> q = [select ProcessInstanceId from ProcessInstanceStep where ProcessInstance.TargetObjectId = :opty.Id];

        
        NSSales_ApprovalHistoryController.fetchHistory(opty.Id);
        NSSales_ApprovalHistoryController.fetchOpportunityIdfromProcessInstanceStep(q[0].id);
        system.assertNotEquals(null, p[0].id);
        system.assertNotEquals(null, q[0].id);
        NSSales_ApprovalHistoryController.getObjectRecordType(p[0].id);
        NSSales_ApprovalHistoryController.getObjectRecordType(q[0].id);
        NSSales_ApprovalHistoryController.getObjectRecordType(opty.Id);
        NSSales_ApprovalHistoryController.getObjectRecordType('');
        opty.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('NS_General_Opportunity').getRecordTypeId();
        update opty;
        NSSales_ApprovalHistoryController.getObjectRecordType(opty.Id);
        
    }

}