force-app/main/default/objects/Contact/fields/Notification_Delivery_Days__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Days__c</fullName>
    <description>contact notification subscription window days of the week preference</description>
    <label>Notification Delivery Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Days_of_the_week</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Hour_Ending__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Hour_Ending__c</fullName>
    <label>Notification Delivery Hour Ending</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Hour_Starting__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Hour_Starting__c</fullName>
    <description>ENS subscription window delivery hour starting</description>
    <label>Notification Delivery Hour Starting</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notification_Delivery_Window_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notification_Delivery_Window_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the contact has or has not subscribed to receive NS ENS notification.</description>
    <inlineHelpText>Whether the contact has or has not subscribed to receive NS ENS notification.</inlineHelpText>
    <label>Delivery Window Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Notifications_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Notifications_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks is contact has subscribed to receive notification in AccessNS.</description>
    <inlineHelpText>Check is contact has subscribed to receive notification in AccessNS.</inlineHelpText>
    <label>Notifications Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_RACF_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_RACF_ID__c</fullName>
    <label>RACF ID</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of ConnectNS contact who subscribed to a notification.</description>
    <inlineHelpText>Name of ConnectNS contact who subscribed to a notification.</inlineHelpText>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notifications_Captured</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Customer_Alert_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Alert_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Customer Alert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Deliver_Now__c.field-meta.xml
<CustomField>
    <fullName>Deliver_Now__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliver Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Empty_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Empty_Indicator__c</fullName>
    <description>Load vs empty status indicator</description>
    <inlineHelpText>Load vs empty status indicator</inlineHelpText>
    <label>Empty Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/ENS_Message_Payload__c.field-meta.xml
<CustomField>
    <fullName>ENS_Message_Payload__c</fullName>
    <description>ENS notification message payload field content, unparsed</description>
    <label>ENS Message Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Equipment_Number__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Number__c</fullName>
    <description>Car ID for No Bill notification</description>
    <inlineHelpText>The single equipment number that is impacted in the event</inlineHelpText>
    <label>Equipment Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Est_Service_Window_From__c.field-meta.xml
<CustomField>
    <fullName>Est_Service_Window_From__c</fullName>
    <description>Train details captured from notification.</description>
    <inlineHelpText>Train details captured from notification.</inlineHelpText>
    <label>Est Service Window - From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Est_Service_Window_To__c.field-meta.xml
<CustomField>
    <fullName>Est_Service_Window_To__c</fullName>
    <description>Train details captured from notification.</description>
    <inlineHelpText>Train details captured from notification.</inlineHelpText>
    <label>Est Service Window – To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Event Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/isInternalUser__c.field-meta.xml
<CustomField>
    <fullName>isInternalUser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>whether the receiver is an internal norfolk southern employee</description>
    <label>is Internal User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Location_City__c.field-meta.xml
<CustomField>
    <fullName>Location_City__c</fullName>
    <description>Bad Order notification field.</description>
    <label>Location City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Location_ClassCode__c.field-meta.xml
<CustomField>
    <fullName>Location_ClassCode__c</fullName>
    <description>TYES location class code value</description>
    <inlineHelpText>TYES location class code value</inlineHelpText>
    <label>Location ClassCode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Location_State__c.field-meta.xml
<CustomField>
    <fullName>Location_State__c</fullName>
    <description>Bad Order notification field</description>
    <label>Location State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/LS_Place_Cars_Detail__c.field-meta.xml
<CustomField>
    <fullName>LS_Place_Cars_Detail__c</fullName>
    <description>local service planned placed cars detail table html string</description>
    <label>Place Cars Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/LS_PlacedCars_Updated_Detail__c.field-meta.xml
<CustomField>
    <fullName>LS_PlacedCars_Updated_Detail__c</fullName>
    <label>LS Place Updated Car Details</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/LS_Pull_Cars_Detail__c.field-meta.xml
<CustomField>
    <fullName>LS_Pull_Cars_Detail__c</fullName>
    <description>local service planned pulled cars detail table html string</description>
    <label>Pull Cars Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <description>SMS/Push, message details populated by MC.</description>
    <inlineHelpText>SMS/Push, message details populated by MC.</inlineHelpText>
    <label>Notification Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/RACF_Id__c.field-meta.xml
<CustomField>
    <fullName>RACF_Id__c</fullName>
    <description>subscriber NS RACF Id</description>
    <label>RACF Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Total_Cars_to_Place__c.field-meta.xml
<CustomField>
    <fullName>Total_Cars_to_Place__c</fullName>
    <description>Number of cars to place from notification.</description>
    <inlineHelpText>Number of cars to place from notification.</inlineHelpText>
    <label>Total Cars to Place</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Total_Cars_to_Pull__c.field-meta.xml
<CustomField>
    <fullName>Total_Cars_to_Pull__c</fullName>
    <description>Number of cars pulled from notification.</description>
    <inlineHelpText>Number of cars pulled from notification.</inlineHelpText>
    <label>Total Cars to Pull</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Train_Departed_Time__c.field-meta.xml
<CustomField>
    <fullName>Train_Departed_Time__c</fullName>
    <description>What date and time did the Local Service In-Transit train depart.</description>
    <inlineHelpText>What date and time did the Local Service In-Transit train depa</inlineHelpText>
    <label>Train Departed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notification_Logs_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/recordTypes/Notification_Log.recordType-meta.xml
<RecordType>
    <fullName>Notification_Log</fullName>
    <active>true</active>
    <description>enterprise notification system message log</description>
    <label>Notification Log</label>
</RecordType>

force-app/main/default/globalValueSets/Days_of_the_week.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MON</fullName>
    </customValue>
    <customValue>
        <fullName>TUE</fullName>
    </customValue>
    <customValue>
        <fullName>WED</fullName>
    </customValue>
    <customValue>
        <fullName>THU</fullName>
    </customValue>
    <customValue>
        <fullName>FRI</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>SUN</fullName>
    </customValue>
    <description>days of the week 3 letter abbreviation</description>
    <masterLabel>Days of the week</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NS_LocalServiceNotification.cls
public class NS_LocalServiceNotification {
   /*
	// Note: classname only specified local service events due to release timing (ENS 1st release), 
	// it is the main entry class to branch to handling of all ENS events
	*/
     
    public Static Final String evPlanned = 'PLANNED';
    public Static Final String evAdvisory = 'SVC_ADVISORY';
    public Static Final String evTransit = 'IN_TRANSIT';
    public Static Final String evOverload = 'OVERLOAD';
    public Static Final String evEta = 'ETACHANGE';
    public Static Final String evNobill = 'NOBILL';
    public Static Final String Pull = 'PULL';
    public Static Final String Plce = 'PLCE';
    
    public static void invokeNotificationInsert(List<Notification_Log__c> notifyList){
        
        System.debug('notifyList' +notifyList);
        List<String> notifyRacfId = new List<String>();
        List<String> notifyContactRacfId = new List<String>();
        List<String> notifyUserRacfId = new List<String>();
        Map<String,User> matchingUser = new Map<String,User>();
        Map<String,Contact> matchingContact = new Map<String,Contact>();
        String notificationDays;
        String notifyStartTime;
        String notifyEndTime;
        Integer intNotifyStartTime;
        Integer intNotifyEndTime;
        String ensPayload;
        Boolean notifyEnabled;
        Boolean notifyWindowEnabled;
        Boolean executeResponse = false;
        
        //compile list of racf where notification events shall be sent to Contact 
        for(Notification_Log__c notify : notifyList)
        {
            if (notify.isInternalUser__c)
            {
                notifyUserRacfId.add(notify.RACF_Id__c);
            }else
            {
                notifyContactRacfId.add(notify.RACF_Id__c);
            }
        }        
        
        for(User usr : [Select id,FederationIdentifier from User where FederationIdentifier =:notifyUserRacfId])
        {
            matchingUser.put(usr.FederationIdentifier,usr);
        }
        for(Contact con : [Select id,NS_RACF_ID__c,Notifications_Enabled__c,Notification_Delivery_Days__c,
                           Notification_Delivery_Hour_Starting__c,Notification_Delivery_Hour_Ending__c,
                           Notification_Delivery_Window_Enabled__c from Contact where NS_RACF_ID__c =:notifyContactRacfId])
        {
            matchingContact.put(con.NS_RACF_ID__c,con);
        }
        
        String createdDayofWk =System.now().format('EEE').toUpperCase();
        String createdTime =System.now().format('HHmm');
        Integer intcreatedTime = Integer.valueOf(createdTime);
        
        for(Notification_Log__c notification : notifyList)
        {
            ensPayload = notification.ENS_Message_Payload__c;
            //2.5, jlong, append country code to phone number for MC sms
            system.debug('input cell=' + notification.Cell_Phone__c);
            if (notification.Cell_Phone__c != null || ''.equalsIgnoreCase(notification.Cell_Phone__c) ){
                notification.Cell_Phone__c = '1' + notification.Cell_Phone__c;
            } 
            //populate notification_msg__c field value
            if((evPlanned.equalsIgnoreCase(notification.Event_Name__c)))
            {
                notification.Notification_Message__c =notification.Customer_Alert_Name__c
                    +' - Plan to place '+Integer.valueOf(notification.Total_Cars_to_Place__c)
                    +' cars and pull '+Integer.valueOf(notification.Total_Cars_to_Pull__c)
                    +'. Estimated window '+notification.Est_Service_Window_From__c.format()
                    +' - '+notification.Est_Service_Window_To__c.format()+' EST.';
            } else if((evAdvisory.equalsIgnoreCase(notification.Event_Name__c)))
            {
                notification.Notification_Message__c =notification.Customer_Alert_Name__c
                    +' - '+Integer.valueOf(notification.Total_Cars_to_Place__c)
                    +' cars were not placed and '
                    +Integer.valueOf(notification.Total_Cars_to_Pull__c)
                    +' were not pulled. Incomplete work will be attempted during next service window.';
            } else if((evTransit.equalsIgnoreCase(notification.Event_Name__c))){
                notification.Notification_Message__c =notification.Customer_Alert_Name__c
                    +' - Train Departed '+notification.Train_Departed_Time__c.format()
                    +' EST with  '+ Integer.valueOf(notification.Total_Cars_to_Place__c)
                    +' place cars. Plan to pull '+ Integer.valueOf(notification.Total_Cars_to_Pull__c)+' cars.';
            } else if((evNobill.equalsIgnoreCase(notification.Event_Name__c)))
            {
                notification.Notification_Message__c =notification.Customer_Alert_Name__c
                    +' - ' +notification.Equipment_Number__c
                    +' was pulled from '  +notification.Location_ClassCode__c +' '
                    +notification.Empty_Indicator__c +' '
                    +notification.Location_City__c +',' +notification.Location_State__c
                    +' without proper forwarding instructions.';
            }
			
            //for notification to internal NS users, set Notification_Log.User field based on RACF ID       
            if(notification.RACF_Id__c != null && notification.isInternalUser__c ==true){
                if(!matchingUser.isEmpty()){
                    notification.User__c = matchingUser.get(notification.RACF_Id__c).Id;
                    notification.OwnerId = matchingUser.get(notification.RACF_Id__c).Id;
                }
                //always process notification to internal user
                notification.Deliver_Now__c = True;
            } else if(notification.RACF_Id__c != null && notification.isInternalUser__c ==false)
			{//for notification to external customers, set Notification_Log.Contact field based on RACF ID
                if(!matchingContact.isEmpty()){
                    notification.Contact_Name__c = matchingContact.get(notification.RACF_Id__c).Id;
                    notificationDays =matchingContact.get(notification.RACF_Id__c).Notification_Delivery_Days__c;
                    notifyEnabled = matchingContact.get(notification.RACF_Id__c).Notifications_Enabled__c;
                    notifyWindowEnabled = matchingContact.get(notification.RACF_Id__c).Notification_Delivery_Window_Enabled__c;
                    notifyStartTime = matchingContact.get(notification.RACF_Id__c).Notification_Delivery_Hour_Starting__c;
                    notifyEndTime = matchingContact.get(notification.RACF_Id__c).Notification_Delivery_Hour_Ending__c;

                    System.debug('DayOfWeek =' + createdDayofWk + '; CurrentHrMin=' + createdTime+ 
                     ';deliveryDays=' +notificationDays +';notifyStartTime=' +notifyStartTime + ' ;notifyEndTime=' +notifyEndTime
                    );

                    if(!(''.equalsIgnoreCase(notifyStartTime)) && !(''.equalsIgnoreCase(notifyEndTime))
                      && notifyStartTime != null && notifyEndTime != null){
                        intNotifyStartTime = Integer.valueOf(notifyStartTime.trim());
                        intNotifyEndTime = Integer.valueOf(notifyEndTime.trim());

                        //set flag whether to process or discard notify msg based on contact delivery window set in AccessNS
                        if(notifyWindowEnabled == false) {                
                            //10.25, jlong, AccessNS does not currently set notification enabled field, remove from delivery condition
                            //if((notification.isInternalUser__c == false && notifyEnabled == true && notifyWindowEnabled == false) || notification.isInternalUser__c == true) {                
                            notification.Deliver_Now__c = True;
                        }
                        else {
                            if( !(''.equalsIgnoreCase(notificationDays)) && notificationDays.contains(createdDayofWk)){
                                //11.9, jlong, temp update set 2400 as 0 for AccessNS notify window start time bug,
                                if (intNotifyStartTime >= 2400){
                                    intNotifyStartTime = 0;                                
                                } 
                                // user notify start time in PM and end in AM
                                if (intNotifyStartTime >= 1200 && intNotifyEndTime < 1200){
                                    System.debug('...PM-AM, enter start time in PM and end in AM ');
                                     if (! (intNotifyEndTime < intcreatedTime && intNotifyStartTime > intcreatedTime)){
                                        System.debug('...PM-AM, current time greater than endtime, less than starttime...'); 
                                        notification.Deliver_Now__c = True;
                                    } 
                                } else{
                                    if (intNotifyStartTime <= intcreatedTime && intNotifyEndTime >= intcreatedTime){
                                        notification.Deliver_Now__c = True;
                                    }                                    
                                }
                            }
                        }
                    }
                }
                
            }
            
            if((evPlanned.equalsIgnoreCase(notification.Event_Name__c) || evAdvisory.equalsIgnoreCase(notification.Event_Name__c) || evTransit.equalsIgnoreCase(notification.Event_Name__c))){
                responseParser(ensPayload,notification);
            }
            else if(evOverload.equalsIgnoreCase(notification.Event_Name__c)){
                ENS_OverloadedNotification.overloadedResponseParser(ensPayload,notification);
            }
            else if(evEta.equalsIgnoreCase(notification.Event_Name__c)){
                ENS_ETANotification.etaResponseParser(ensPayload,notification);
            }
        }
    }
    
    public static void responseParser(String rawResponse,Notification_Log__c notificationList){
        
        System.debug('rawResponse' +rawResponse);
        if(rawResponse != null){
            NS_LocalServicePayloadWrapper wrapperList = (NS_LocalServicePayloadWrapper)JSON.deserialize(rawResponse,NS_LocalServicePayloadWrapper.class);
            
            Boolean placeCarFlag = false;
            Boolean pullCarFlag = false;
            Integer placeCarCount = 0;
            Integer placePrevCount;
            Integer pullCarCount = 0;
            Integer pullCarPrevCount;
            String jsonResponsePlaceSub;
            String jsonResponsePullSub;
            String jsonResponsePlace = '{"eqdtl":[{';
            String jsonResponsePull = '{"eqdtl":[{';

            Boolean plcUpdatedFlag=false;
            Integer plcUpdatedCount = 0;
            Integer plcUpdatedPrevCount;
            String jsonResponsePlaceUpdatedSub;
            String jsonResponsePlaceUpdated = '{"eqdtl":[{';
            
            for(NS_LocalServicePayloadWrapper.Eqdtl objt :wrapperList.Eqdtls.eqdtl){
                
                if(objt.action =='PLCE' && !('Y'.equalsIgnoreCase(objt.equpdatedind)) && placeCarCount < 3998){

                    placePrevCount  = jsonResponsePlace.length();
                    if (placeCarFlag== true)
                    {
                        jsonResponsePlace+=',{';
                    }
                    jsonResponsePlace+= '"eqinit":"'+objt.eqinit
                        +'","eqnr":"'+objt.eqnr
                        +'","wbsernr":"'+objt.wbsernr
                        +'","emptyind":"'+objt.emptyind
                        +'","cartype":"'+objt.cartype
                        +'","classcd":"'+objt.classcd
                        +'","commodity":"'+objt.commodity
                        +'","stcc":"'+objt.stcc
                        +'","wgt":"'+objt.wgt
                        +'","rlsereqtype":"'+objt.rlsereqtype
                        +'","totk":"'+objt.totk
                        +'","tospot":"'+objt.tospot
                        +'","eqloparsn":"'+objt.eqloparsn+'"}';                    
                    placeCarFlag = true;
                    placeCarCount =jsonResponsePlace.length();
                    
                }

                if(objt.action =='PLCE' && 'Y'.equalsIgnoreCase(objt.equpdatedind) && plcUpdatedCount < 3998){
                    plcUpdatedPrevCount  = jsonResponsePlaceUpdated.length();
                    if (plcUpdatedFlag == true)
                    {
                        jsonResponsePlaceUpdated+=',{';
                    }
                    jsonResponsePlaceUpdated+= '"eqinit":"'+objt.eqinit
                        +'","eqnr":"'+objt.eqnr
                        +'","wbsernr":"'+objt.wbsernr
                        +'","emptyind":"'+objt.emptyind
                        +'","cartype":"'+objt.cartype
                        +'","classcd":"'+objt.classcd
                        +'","commodity":"'+objt.commodity
                        +'","stcc":"'+objt.stcc
                        +'","wgt":"'+objt.wgt
                        +'","rlsereqtype":"'+objt.rlsereqtype
                        +'","totk":"'+objt.totk
                        +'","tospot":"'+objt.tospot
                        +'","eqloparsn":"'+objt.eqloparsn+'"}';                    
                    plcUpdatedFlag = true;
                    plcUpdatedCount =jsonResponsePlaceUpdated.length();                    
                }

                if(objt.action =='PULL' && pullCarCount < 3998){
                    pullCarPrevCount  = jsonResponsePull.length();
                    if (pullCarFlag== true)
                    {
                        jsonResponsePull+=',{';
                    }
                    jsonResponsePull+= '"eqinit":"'+objt.eqinit
                        +'","eqnr":"'+objt.eqnr
                        +'","wbsernr":"'+objt.wbsernr
                        +'","emptyind":"'+objt.emptyind
                        +'","cartype":"'+objt.cartype
                        +'","classcd":"'+objt.classcd
                        +'","commodity":"'+objt.commodity
                        +'","stcc":"'+objt.stcc
                        +'","wgt":"'+objt.wgt
                        +'","rlsereqtype":"'+objt.rlsereqtype
                        +'","fromtk":"'+objt.fromtk
                        +'","fromspot":"'+objt.fromspot
                        +'","eqloparsn":"'+objt.eqloparsn+'"}';
                    pullCarFlag= true;
                    pullCarCount =jsonResponsePull.length();    
                }
            }     
            
            // Place Car Details for 4000 character  
            if(placeCarCount > 4000){
                system.debug('Inside Count' +placeCarCount);
                jsonResponsePlaceSub = jsonResponsePlace.substring(0, placePrevCount);
                
            }
            else{
                jsonResponsePlaceSub = jsonResponsePlace.substring(0, placeCarCount);
            }
            // Updated Place Car Details for 4000 character  
            if(plcUpdatedCount > 4000){
                jsonResponsePlaceUpdatedSub = jsonResponsePlaceUpdated.substring(0, plcUpdatedPrevCount);
                
            }
            else{
                jsonResponsePlaceUpdatedSub = jsonResponsePlaceUpdated.substring(0, plcUpdatedCount);
            }            
            // Pull Car Details for 4000 character     
            if(pullCarCount > 4000){
                system.debug('Inside Count' +pullCarCount);
                jsonResponsePullSub = jsonResponsePull.substring(0, pullCarPrevCount);
                
            }
            else{
                jsonResponsePullSub = jsonResponsePull.substring(0, pullCarCount);
            }
            //If there is no Place Car Details, then display blank.    
            if(placeCarCount == 0){
                jsonResponsePlaceSub+='';
            }
            else{
                jsonResponsePlaceSub+=']}';
            }
            //If there is no Updated Place Car Details, then display blank.    
            if(plcUpdatedCount == 0){
                jsonResponsePlaceUpdatedSub+='';
            }
            else{
                jsonResponsePlaceUpdatedSub+=']}';
            }            
            //If there is no Pull Car Details, then display blank.  
            if(pullCarCount == 0){
                jsonResponsePullSub+='';  
            }
            else{
                jsonResponsePullSub+=']}';
            }
            
            notificationList.LS_Place_Cars_Detail__c = jsonResponsePlaceSub.replace('null', '-');
            notificationList.LS_Pull_Cars_Detail__c = jsonResponsePullSub.replace('null', '-');
            notificationList.LS_PlacedCars_Updated_Detail__c = jsonResponsePlaceUpdatedSub.replace('null', '-');
            
        } 
    }
    
}