force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/NSSales_MarketingManagerAssignmentLog__c.object-meta.xml
<CustomObject>
    <description>This object captures the history of Marketing Manager Assignment object</description>
    <label>Marketing Manager Assignment Log</label>
    <nameField>
        <displayFormat>MMLog-{0}</displayFormat>
        <label>Marketing Manager Assignment Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Manager Assignment Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the account name of the record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Manager Assignment Logs</relationshipLabel>
    <relationshipName>Marketing_Manager_Assignment_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_Action__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Action__c</fullName>
    <description>It stores the action(create/edit/delete) taken on any record</description>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>NSSales_BusinessUnit__c</fullName>
    <description>It stores the related marketing manager&#39;s Business Unit</description>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_ChangeDate__c.field-meta.xml
<CustomField>
    <fullName>NSSales_ChangeDate__c</fullName>
    <description>It captures the create date/change date of the record</description>
    <label>Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_MarketingManager__c.field-meta.xml
<CustomField>
    <fullName>NSSales_MarketingManager__c</fullName>
    <description>It stores the Marketing Manager user name of the record</description>
    <label>Marketing Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_NewValue__c.field-meta.xml
<CustomField>
    <fullName>NSSales_NewValue__c</fullName>
    <description>It stores the new value of any changed record</description>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_OldValue__c.field-meta.xml
<CustomField>
    <fullName>NSSales_OldValue__c</fullName>
    <description>It stores the old value of any changed record</description>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSSales_MarketingManagerAssignmentLog__c/fields/NSSales_Role__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Role__c</fullName>
    <description>It stores the role of the Marketing Manager</description>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NSSales_MrktMngrAssgnmntLogsController.cls
/**@author  Accenture
* @Created Date Oct,2019
* @version  1.0
* @description This class contains Server side controller for Marketing Manager Assignment Log functionalities 
*/ 
public class NSSales_MrktMngrAssgnmntLogsController {

    @AuraEnabled
     public static List <NSSales_MarketingManagerAssignmentLog__c> getMarketingManagerAssignmentLog(String accountId) {
         return [SELECT NSSales_Account__c, 
                 NSSales_MarketingManager__c,
                 NSSales_Role__c,
               //  NSSales_AssociatedBusinessUnit__c,
                 NSSales_BusinessUnit__c,
                 NSSales_Action__c,
                 NSSales_OldValue__c,
                 NSSales_NewValue__c,
                 NSSales_ChangeDate__c,
                 CreatedBy.Name
                 FROM NSSales_MarketingManagerAssignmentLog__c
                 WHERE NSSales_Account__c = :accountId
                 ORDER BY createdDate DESC];
     }
}