force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/Customer_Alert_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Alert_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Customer Alert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <description>Date and Time and event was sent from Marketing Cloud.</description>
    <inlineHelpText>Date and Time and event was sent from Marketing Cloud.</inlineHelpText>
    <label>Event Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Event Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_SubType__c.field-meta.xml
<CustomField>
    <fullName>Event_SubType__c</fullName>
    <description>Used for events with additional subtype to differentiate notification message content</description>
    <inlineHelpText>Used for events with additional subtype to differentiate notification message content</inlineHelpText>
    <label>Event SubType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Overload_Cars_Detail__c.field-meta.xml
<CustomField>
    <fullName>Overload_Cars_Detail__c</fullName>
    <description>overload event impacted equipment/cars detail information</description>
    <inlineHelpText>overload event impacted equipment/cars detail information</inlineHelpText>
    <label>Overload Cars Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NS_ENSOverloadEmailTemplate.cls
public with sharing class NS_ENSOverloadEmailTemplate {
    
    public List<overloadCar> overloadCarDtl { get; set; }
    public String EventSubType;
    public String CustomerName;
    
    public Id notifyId;
	public Id getnotifyId(){
          return notifyId;           
    }
    public void setnotifyId(Id notify){
		notifyId = notify;
		NS_Parse();
	}
    public String getEventSubType(){
  		return EventSubType;
 	}
 	public void setEventSubType(String evtSubType){
  		this.EventSubType = evtSubType;
 	}
     public String getCustomerName(){
  		return CustomerName;
 	}
 	public void setCustomerName(String CustomerName){
  		this.CustomerName = CustomerName;
 	}
    
    public  NS_ENSOverloadEmailTemplate()
    {   
    }
    
    Public void NS_Parse(){
        
        List<Notification_Log__c> carList = [SELECT Customer_Alert_Name__c,Overload_Cars_Detail__c,Event_SubType__c,Event_Name__c,Event_Date_Time__c FROM Notification_Log__c WHERE Id =: notifyId];
        
        String overloadCar = carList[0].Overload_Cars_Detail__c;
        String evtSubType = carList[0].Event_SubType__c;
        String CustomerName = carList[0].Customer_Alert_Name__c;
        
        setEventSubType(evtSubType);
        setCustomerName(CustomerName);
        
        if(overloadCar !=null){
            Integer placeLength = overloadCar.length() - 1;
        	String placeString = overloadCar.substring(9,placeLength);
          overloadCarDtl = (List<overloadCar>) System.JSON.deserialize(placeString, List<overloadCar>.class);  
        }        
    }
    
    public class overloadCar{
        public String eqids{get;set;}
		public String origloc{get;set;}
		public String shipper{get;set;}
		public String lastevent{get;set;}
        public String lasteventtime{get;set;}
        public String lasteventloc{get;set;}             
		public String scalewtgrs;
		public String umltotalwt;
        
        public String getScalewtgrs(){
            if (''.equalsIgnoreCase(scalewtgrs.trim()) || '-'.equalsIgnoreCase(scalewtgrs.trim()) ){
                return '-';
            } else{
            	return Decimal.valueOf(scalewtgrs).toPlainString();
            }            
        }
        public void setScalewtgrs(String ipScalewtgrs){
            this.scalewtgrs = ipScalewtgrs;            
        }
        public String getUmltotalwt(){
            if (''.equalsIgnoreCase(umltotalwt.trim()) || '-'.equalsIgnoreCase(umltotalwt.trim()) ){
                return '-';
            } else{
            	return Decimal.valueOf(umltotalwt).toPlainString();
            }
        }
        public void setUmltotalwt(String ipUmltotalwt){
            this.umltotalwt = ipUmltotalwt;
        }        
    }

}