force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/ETA_Car_Detail__c.field-meta.xml
<CustomField>
    <fullName>ETA_Car_Detail__c</fullName>
    <description>ETA change impacted car/equipment details</description>
    <inlineHelpText>ETA change impacted car/equipment details</inlineHelpText>
    <label>ETA Car Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_Time__c</fullName>
    <description>Date and Time and event was sent from Marketing Cloud.</description>
    <inlineHelpText>Date and Time and event was sent from Marketing Cloud.</inlineHelpText>
    <label>Event Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Event Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Total_Cars_Impacted__c.field-meta.xml
<CustomField>
    <fullName>Total_Cars_Impacted__c</fullName>
    <description>total number of cars (equipment) impacted in the event</description>
    <inlineHelpText>Total number of cars (equipment) impacted in the event</inlineHelpText>
    <label>Number of Cars Impacted</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NS_ENSETAEmailTemplate.cls
public with sharing class NS_ENSETAEmailTemplate {
    
    public List<etaCar> etaCarDtl { get; set; }
    public Decimal EtaCarNumber;
    public DateTime EventDate;
    
    public Id notifyId;
	public Id getnotifyId(){
          return notifyId;           
    }
    public void setnotifyId(Id notify){
		notifyId = notify;
		NS_Parse();
	}
    public Decimal getEtaCarNumber(){
  		return EtaCarNumber;
 	}
 	public void setEtaCarNumber(Decimal EtaCarNumber){
  		this.EtaCarNumber = EtaCarNumber;
 	}
    public DateTime getEventDate(){
  		return EventDate;
 	}
 	public void setEventDate(DateTime EventDate){
  		this.EventDate = EventDate;
 	}
    
    public  NS_ENSETAEmailTemplate()
    {   
    }
    
    Public void NS_Parse(){
        
        List<Notification_Log__c> carList = [SELECT  ETA_Car_Detail__c,Total_Cars_Impacted__c,Event_Name__c,Event_Date_Time__c FROM Notification_Log__c WHERE Id =: notifyId];
        
        String etachangeCar = carList[0].ETA_Car_Detail__c;
        Decimal EtaCarNumber = carList[0].Total_Cars_Impacted__c;
        DateTime EventDate = carList[0].Event_Date_Time__c;
        
        setEtaCarNumber(EtaCarNumber);
        setEventDate(EventDate);
        
        if(etachangeCar !=null){
            Integer placeLength = etachangeCar.length() - 1;
        	String placeString = etachangeCar.substring(9,placeLength);
          etaCarDtl = (List<etaCar>) System.JSON.deserialize(placeString, List<etaCar>.class);  
        }
        
    }
    
 public class etaCar{

        public String eqids{get;set;}
		public String acctloc{get;set;}
		public String lastevent{get;set;}
		public String lasteventtime{get;set;}
		public String lasteventloc{get;set;}
		public String delaydesc{get;set;}
		public String neweta{get;set;}
        public String oldeta{get;set;}
        public String emptyStat{get;set;}
        public String stcc{get;set;}
     
             
    }
}