force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/Customer_Alert_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Alert_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Customer Alert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Equipment_Number__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Number__c</fullName>
    <description>Car ID for No Bill notification</description>
    <inlineHelpText>The single equipment number that is impacted in the event</inlineHelpText>
    <label>Equipment Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/ETA_Car_Detail__c.field-meta.xml
<CustomField>
    <fullName>ETA_Car_Detail__c</fullName>
    <description>ETA change impacted car/equipment details</description>
    <inlineHelpText>ETA change impacted car/equipment details</inlineHelpText>
    <label>ETA Car Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <description>SMS/Push, message details populated by MC.</description>
    <inlineHelpText>SMS/Push, message details populated by MC.</inlineHelpText>
    <label>Notification Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Total_Cars_Impacted__c.field-meta.xml
<CustomField>
    <fullName>Total_Cars_Impacted__c</fullName>
    <description>total number of cars (equipment) impacted in the event</description>
    <inlineHelpText>Total number of cars (equipment) impacted in the event</inlineHelpText>
    <label>Number of Cars Impacted</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ENS_ETANotification.cls
public class ENS_ETANotification {
    
    public static void etaResponseParser(String rawResponse,Notification_Log__c recNotificationLog){
        if(rawResponse != null){
            
            ENS_ETAWrapper wrapperList = (ENS_ETAWrapper)JSON.deserialize(rawResponse,ENS_ETAWrapper.class);
            
            Boolean etaFlag = false;    
            String etaJson = '{"eqdtl":[{';
            String etaJsonSub;   
            Integer count = 0;
            Integer prevCount;

            // construct notification_message for multi cars/equipments event
            if (recNotificationLog.Total_Cars_Impacted__c >1){
                recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c
                    +' - '+ Integer.valueOf(recNotificationLog.Total_Cars_Impacted__c)
                    +' shipments have been rescheduled.';                 
            }            
            for(ENS_ETAWrapper.Equipment objt :wrapperList.EquipmentList.Equipment){
                if(count < 3998){
                    prevCount  = etaJson.length();
                    if (etaFlag== true)
                    {
                        etaJson+=',{';
                    }
                    etaJson+= '"eqids":"'+objt.EquipmentNumber
                        +'","acctloc":"'+objt.Locations.Location[0].AcctLocCity + ',' + objt.Locations.Location[0].AcctLocState 
                        +'","lastevent":"'+objt.LastEventDescription
                        +'","lasteventtime":"'+Datetime.valueOf(objt.LastEventTime.replace('T', ' ')).format()+' EST'
                        +'","lasteventloc":"'+objt.LastEvtCity+','+objt.LastEvtState
                        +'","delaydesc":"'+objt.DelayDescription
                        // change wrapper once source field name for old eta is provided
                        +'","oldeta":"'+ Datetime.valueOf(objt.PriorETA.replace('T', ' ')).format() +' EST'  
                        +'","neweta":"'+Datetime.valueOf(objt.NewETA.replace('T', ' ')).format()+' EST'
                        +'","emptyStat":"'+objt.LoadEmptyStatus
                        +'","stcc":"'+objt.Commodity                        
                        +'"}';                    
                    etaFlag = true;
                    count =etaJson.length();
                }
                // construct notification_message for 1 car/equipment event
                if (recNotificationLog.Total_Cars_Impacted__c ==1){
                    recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c
                        +' - '+ objt.EquipmentNumber
                        +' is rescheduled to ' + Datetime.valueOf(objt.NewETA.replace('T', ' ')).format()+' EST.';
                    recNotificationLog.Equipment_Number__c =objt.EquipmentNumber;
                }
                
            }          
            if(count > 4000){
                system.debug('Inside Count' +count);
                etaJsonSub = etaJson.substring(0, prevCount);
                
            }else{
                etaJsonSub = etaJson.substring(0, count);
            }
            
            if(count == 0){
                etaJsonSub+='';
            }
            else{
                etaJsonSub+=']}';
            }
            
            recNotificationLog.ETA_Car_Detail__c = etaJsonSub.replace('null', '-');
            
        }
    }
}