force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/ENS_Message_Payload__c.field-meta.xml
<CustomField>
    <fullName>ENS_Message_Payload__c</fullName>
    <description>ENS notification message payload field content, unparsed</description>
    <label>ENS Message Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NS_LocalServicePayloadWrapperTest.cls
@isTest(SeeAllData=false)
private class NS_LocalServicePayloadWrapperTest {
    static testmethod void testNotificationInsert(){
        Notification_Log__c notifi = new Notification_Log__c();
        notifi.ENS_Message_Payload__c='{"eventtype":"PLANNED",'
            +'"eventdesc":"Local Service Planned",'
            +'"custclasscd":"H11",'
            +'"eqdtls":'
            +'{"eqdtl":'
            +'[{"action":"PLCE",'
            +'"eqinit":"BKTY",'
            +'"eqnr":"0000152146",'
            +'"wbsernr":"6460642492",'
            +'"emptyind":"L",'
            +'"cartype":"BOXCAR",'
            +'"classcd":"H11",'
            +'"commodity":"PPBRD",'
            +'"stcc":"2631117",'
            +'"wgt":"91",'
            +'"rlsereqtype":null,'
            +'"fromtk":null,'
            +'"fromspot":"0",'
            +'"totk":null,'
            +'"tospot":"0",'
            +'"eqloparsn":"test lopa"}]}}';
        insert notifi;  
        Test.startTest();
        NS_LocalServicePayloadWrapper.Eqdtl  abc=new NS_LocalServicePayloadWrapper.Eqdtl();
        abc.action='PLCE';
        abc.eqinit='BKTY';
        abc.eqnr='0000152146';
        abc.wbsernr='6460642492';
        abc.emptyind='L';
        abc.cartype='BOXCAR';
        abc.classcd='H11';
        abc.commodity='PPBRD';
        abc.stcc='2631117';
        abc.wgt='91';
        abc.fromspot='0';
        abc.fromtk='null';
        abc.tospot='1';
        abc.totk='2';
        abc.rlsereqtype='null';
        abc.eqloparsn='null'; 
        Test.stopTest();
        System.debug('abc.eqloparsn:'+ abc.eqloparsn );
        
    }
}