force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/Contact_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Display_Name__c</fullName>
    <description>notification subscriber display name</description>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Event Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ENS_BatchToDeleteNotificationTest.cls
@istest(SeeAllData=false)
public class ENS_BatchToDeleteNotificationTest {
    static testMethod void testMethod1()
    {
        Test.startTest();
        //List<Notification_Log__c> Notif = new List<Notification_Log__c>();
        ENS_BatchToDeleteNotification BC=new ENS_BatchToDeleteNotification();
        Notification_Log__c n1 = new Notification_Log__c();
        n1.Contact_Display_Name__c='XYZ';
        n1.Event_Name__c='BatchDelTest';
        Datetime dt = DateTime.parse('09/25/2019 11:46 AM');
        n1.CreatedDate=dt;
        insert n1;
        List<Notification_Log__c> alist=[SELECT ID,CreatedDate FROM Notification_Log__c where CreatedDate < LAST_N_DAYS:14];
        DataBase.executeBatch(BC,200);
        Test.stopTest();
        
    }

}