force-app/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <description>ENS notification message log which track subscriber details from Marketing Cloud.</description>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NFL{0000000000}</displayFormat>
        <label>Notification Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Log__c/fields/Customer_Alert_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Alert_Name__c</fullName>
    <description>The name the subscriber gives to the subscription.</description>
    <inlineHelpText>The name the subscriber gives to the subscription.</inlineHelpText>
    <label>Customer Alert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Equipment_Number__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Number__c</fullName>
    <description>Car ID for No Bill notification</description>
    <inlineHelpText>The single equipment number that is impacted in the event</inlineHelpText>
    <label>Equipment Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Event_SubType__c.field-meta.xml
<CustomField>
    <fullName>Event_SubType__c</fullName>
    <description>Used for events with additional subtype to differentiate notification message content</description>
    <inlineHelpText>Used for events with additional subtype to differentiate notification message content</inlineHelpText>
    <label>Event SubType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Notification_Message__c.field-meta.xml
<CustomField>
    <fullName>Notification_Message__c</fullName>
    <description>SMS/Push, message details populated by MC.</description>
    <inlineHelpText>SMS/Push, message details populated by MC.</inlineHelpText>
    <label>Notification Message</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Overload_Cars_Detail__c.field-meta.xml
<CustomField>
    <fullName>Overload_Cars_Detail__c</fullName>
    <description>overload event impacted equipment/cars detail information</description>
    <inlineHelpText>overload event impacted equipment/cars detail information</inlineHelpText>
    <label>Overload Cars Detail</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Log__c/fields/Total_Cars_Impacted__c.field-meta.xml
<CustomField>
    <fullName>Total_Cars_Impacted__c</fullName>
    <description>total number of cars (equipment) impacted in the event</description>
    <inlineHelpText>Total number of cars (equipment) impacted in the event</inlineHelpText>
    <label>Number of Cars Impacted</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ENS_OverloadedNotification.cls
public class ENS_OverloadedNotification {
    
    public static void overloadedResponseParser(String rawResponse,Notification_Log__c recNotificationLog){
        
        if(rawResponse != null){
            
            ENS_OverloadedWrapper wrapperList = (ENS_OverloadedWrapper)JSON.deserialize(rawResponse,ENS_OverloadedWrapper.class);
            
            Boolean OverloadFlag = false;    
            String overloadJson = '{"eqdtl":[{';
            String overloadJsonSub;   
            String overloadStatus= wrapperList.Payload[0].OverloadStatus;
            String olString = 'Overloaded';
            String olResString = 'RESOLVED';
            Integer count = 0;
            Integer prevCount;
            
            if(overloadStatus.equalsIgnoreCase(olResString)){
                recNotificationLog.Event_SubType__c='RESOLVED';
            }
            
            for(ENS_OverloadedWrapper.Payload objt :wrapperList.Payload){
                // construct notification_message
                if (recNotificationLog.Total_Cars_Impacted__c ==1 && overloadStatus.equalsIgnoreCase(olString)) {
                    recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c 
                        +' - ' +objt.EquipmentNumber
                        +' is overloaded and must be reduced to gross or diverted to an alternate destination.';
                    recNotificationLog.Equipment_Number__c =objt.EquipmentNumber;
                } 
                else if (recNotificationLog.Total_Cars_Impacted__c >1 && overloadStatus.equalsIgnoreCase(olString)){
                    recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c
                        +' - '+ Integer.valueOf(recNotificationLog.Total_Cars_Impacted__c)
                        +' railcars are overloaded and must be reduced to gross or diverted to an alternate location.';               
                } 
                else if (recNotificationLog.Total_Cars_Impacted__c ==1 && overloadStatus.equalsIgnoreCase(olResString)){
                    recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c
                        +' - ' +objt.EquipmentNumber
                        +' was overloaded. The overload has been resolved.';
                    recNotificationLog.Equipment_Number__c =objt.EquipmentNumber;                
                }
                else if (recNotificationLog.Total_Cars_Impacted__c >1 && overloadStatus.equalsIgnoreCase(olResString)){
                    recNotificationLog.Notification_Message__c =recNotificationLog.Customer_Alert_Name__c
                        +' - ' + Integer.valueOf(recNotificationLog.Total_Cars_Impacted__c)
                        +' shipments were overloaded. The overload has been resolved.';
                }
                
                if(count < 3998){
                    prevCount  = overloadJson.length();
                    if (OverloadFlag== true)
                    {
                        overloadJson+=',{';
                    }
                    overloadJson+= '"eqids":"'+objt.EquipmentNumber
                        +'","lastevent":"'+objt.LastEventDescription
                        +'","lasteventtime":"'+Datetime.valueOf(objt.LastEventTime.replace('T', ' ')).format()+' EST'
                        +'","lasteventloc":"'+objt.LastEvtCity+','+objt.LastEvtState
                        +'","scalewtgrs":"'+objt.ScaleWeightGross
                        +'","umltotalwt":"'+objt.UmlerTotalWeight
                        +'","origloc":"'+objt.OriginLocCity +','+objt.OriginLocState
                        +'","shipper":"'+objt.Name
                        +'"}';                    
                    OverloadFlag = true;
                    count =overloadJson.length();
                } 
            }
            
            if(count > 4000){
                system.debug('Inside Count' +count);
                overloadJsonSub = overloadJson.substring(0, prevCount);
                
            }
            else{
                overloadJsonSub = overloadJson.substring(0, count);
            }
            
            if(count == 0){
                overloadJsonSub+='';
            }
            else{
                overloadJsonSub+=']}';
            }
            
            recNotificationLog.Overload_Cars_Detail__c = overloadJsonSub.replace('null', '-');
        }
    }
    
}