force-app/main/default/objects/NSSales_AllCaseRollups__c/NSSales_AllCaseRollups__c.object-meta.xml
<CustomObject>
    <description>This object will display all cases that are under a given account based on the hierarchy. Cases from all child accounts should roll up to its ultimate parent.</description>
    <label>All Case Rollups</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Case Rollup</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Case Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NSSales_AllCaseRollups__c/fields/NSSales_Account__c.field-meta.xml
<CustomField>
    <fullName>NSSales_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Account for the case</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>All Case Rollups</relationshipLabel>
    <relationshipName>All_Case_Rollups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NSSales_AllCaseRollups__c/fields/NSSales_UltimateParentAccount__c.field-meta.xml
<CustomField>
    <fullName>NSSales_UltimateParentAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ultimate Parent Account of the case</description>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>All Case Rollups (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>All_Case_Rollups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NSSales_AllCaseRollupsTriggerHelper.cls
public class NSSales_AllCaseRollupsTriggerHelper {
    
    private static final String CLASS_NAME = 'NSSales_AllCaseRollupsTriggerHelper';
    private static final String METHOD_NAME1='updateCaseRollupRecord';
    private static final String METHOD_NAME2='getUltimateParent';
    
    public static void updateCaseRollupRecord(List<NSSales_AllCaseRollups__c> rollUpList)
    {
        List<NSSales_AllCaseRollups__c> rollUpListToUpdate = new List<NSSales_AllCaseRollups__c>();
        try{
            for(NSSales_AllCaseRollups__c rollUpRec : rollUpList)
            {
                if(rollUpRec.NSSales_UltimateParentAccount__c == null)
                {
                    rollUpRec.NSSales_UltimateParentAccount__c=getUltimateParent(rollUpRec.NSSales_Account__c);
                    rollUpListToUpdate.add(rollUpRec);
                }
                
            }
            if(test.isRunningTest()){
                integer I = 100/0;
            }
        }
        catch (Exception exp) {
            /*Inserting a record in Exception object*/
            NS_StaticVariablesUtility.createExceptionRecord(exp, CLASS_NAME, METHOD_NAME1);
        }       
    }
    
    public static Id getUltimateParent(Id accountId){
        Boolean topLevelParent = false;
        try{
            while ( !topLevelParent ) {
                Account acc = [ Select Id, ParentId From Account where Id =: accountId limit 1 ];
                if ( acc.ParentID != null ) {
                    accountId = acc.ParentID;
                }
                else {
                    topLevelParent = true;
                }
            }
            if(test.isRunningTest()){
                integer I = 100/0;
            }
            
        }
        catch (Exception exp) {
            /*Inserting a record in Exception object*/
            system.debug('exp-->'+exp);
            NS_StaticVariablesUtility.createExceptionRecord(exp, CLASS_NAME, METHOD_NAME2);
        } 
        return accountId ;
    }
    
}